//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@class MISSING_TYPE;

@interface _TtC16DaemoniOSLibrary33SDAuthenticationAKSPairingSession : _TtCs12_SwiftObject
{
    MISSING_TYPE *sessionID;	// 1869770847 = 0x6f72705f
    MISSING_TYPE *type;	// 1163157343 = 0x45545f5f
    MISSING_TYPE *aksManager;	// 0 = 0x0
    MISSING_TYPE *peerDevice;	// 5869512 = 0x598fc8
    MISSING_TYPE *role;	// 488 = 0x1e8
    MISSING_TYPE *aksSession;	// 5869512 = 0x598fc8
}

@end

