//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface SDAirDropHandlerPhoneLinks
{
}

- (id)suitableContentsDescription;	// IMP=0x004000000004da33
- (long long)transferTypes;	// IMP=0x001000000004d9ff
- (id)singleItemActionTitle;	// IMP=0x001000000004d9ee
- (_Bool)canHandleTransfer;	// IMP=0x001000000004d9d9
- (id)candidateIdentifiers;	// IMP=0x001000000004d92a
- (id)initWithTransfer:(id)arg1;	// IMP=0x001000000004d8f4

@end

