//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface SDAirDropHandlerVoiceMails
{
}

- (id)suitableContentsDescription;	// IMP=0x0040000000110453
- (long long)transferTypes;	// IMP=0x000000000011041e
- (_Bool)canHandleTransfer;	// IMP=0x0010000000110377

@end

