//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class NSString;

@interface SDAirDropHandlerFailed
{
}

- (_Bool)shouldEndAfterOpen;	// IMP=0x0020000000154f0d
- (id)suitableContentsDescription;	// IMP=0x0010000000154efb
- (id)suitableContentsTitle;	// IMP=0x0010000000154ee9
@property(readonly, nonatomic) NSString *errorDetailedString;
@property(readonly, nonatomic) NSString *errorString;
- (_Bool)canHandleTransfer;	// IMP=0x0010000000154d34
- (void)activate;	// IMP=0x0010000000154c66

@end

