//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface SDAirDropHandlerPDFs
{
}

- (id)suitableContentsDescription;	// IMP=0x004000000009b364
- (long long)transferTypes;	// IMP=0x001000000009b32f
- (_Bool)canHandleTransfer;	// IMP=0x001000000009b13f

@end

