//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface SDAirDropHandleriLifeLinks
{
}

- (id)suitableContentsDescription;	// IMP=0x004000000002be5d
- (long long)transferTypes;	// IMP=0x001000000002be29
- (_Bool)canHandleTransfer;	// IMP=0x001000000002be14

@end

