//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSMutableArray, NSMutableDictionary, NSString, NSXPCConnection, UISUIActivityViewControllerConfiguration;
@protocol OS_dispatch_queue;

@interface SDXPCHelperConnection : NSObject
{
    _Bool _activated;	// 8 = 0x8
    _Bool _needsTransactionRelease;	// 9 = 0x9
    _Bool _invalidateCalled;	// 10 = 0xa
    NSObject<OS_dispatch_queue> *_queue;	// 16 = 0x10
    NSXPCConnection *_connectionToService;	// 24 = 0x18
    unsigned long long _intervalID;	// 32 = 0x20
    NSString *_signpostName;	// 40 = 0x28
    long long _cacheAccessCount;	// 48 = 0x30
    NSMutableDictionary *_cacheAccessDict;	// 56 = 0x38
    struct os_unfair_lock_s _cacheAccessLock;	// 64 = 0x40
    UISUIActivityViewControllerConfiguration *_latestHostConfig;	// 72 = 0x48
    CDUnknownBlockType _interruptionHandler;	// 80 = 0x50
    CDUnknownBlockType _invalidationHandler;	// 88 = 0x58
    NSMutableArray *_queuedBlocks;	// 96 = 0x60
    NSString *_serviceName;	// 104 = 0x68
}

+ (id)identifierForColor:(id)arg1;	// IMP=0x00400000001504a1
+ (id)makeActivatedConnection;	// IMP=0x001000000014bdbc
+ (void)updateCacheFromSFCGImageData:(id)arg1 cacheKey:(id)arg2 contactIDs:(id)arg3;	// IMP=0x001000000014b678
- (void).cxx_destruct;	// IMP=0x0020000000151481
@property(readonly, copy, nonatomic) NSString *serviceName; // @synthesize serviceName=_serviceName;
@property(retain) NSMutableArray *queuedBlocks; // @synthesize queuedBlocks=_queuedBlocks;
@property(copy, nonatomic) CDUnknownBlockType invalidationHandler; // @synthesize invalidationHandler=_invalidationHandler;
@property(copy, nonatomic) CDUnknownBlockType interruptionHandler; // @synthesize interruptionHandler=_interruptionHandler;
- (void)setSessionKeepAliveTransactionIdentifier:(id)arg1;	// IMP=0x0010000000151318
- (void)_updateShareSheetHostConfiguration;	// IMP=0x0010000000151134
- (void)updateShareSheetHostConfiguration:(id)arg1;	// IMP=0x0010000000151123
- (id)perspectiveDataForNearbyBadgeWithCount:(long long)arg1;	// IMP=0x0010000000150f89
- (id)perspectiveDataForActivityMoreListEntryForActivityTitle:(id)arg1 labelColor:(id)arg2 activityCategory:(long long)arg3;	// IMP=0x0010000000150db3
- (id)perspectiveDataForActionPlatterWithTitle:(id)arg1 tintColor:(id)arg2;	// IMP=0x0010000000150be4
- (id)perspectiveDataForNameLabelWithString:(id)arg1 textColor:(id)arg2 maxNumberOfLines:(unsigned long long)arg3 isAirDrop:(_Bool)arg4 ignoreNameWrapping:(_Bool)arg5;	// IMP=0x00100000001509f0
- (id)perspectiveDataForUIActivityTitle:(id)arg1 textColor:(id)arg2;	// IMP=0x0010000000150821
- (id)keyDerivedFromRelevantTraitCollectionPropertiesWithOppositeUserInterfaceStyle;	// IMP=0x00100000001506ab
- (id)keyDerivedFromRelevantTraitCollectionProperties;	// IMP=0x001000000015054d
- (id)loadBatchImageCacheData:(id)arg1 cacheKey:(CDUnknownBlockType)arg2 mapCacheHitImage:(CDUnknownBlockType)arg3 runProxy:(CDUnknownBlockType)arg4 type:(id)arg5;	// IMP=0x001000000014fe3c
- (struct CGImage *)CGImgForNearbyBadgeWithCount:(long long)arg1;	// IMP=0x001000000014fad5
- (struct CGImage *)CGImgForActionPlatterWithTitle:(id)arg1 tintColor:(id)arg2;	// IMP=0x001000000014f6db
- (id)CGImgDataForActivityMoreListEntryForActivityTitle:(id)arg1 labelColor:(id)arg2 processOppositeColor:(_Bool)arg3 activityCategory:(long long)arg4;	// IMP=0x001000000014f101
- (struct CGImage *)CGImgForNameLabelWithString:(id)arg1 textColor:(id)arg2 maxNumberOfLines:(unsigned long long)arg3 isAirDrop:(_Bool)arg4 ignoreNameWrapping:(_Bool)arg5 processOppositeColor:(_Bool)arg6;	// IMP=0x001000000014e9c0
- (void)sendShareSheetInvocationMetricsWithAppBundleID:(id)arg1 numSuggestions:(long long)arg2 suggestionDisplayNames:(id)arg3 extensionsCacheResult:(id)arg4 isDarkMode:(_Bool)arg5 duration:(long long)arg6 isCollaborative:(_Bool)arg7;	// IMP=0x001000000014e6e2
- (id)MD5HashOfStrings:(id)arg1;	// IMP=0x001000000014e4fe
- (struct CGImage *)CGImageWithCacheKey:(id)arg1 contactIDs:(id)arg2 type:(id)arg3;	// IMP=0x001000000014e3d5
- (id)CGImgForUIActivityTitles:(id)arg1 foregroundColor:(id)arg2 processOppositeColor:(_Bool)arg3;	// IMP=0x001000000014d931
- (id);	// IMP=0x001000000014d753
- (id)_loadGroupContactIdentityImage:(id)arg1;	// IMP=0x001000000014d74b
- (id)monogramImagesForMultipleContacts:(id)arg1 style:(long long)arg2 diameter:(double)arg3 monogramsAsFlatImages:(_Bool)arg4;	// IMP=0x001000000014cecc
- (id)urlToCGImgDataForCallHandoffIconWithAppIconImageData:(id)arg1 contact:(id)arg2;	// IMP=0x001000000014cc24
- (id)groupMonogramImageDataForContacts:(id)arg1 style:(long long)arg2 diameter:(double)arg3 monogramsAsFlatImages:(_Bool)arg4 processOppositeBackgroundStyle:(_Bool)arg5;	// IMP=0x001000000014c4de
- (id)copyConversationIdentityImageIconDataForImage:(id)arg1 forConversationIdentifier:(id)arg2 style:(long long)arg3 diameter:(double)arg4 monogramsAsFlatImages:(_Bool)arg5 isContactImage:(_Bool *)arg6;	// IMP=0x001000000014c4d6
- (id)monogramImageDataForContact:(id)arg1 style:(long long)arg2 diameter:(double)arg3 monogramsAsFlatImages:(_Bool)arg4 isContactImage:(_Bool *)arg5;	// IMP=0x001000000014be5e
- (id)whitelistedDownloadsFolderURL;	// IMP=0x001000000014be56
- (void)dealloc;	// IMP=0x001000000014bcda
- (void)invalidate;	// IMP=0x001000000014b972
- (void)activate;	// IMP=0x001000000014b856
- (id)initWithQueue:(id)arg1 xrRenderingMode:(unsigned long long)arg2;	// IMP=0x001000000014b83d
- (id)initWithQueue:(id)arg1;	// IMP=0x001000000014b824
- (id)initWithQueue:(id)arg1 serviceName:(id)arg2;	// IMP=0x001000000014b723

@end

