//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class LNSystemProtocol, MISSING_TYPE, NSArray, NSDictionary, NSSet, NSString, NSUUID;

@interface _TtC10LinkDaemon8Registry : NSObject
{
    MISSING_TYPE *applicationSource;	// 8 = 0x8
    MISSING_TYPE *indexingQueue;	// 48 = 0x30
    MISSING_TYPE *observers;	// 56 = 0x38
    MISSING_TYPE *ready;	// 64 = 0x40
    MISSING_TYPE *lastMetadataAudit;	// 0 = 0x0
    MISSING_TYPE *store;	// 0 = 0x0
    MISSING_TYPE *appShortcutInterpolator;	// 1277952 = 0x138000
    MISSING_TYPE *examplePhraseInterpolator;	// 36864 = 0x9000
}

- (void).cxx_destruct;	// IMP=0x00200000000a27b9
- (id)init;	// IMP=0x00100000000a2783
- (void)unregisterBundleWithIdentifier:(NSString *)arg1 reply:(void (^)(NSError *))arg2;	// IMP=0x00100000000c7db4
- (void)scanBundlesWithReply:(void (^)(NSError *))arg1;	// IMP=0x00100000000c7753
- (void)resetWithReply:(void (^)(NSError *))arg1;	// IMP=0x00100000000c73cc
- (void)registerBundleWithIdentifier:(NSString *)arg1 force:(_Bool)arg2 reply:(void (^)(NSError *))arg3;	// IMP=0x00100000000c6d5e
- (void)relevantIntentsWithReply:(void (^)(NSDictionary *, NSError *))arg1;	// IMP=0x00100000000c5091
- (void)relevantIntentsForBundleIdentifier:(NSString *)arg1 reply:(void (^)(NSArray *, NSError *))arg2;	// IMP=0x00100000000c4a0a
- (void)propertiesForIdentifiers:(NSArray *)arg1 completionHandler:(void (^)(NSDictionary *, NSError *))arg2;	// IMP=0x00100000000c4754
- (void)autoShortcutsForLocaleIdentifier:(NSString *)arg1 completionHandler:(void (^)(NSDictionary *, NSError *))arg2;	// IMP=0x00100000000c3e93
- (void)autoShortcutsForBundleIdentifier:(NSString *)arg1 localeIdentifier:(NSString *)arg2 completionHandler:(void (^)(NSArray *, NSError *))arg3;	// IMP=0x00100000000c39cb
- (void)actionForBundleIdentifier:(NSString *)arg1 basePhraseTemplate:(NSString *)arg2 actionIdentifier:(NSString *)arg3 parameterIdentifier:(NSUUID *)arg4 completionHandler:(void (^)(LNAction *, NSError *))arg5;	// IMP=0x00100000000c33a2
- (void)actionForBundleIdentifier:(NSString *)arg1 basePhraseTemplate:(NSString *)arg2 parameterIdentifier:(NSUUID *)arg3 completionHandler:(void (^)(LNAction *, NSError *))arg4;	// IMP=0x00100000000c209e
- (void)actionForBundleIdentifier:(NSString *)arg1 basePhraseTemplate:(NSString *)arg2 completionHandler:(void (^)(LNAction *, NSError *))arg3;	// IMP=0x00100000000c1915
- (void)actionForBundleIdentifier:(NSString *)arg1 appShortcutIdentifier:(NSString *)arg2 parameterIdentifier:(NSString *)arg3 completionHandler:(void (^)(LNAction *, NSError *))arg4;	// IMP=0x00100000000c0e5b
- (void)metadataVersionForBundleIdentifier:(NSString *)arg1 reply:(void (^)(long long, NSError *))arg2;	// IMP=0x00100000000bfa6d
- (void)queriesForBundleIdentifier:(NSString *)arg1 ofType:(NSString *)arg2 reply:(void (^)(NSArray *, NSError *))arg3;	// IMP=0x00100000000bf746
- (void)queriesWithReply:(void (^)(NSDictionary *, NSError *))arg1;	// IMP=0x00100000000bf42f
- (void)examplePhrasesForBundleIdentifier:(NSString *)arg1 reply:(void (^)(NSArray *, NSError *))arg2;	// IMP=0x00100000000bf1c8
- (MISSING_TYPE *)enumsForBundleIdentifier:reply: /* Error: Ran out of types for this method. */;	// IMP=0x00100000000beeae
- (void)enumsWithReply:(void (^)(NSDictionary *, NSError *))arg1;	// IMP=0x00100000000bed45
- (void)entityIdentifiersForBundleIdentifier:(NSString *)arg1 reply:(void (^)(NSArray *, NSError *))arg2;	// IMP=0x00100000000beb55
- (void)entitiesForBundleIdentifier:(NSString *)arg1 reply:(void (^)(NSArray *, NSError *))arg2;	// IMP=0x00100000000be8c7
- (void)entitiesWithReply:(void (^)(NSDictionary *, NSError *))arg1;	// IMP=0x00100000000be75e
- (void)bundleRegistrationsWithReply:(void (^)(NSArray *, NSError *))arg1;	// IMP=0x00100000000be52c
- (void)bundlesWithReply:(void (^)(NSArray *, NSError *))arg1;	// IMP=0x00100000000be3db
- (void)actionIdentifiersForBundleIdentifier:(NSString *)arg1 reply:(void (^)(NSArray *, NSError *))arg2;	// IMP=0x00100000000be24b
- (void)actionsAndSystemProtocolDefaultsForBundleIdentifier:(NSString *)arg1 reply:(void (^)(NSDictionary *, NSError *))arg2;	// IMP=0x00100000000bdfa7
- (void)actionsWithFullyQualifiedIdentifiers:(NSArray *)arg1 reply:(void (^)(NSDictionary *, NSError *))arg2;	// IMP=0x00100000000bdd06
- (void)actionsForBundleIdentifier:(NSString *)arg1 reply:(void (^)(NSArray *, NSError *))arg2;	// IMP=0x00100000000bd9c8
- (void)actionsConformingToSystemProtocol:(LNSystemProtocol *)arg1 withParametersOfTypes:(NSDictionary *)arg2 bundleIdentifier:(NSString *)arg3 reply:(void (^)(NSDictionary *, NSError *))arg4;	// IMP=0x00100000000bd79c
- (void)actionsConformingToSystemProtocols:(NSSet *)arg1 logicalType:(unsigned long long)arg2 bundleIdentifier:(NSString *)arg3 reply:(void (^)(NSDictionary *, NSError *))arg4;	// IMP=0x00100000000bd3f6
- (void)actionsForBundleIdentifier:(NSString *)arg1 andActionIdentifier:(NSString *)arg2 reply:(void (^)(NSArray *, NSError *))arg3;	// IMP=0x00100000000bd03f
- (void)actionsWithReply:(void (^)(NSDictionary *, NSError *))arg1;	// IMP=0x00100000000bce36
- (void)fetchDatabaseURL:(CDUnknownBlockType)arg1;	// IMP=0x00100000000ac3f3

@end

