//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <CoreSpeechFoundation/CSPolicy.h>

@interface CSAdBlockerEnabledPolicy : CSPolicy
{
}

- (void)_addContinuousAudioFingerprintEnabledConditions;	// IMP=0x004000000001f9ae
- (void)_subscribeEventMonitors;	// IMP=0x001000000001f95b
- (id)init;	// IMP=0x001000000001f8fa

@end

