//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <CoreSpeechFoundation/CSEventMonitor.h>

@interface CSBluetoothWirelessSplitterMonitor : CSEventMonitor
{
}

+ (id)sharedInstance;	// IMP=0x00400000000fa2d6
- (void)updateSplitterState:(unsigned long long)arg1 shouldDisableSpeakerVerificationInSplitterMode:(_Bool)arg2;	// IMP=0x00400000000fa2d0
- (void)_stopMonitoring;	// IMP=0x00100000000fa2ca
- (void)_startMonitoringWithQueue:(id)arg1;	// IMP=0x00100000000fa2c4
- (unsigned long long)splitterState;	// IMP=0x00100000000fa2bc
- (void)splitterState:(CDUnknownBlockType)arg1;	// IMP=0x00100000000fa2b6
- (id)init;	// IMP=0x00100000000fa27c

@end

