//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class CSGibraltarVoiceTriggerHandler, NSString, NSXPCListener;
@protocol OS_dispatch_queue;

@interface CSCoreSpeechServicesListener : NSObject
{
    CSGibraltarVoiceTriggerHandler *_gibraltarVoiceTriggerHandler;	// 8 = 0x8
    NSObject<OS_dispatch_queue> *_queue;	// 16 = 0x10
    NSXPCListener *_servicesListener;	// 24 = 0x18
}

- (void).cxx_destruct;	// IMP=0x002000000003fc1c
@property(retain, nonatomic) NSXPCListener *servicesListener; // @synthesize servicesListener=_servicesListener;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *queue; // @synthesize queue=_queue;
@property(retain, nonatomic) CSGibraltarVoiceTriggerHandler *gibraltarVoiceTriggerHandler; // @synthesize gibraltarVoiceTriggerHandler=_gibraltarVoiceTriggerHandler;
- (oneway void)getFirstPassRunningMode:(CDUnknownBlockType)arg1;	// IMP=0x001000000003faff
- (oneway void)requestUpdatedSATAudio:(CDUnknownBlockType)arg1;	// IMP=0x001000000003fae9
- (oneway void)clearTriggerCount:(CDUnknownBlockType)arg1;	// IMP=0x001000000003fa24
- (oneway void)getTriggerCount:(CDUnknownBlockType)arg1;	// IMP=0x001000000003f95d
- (oneway void)setDelayInterstitialSounds:(id)arg1 level:(long long)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x001000000003f82e
- (oneway void)getVoiceTriggerRTModelRequestOptionsWithEndpointId:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x001000000003f77b
- (oneway void)getCurrentVoiceTriggerLocaleWithEndpointId:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x001000000003f6c5
- (oneway void)getTestResponse:(CDUnknownBlockType)arg1;	// IMP=0x001000000003f620
- (_Bool)listener:(id)arg1 shouldAcceptNewConnection:(id)arg2;	// IMP=0x001000000003f4e9
- (_Bool)_servicesListenerShouldAcceptNewConnection:(id)arg1;	// IMP=0x001000000003f331
- (void)listen;	// IMP=0x001000000003f257
- (id)init;	// IMP=0x001000000003f1ff

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"NSString",?,R,C

@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

