//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@interface CSDarkWakePowerAssertionMac : NSObject
{
}

- (void)invalidate;	// IMP=0x004000000009f715
- (id)init;	// IMP=0x001000000009f707
- (id)initWithDescription:(id)arg1 timeout:(double)arg2;	// IMP=0x001000000009f6f9

@end

