//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSString;
@protocol CSAttendingInitiating;

@interface CSLocalAttendingHintProvider : NSObject
{
    id <CSAttendingInitiating> _initiator;	// 8 = 0x8
}

- (void).cxx_destruct;	// IMP=0x0020000000015c4d
@property(retain, nonatomic) id <CSAttendingInitiating> initiator; // @synthesize initiator=_initiator;
- (void)postAttendingJarvisHintWithInfo:(id)arg1;	// IMP=0x0010000000015c1c
- (void)postAttendingMagusNotSupportedHintWithInfo:(id)arg1;	// IMP=0x0010000000015c06
- (void)postAttendingTriggerForSiriPromptHintWithInfo:(id)arg1;	// IMP=0x0010000000015bf0
- (void)postAttendingStopHintWithInfo:(id)arg1;	// IMP=0x0010000000015bda
- (void)postAttendingStartHintWithInfo:(id)arg1;	// IMP=0x0010000000015bc4
- (void)postAttendingWillStartHintWithInfo:(id)arg1;	// IMP=0x0010000000015bae
- (id)initWithAttendingIniting:(id)arg1;	// IMP=0x0010000000015b43

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"NSString",?,R,C

@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

