//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSHashTable;
@protocol OS_dispatch_queue;

@interface CSOpportuneSpeakBehaviorMonitor : NSObject
{
    NSObject<OS_dispatch_queue> *_queue;	// 8 = 0x8
    NSHashTable *_observers;	// 16 = 0x10
}

+ (id)sharedInstance;	// IMP=0x00400000000ef1d8
- (void).cxx_destruct;	// IMP=0x00200000000eea95
@property(retain, nonatomic) NSHashTable *observers; // @synthesize observers=_observers;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *queue; // @synthesize queue=_queue;
- (void)notifyDidStopStream:(id)arg1;	// IMP=0x00100000000ee9d2
- (void)notifyWillStopStream:(id)arg1;	// IMP=0x00100000000ee945
- (void)notifyDidStartStreamWithContext:(id)arg1 audioProviderUUID:(id)arg2 successfully:(_Bool)arg3 option:(id)arg4;	// IMP=0x00100000000ee859
- (void)notifyWillStartStreamWithContext:(id)arg1 audioProviderUUID:(id)arg2 option:(id)arg3;	// IMP=0x00100000000ee774
- (void)unregisterObserver:(id)arg1;	// IMP=0x00100000000ee6e7
- (void)registerObserver:(id)arg1;	// IMP=0x00100000000ee65a
- (id)init;	// IMP=0x00100000000ee5d3

@end

