//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <CoreSpeechFoundation/CSEventMonitor.h>

@interface CSSpeechEndpointAssetMetaUpdateMonitor : CSEventMonitor
{
    int _notifyToken;	// 8 = 0x8
}

+ (id)sharedInstance;	// IMP=0x004000000009d583
- (void)_notifyObserver:(id)arg1;	// IMP=0x002000000009d4eb
- (void)_didReceiveNewSpeechEndpointAssetMetaData;	// IMP=0x001000000009d424
- (void)_stopMonitoring;	// IMP=0x001000000009d381
- (void)_startMonitoringWithQueue:(id)arg1;	// IMP=0x001000000009d221
- (id)init;	// IMP=0x001000000009d1df

@end

