//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSXPCConnection;

@interface SpeechModelTrainingClient : NSObject
{
    NSXPCConnection *_smtConnection;	// 8 = 0x8
}

+ (void)initialize;	// IMP=0x0040000000004775
- (void).cxx_destruct;	// IMP=0x0020000000003e98
- (void)invalidate;	// IMP=0x0010000000003e2d
- (void)xpcExitClean;	// IMP=0x0010000000003de9
- (void)generateConfusionPairsWithUUID:(id)arg1 parameters:(id)arg2 language:(id)arg3 task:(id)arg4 samplingRate:(unsigned long long)arg5 recognizedNbest:(id)arg6 recognizedText:(id)arg7 correctedText:(id)arg8 selectedAlternatives:(id)arg9 completion:(CDUnknownBlockType)arg10;	// IMP=0x0010000000003c53
- (void)generateConfusionPairsWithUUID:(id)arg1 parameters:(id)arg2 language:(id)arg3 task:(id)arg4 samplingRate:(unsigned long long)arg5 recognizedTokens:(id)arg6 recognizedText:(id)arg7 correctedText:(id)arg8 selectedAlternatives:(id)arg9 completion:(CDUnknownBlockType)arg10;	// IMP=0x0010000000003abd
- (void)generateAudioWithTexts:(id)arg1 language:(id)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x00100000000039d3
- (void)buildPhoneticMatchWithLanguage:(id)arg1 saveIntermediateFsts:(_Bool)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x00100000000038a3
- (void)trainGlobalNNLMwithFidesSessionURL:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x00100000000037d8
- (void)trainPersonalizedLMWithLanguage:(id)arg1 configuration:(id)arg2 fides:(_Bool)arg3 activity:(id)arg4 completion:(CDUnknownBlockType)arg5;	// IMP=0x001000000000363a
- (void)trainPersonalizedLMWithLanguage:(id)arg1 configuration:(id)arg2 asset:(id)arg3 fides:(_Bool)arg4 activity:(id)arg5 completion:(CDUnknownBlockType)arg6;	// IMP=0x0010000000003610
- (void)trainPersonalizedLMWithLanguage:(id)arg1 directory:(id)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x00100000000035e9
- (void)trainPersonalizedLMWithLanguage:(id)arg1 configuration:(id)arg2 asset:(id)arg3 directory:(id)arg4 completion:(CDUnknownBlockType)arg5;	// IMP=0x0010000000002ff2
- (void)upperCaseString:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x0010000000002e80
- (id)_serviceProxyWithErrorHandler:(CDUnknownBlockType)arg1;	// IMP=0x0010000000002e6a
- (void)dealloc;	// IMP=0x0010000000002de1
- (id)initWithServiceName:(id)arg1;	// IMP=0x0010000000002dcf
- (id)init;	// IMP=0x0010000000002bcc

@end

