//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@interface _TtC17identityservicesd23IDSSenderKeySendContext : NSObject
{
}

+ (id)remoteDeviceUpdate;	// IMP=0x00200000005463e0
+ (id)keyRecovery;	// IMP=0x00100000005463b0
+ (id)keyRoll;	// IMP=0x0010000000546350
+ (id)handleDonation;	// IMP=0x00100000005462f0
+ (id)iMessageReceive;	// IMP=0x0010000000546290
+ (id)iMessageSend;	// IMP=0x0010000000546230
+ (id)idstool;	// IMP=0x00100000005461d0
- (void).cxx_destruct;	// IMP=0x0040000000546490
- (id)init;	// IMP=0x0010000000546410

@end

