//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class IDSPushToken, IDSRealTimeEncryptionIdentity, MISSING_TYPE, NSData, NSDictionary, _TtC17identityservicesd36IDSGroupEncryptionIdentityController;
@protocol _TtP17identityservicesd19IDSDSessionProvider_, _TtP17identityservicesd27IDSGroupPushHandlerProtocol_;

@interface _TtC17identityservicesd29IDSGroupEncryptionController2 : NSObject
{
    MISSING_TYPE *l;	// 1936941420 = 0x7373616c
    MISSING_TYPE *q;	// 1163157343 = 0x45545f5f
    MISSING_TYPE *groupsLock;	// 1438866880 = 0x55c35dc0
    MISSING_TYPE *publicIdentitiesLock;	// 823525349 = 0x3115ffe5
    MISSING_TYPE *delegate;	// 0 = 0x0
    MISSING_TYPE *config;	// 7815275 = 0x77406b
    MISSING_TYPE *identityController;	// 16460 = 0x404c
    MISSING_TYPE *sessionProvider;	// 7815275 = 0x77406b
    MISSING_TYPE *pushHandler;	// 0 = 0x0
    MISSING_TYPE *cryptoHandler;	// 2 = 0x2
}

- (void).cxx_destruct;	// IMP=0x0040000000577d70
- (id)init;	// IMP=0x0010000000577d10
@property(nonatomic, readonly) IDSRealTimeEncryptionIdentity *objcPreviousIdentity;
@property(nonatomic, readonly) IDSRealTimeEncryptionIdentity *objcIdentity;
@property(nonatomic, readonly) IDSRealTimeEncryptionIdentity *objcPreviousPublicIdentity;
@property(nonatomic, readonly) IDSRealTimeEncryptionIdentity *objcPublicIdentity;
- (void)cleanUpGroupForID:(id)arg1 after:(double)arg2;	// IMP=0x0010000000577650
- (id)objcPublicIdentityForPushToken:(id)arg1;	// IMP=0x0010000000577010
- (void)receivePublicKey:(id)arg1 forPushToken:(id)arg2 fromURI:(id)arg3 groupID:(id)arg4 sessionID:(id)arg5 serverDate:(id)arg6 wrapMode:(long long)arg7;	// IMP=0x0010000000576d00
- (void)receivePublicIdentity:(id)arg1;	// IMP=0x0010000000575ee0
- (id)groupForID:(id)arg1;	// IMP=0x0010000000575780
- (id)initWithDelegate:(id)arg1 config:(id)arg2 sessionProvider:(id)arg3 identityController:(id)arg4 pushHandler:(id)arg5;	// IMP=0x00100000005755c0
@property(nonatomic, readonly) NSDictionary *publicKeys;
@property(nonatomic, readonly) NSData *previousPublicIdentityData;
@property(nonatomic, readonly) struct __SecKey *previousPublicIdentityKey;
@property(nonatomic, readonly) struct __SecKey *previousFullIdentityKey;
@property(nonatomic, readonly) NSData *publicIdentityData;
@property(nonatomic, readonly) struct __SecKey *publicIdentityKey;
@property(nonatomic, readonly) struct __SecKey *fullIdentityKey;
@property(nonatomic, readonly) long long publicIdentityWrapMode;
@property(nonatomic, readonly) IDSPushToken *pushToken;
@property(nonatomic, readonly) id <_TtP17identityservicesd27IDSGroupPushHandlerProtocol_> pushHandler; // @synthesize pushHandler;
@property(nonatomic, readonly) id <_TtP17identityservicesd19IDSDSessionProvider_> sessionProvider; // @synthesize sessionProvider;
@property(nonatomic, readonly) _TtC17identityservicesd36IDSGroupEncryptionIdentityController *identityController; // @synthesize identityController;

@end

