//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class IDSDGroupContextNotifyingObserver, NSMutableArray, NSString, NSXPCConnection, NSXPCListener;

@interface IDSDaemonXPCInterface : NSObject
{
    NSXPCListener *_listener;	// 8 = 0x8
    NSXPCConnection *_connection;	// 16 = 0x10
    IDSDGroupContextNotifyingObserver *_observer;	// 24 = 0x18
    NSMutableArray *_observerProxies;	// 32 = 0x20
}

+ (id)sharedInstance;	// IMP=0x0020000000226324
- (void).cxx_destruct;	// IMP=0x0020000000227d35
@property(retain, nonatomic) NSMutableArray *observerProxies; // @synthesize observerProxies=_observerProxies;
@property(retain, nonatomic) IDSDGroupContextNotifyingObserver *observer; // @synthesize observer=_observer;
@property(retain, nonatomic) NSXPCConnection *connection; // @synthesize connection=_connection;
@property(retain, nonatomic) NSXPCListener *listener; // @synthesize listener=_listener;
- (void)didReceiveRegistrationIdentityUpdate;	// IMP=0x0010000000227a34
- (void)didReceiveDecryptionFailureForGroup:(id)arg1;	// IMP=0x001000000022773f
- (void)didUpdateGroup:(id)arg1 withNewGroup:(id)arg2;	// IMP=0x00100000002273d4
- (void)didCacheGroup:(id)arg1;	// IMP=0x00100000002270df
- (void)didCreateGroup:(id)arg1;	// IMP=0x0010000000226dea
- (_Bool)listener:(id)arg1 shouldAcceptNewConnection:(id)arg2;	// IMP=0x00100000002265fc
- (id)groupContextController;	// IMP=0x00100000002265e3
- (id)init;	// IMP=0x0010000000226379

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"NSString",?,R,C

@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

