//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSMutableDictionary;

@interface IDSDevicePolicyController : NSObject
{
    NSMutableDictionary *_devices;	// 8 = 0x8
    struct os_unfair_lock_s _lock;	// 16 = 0x10
}

+ (id)sharedInstance;	// IMP=0x004000000049eaad
- (void).cxx_destruct;	// IMP=0x002000000049f32a
- (_Bool)shouldBlackOutDeviceWithCbuuid:(id)arg1;	// IMP=0x001000000049ee9c
- (void)endFairplayAuthenticationForDeviceWithCbuuid:(id)arg1;	// IMP=0x001000000049ee1c
- (void)startFairplayAuthenticationForDeviceWithCbuuid:(id)arg1;	// IMP=0x001000000049eb5f
- (id)init;	// IMP=0x001000000049eb02

@end

