//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class IDSURI, NSArray, NSMutableDictionary, NSString;
@protocol OS_dispatch_queue;

@interface IDSEndpointSubscription : NSObject
{
    NSString *_serviceIdentifier;	// 8 = 0x8
    IDSURI *_localURI;	// 16 = 0x10
    NSArray *_subscribedURIs;	// 24 = 0x18
    CDUnknownBlockType _resolvedEndpointsDidUpdateHandler;	// 32 = 0x20
    NSObject<OS_dispatch_queue> *_queue;	// 40 = 0x28
    NSMutableDictionary *_endpointMap;	// 48 = 0x30
    NSString *_peerIDManagerToken;	// 56 = 0x38
}

- (void).cxx_destruct;	// IMP=0x0020000000022fa0
@property(readonly, nonatomic) NSString *peerIDManagerToken; // @synthesize peerIDManagerToken=_peerIDManagerToken;
@property(retain, nonatomic) NSMutableDictionary *endpointMap; // @synthesize endpointMap=_endpointMap;
@property(readonly, nonatomic) NSObject<OS_dispatch_queue> *queue; // @synthesize queue=_queue;
@property(copy, nonatomic) CDUnknownBlockType resolvedEndpointsDidUpdateHandler; // @synthesize resolvedEndpointsDidUpdateHandler=_resolvedEndpointsDidUpdateHandler;
@property(readonly, nonatomic) NSArray *subscribedURIs; // @synthesize subscribedURIs=_subscribedURIs;
@property(readonly, nonatomic) IDSURI *localURI; // @synthesize localURI=_localURI;
@property(readonly, nonatomic) NSString *serviceIdentifier; // @synthesize serviceIdentifier=_serviceIdentifier;
- (void)_signalDidUpdateEndpoints;	// IMP=0x0010000000022e6b
- (void)_noteSourceDidDiscoverEndpointMap:(id)arg1 forLocalURI:(id)arg2;	// IMP=0x0010000000022a3a
- (void)_registerEndpointQueryCompletionBlock;	// IMP=0x0010000000022838
- (id)resolvedEndpoints;	// IMP=0x0010000000022696
- (void)initializeWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x001000000002229d
- (id)peerIDManager;	// IMP=0x0010000000022284
- (id)description;	// IMP=0x00100000000221aa
- (void)dealloc;	// IMP=0x0010000000022134
- (id)initWithServiceIdentifier:(id)arg1 localURI:(id)arg2 subscribedURIs:(id)arg3 queue:(id)arg4;	// IMP=0x0010000000022005

@end

