//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <Foundation/NSProxy.h>

@class NSArray;

@interface IDSNWBroadcastProxy : NSProxy
{
    NSArray *_targets;	// 8 = 0x8
}

- (void).cxx_destruct;	// IMP=0x00200000001eb49b
@property(retain, nonatomic) NSArray *targets; // @synthesize targets=_targets;
- (void)forwardInvocation:(id)arg1;	// IMP=0x00100000001eb2cb
- (id)methodSignatureForSelector:(SEL)arg1;	// IMP=0x00100000001eb16b
- (id)initWithTargets:(id)arg1;	// IMP=0x00100000001eb146

@end

