//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class IDSNRBluetoothLinkPreferences, IDSNRDeviceIdentifier, NSSet;

@interface IDSNRDevicePreferences : NSObject
{
    _Bool _hasPreferWiFiRequest;	// 8 = 0x8
    IDSNRBluetoothLinkPreferences *_bluetoothLinkPreferences;	// 16 = 0x10
    IDSNRDeviceIdentifier *_deviceIdentifier;	// 24 = 0x18
    NSSet *_policyTrafficClassifiers;	// 32 = 0x20
}

- (void).cxx_destruct;	// IMP=0x0020000000005acf
@property(retain, nonatomic) NSSet *policyTrafficClassifiers; // @synthesize policyTrafficClassifiers=_policyTrafficClassifiers;
@property(readonly, nonatomic) _Bool hasPreferWiFiRequest; // @synthesize hasPreferWiFiRequest=_hasPreferWiFiRequest;
@property(readonly, retain, nonatomic) IDSNRDeviceIdentifier *deviceIdentifier; // @synthesize deviceIdentifier=_deviceIdentifier;
@property(retain, nonatomic) IDSNRBluetoothLinkPreferences *bluetoothLinkPreferences; // @synthesize bluetoothLinkPreferences=_bluetoothLinkPreferences;
- (void)deviceSetupCompleted;	// IMP=0x0010000000005a80
- (void)deviceSetupStarted;	// IMP=0x0010000000005a7a
- (void)cancel;	// IMP=0x0010000000005a74
- (void)removeAllQuickRelayRequests;	// IMP=0x0010000000005a6e
- (void)removeQuickRelayRequest;	// IMP=0x0010000000005a68
- (void)addQuickRelayRequest;	// IMP=0x0010000000005a62
- (void)removePreferWiFiRequest;	// IMP=0x0010000000005a5c
- (void)addPreferWiFiRequest;	// IMP=0x0010000000005a56
- (id)init;	// IMP=0x0010000000005a48
- (id)initWithDeviceIdentifier:(id)arg1;	// IMP=0x0010000000005a3a

@end

