//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class IDSKeychainWrapper, IMSystemMonitor, NSString;

@interface IDSPersistentMapKeychainPersister : NSObject
{
    NSString *_identifier;	// 8 = 0x8
    IDSKeychainWrapper *_keychainWrapper;	// 16 = 0x10
    IMSystemMonitor *_systemMonitor;	// 24 = 0x18
}

- (void).cxx_destruct;	// IMP=0x00200000003b63a4
@property(readonly, nonatomic) IMSystemMonitor *systemMonitor; // @synthesize systemMonitor=_systemMonitor;
@property(readonly, nonatomic) IDSKeychainWrapper *keychainWrapper; // @synthesize keychainWrapper=_keychainWrapper;
@property(retain, nonatomic) NSString *identifier; // @synthesize identifier=_identifier;
- (void)purgeData;	// IMP=0x00100000003b6244
- (void)saveData:(id)arg1 allowBackup:(_Bool)arg2;	// IMP=0x00100000003b6006
- (id)data;	// IMP=0x00100000003b5dfd
@property(readonly, nonatomic) _Bool isAvailable;
- (id)initWithIdentifier:(id)arg1 keychainWrapper:(id)arg2 systemMonitor:(id)arg3;	// IMP=0x00100000003b5cfd

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"NSString",?,R,C

@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

