//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <ProtocolBuffer/PBCodable.h>

@class NSData;

@interface IDSProtoApplicationKeyEntry : PBCodable
{
    int _keyIndex;	// 8 = 0x8
    NSData *_publicIdentity;	// 16 = 0x10
    CDStruct_31fd730f _has;	// 24 = 0x18
}

- (void).cxx_destruct;	// IMP=0x00200000004953bf
@property(retain, nonatomic) NSData *publicIdentity; // @synthesize publicIdentity=_publicIdentity;
- (void)mergeFrom:(id)arg1;	// IMP=0x0010000000495337
- (unsigned long long)hash;	// IMP=0x00100000004952ea
- (_Bool)isEqual:(id)arg1;	// IMP=0x001000000049522f
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x001000000049519b
- (void)copyTo:(id)arg1;	// IMP=0x0010000000495138
- (void)writeTo:(id)arg1;	// IMP=0x00100000004950d2
- (_Bool)readFrom:(id)arg1;	// IMP=0x00100000004950c5
- (id)dictionaryRepresentation;	// IMP=0x0010000000494e03
- (id)description;	// IMP=0x0010000000494d54
@property(readonly, nonatomic) _Bool hasPublicIdentity;
- (int)StringAsKeyIndex:(id)arg1;	// IMP=0x0010000000494cda
- (id)keyIndexAsString:(int)arg1;	// IMP=0x0010000000494c85
@property(nonatomic) _Bool hasKeyIndex;
@property(nonatomic) int keyIndex; // @synthesize keyIndex=_keyIndex;

@end

