//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@interface IDSPACStateTracker : NSObject
{
}

+ (id)sharedInstance;	// IMP=0x004000000016c9f0
- (void)noteAuthenticationFinished;	// IMP=0x004000000016db8c
- (void)noteAuthenticationStarted;	// IMP=0x001000000016db1a
- (void)notePNRError:(long long)arg1;	// IMP=0x001000000016daaf
- (void)notePNRSuccess;	// IMP=0x001000000016da44
- (void)notePhoneAuthCertGained;	// IMP=0x001000000016d9b4
- (id)_simTypeString:(unsigned long long)arg1;	// IMP=0x001000000016d989
- (id)_pacRemovalReasonToString:(long long)arg1;	// IMP=0x001000000016d965
- (void)notePhoneAuthCertLost:(long long)arg1;	// IMP=0x001000000016d862
- (id)underlyingErrorForPACState:(id)arg1;	// IMP=0x001000000016d3a8
- (id)fetchCurrentPACState;	// IMP=0x001000000016ca8f

@end

