//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class IMTimer, NSArray, NSMutableArray, NSMutableDictionary, NSRecursiveLock;
@protocol OS_dispatch_queue;

@interface IDSRegistrationKeychainManager : NSObject
{
    NSMutableDictionary *_tempPhoneCredentials;	// 8 = 0x8
    NSMutableDictionary *_smsSignatures;	// 16 = 0x10
    NSMutableDictionary *_authenticationCerts;	// 24 = 0x18
    NSMutableArray *_registrationData;	// 32 = 0x20
    IMTimer *_purgeTimer;	// 40 = 0x28
    NSRecursiveLock *_lock;	// 48 = 0x30
    CDUnknownBlockType _purgeCancelBlock;	// 56 = 0x38
    CDUnknownBlockType _purgeEnqueueBlock;	// 64 = 0x40
    _Bool _loaded;	// 72 = 0x48
    NSObject<OS_dispatch_queue> *_saveQueue;	// 80 = 0x50
}

+ (id)keychainAccessGroupForVersion:(unsigned long long)arg1;	// IMP=0x004000000027000f
+ (id)keychainAccountForVersion:(unsigned long long)arg1;	// IMP=0x001000000026ffbc
+ (id)keychainServiceForVersion:(unsigned long long)arg1;	// IMP=0x001000000026ff8e
+ (id)sharedInstance;	// IMP=0x001000000026fa90
- (void).cxx_destruct;	// IMP=0x0020000000274aa6
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *saveQueue; // @synthesize saveQueue=_saveQueue;
- (void)setTempPhoneCredential:(id)arg1 forID:(id)arg2;	// IMP=0x00100000002748d8
- (id)tempPhoneCredentialForID:(id)arg1;	// IMP=0x001000000027478b
- (void)setSMSSignature:(id)arg1 mainID:(id)arg2;	// IMP=0x001000000027453a
- (id)smsIDs;	// IMP=0x0010000000274424
- (id)smsSignatureForID:(id)arg1;	// IMP=0x0010000000274245
- (void)setAuthenticationCert:(id)arg1 forID:(id)arg2;	// IMP=0x001000000027408b
- (id)authenticationCertForID:(id)arg1;	// IMP=0x0010000000273ff2
- (_Bool)removeAllRegistrations;	// IMP=0x00100000002738ac
- (_Bool)removeRegistration:(id)arg1;	// IMP=0x001000000027365e
- (_Bool)addRegistration:(id)arg1;	// IMP=0x001000000027344c
@property(readonly, copy, nonatomic) NSArray *registrations; // @dynamic registrations;
- (id)registrationWithServiceType:(id)arg1 registrationType:(int)arg2 value:(id)arg3;	// IMP=0x0010000000272f97
- (void)reloadFromKeychain;	// IMP=0x00100000002721e7
- (void)_reloadFromDictionary:(id)arg1;	// IMP=0x00100000002716a9
- (void)_loadIfNeeded;	// IMP=0x001000000027164c
- (void)_setPurgeTimer;	// IMP=0x0010000000271619
- (void)_flush;	// IMP=0x0010000000271386
- (_Bool)saveToKeychain;	// IMP=0x0010000000271374
- (_Bool)_saveToKeychain;	// IMP=0x00100000002712bb
- (_Bool)__saveToKeychain;	// IMP=0x0010000000270023
- (void)systemDidFinishMigration;	// IMP=0x001000000026fee1
- (void)_purgeTimerFiredOnMain;	// IMP=0x001000000026fe60
- (void)dealloc;	// IMP=0x001000000026fdeb
- (id)init;	// IMP=0x001000000026fae5

@end

