//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <FTServices/FTIDSMessage.h>

@class NSArray, NSString;

@interface IDSSIMDeactivationInfoMessage : FTIDSMessage
{
    long long _deviceTime;	// 232 = 0xe8
    NSString *_homePlmn;	// 240 = 0xf0
    NSArray *_events;	// 248 = 0xf8
}

- (void).cxx_destruct;	// IMP=0x002000000001f1b6
@property(retain) NSArray *events; // @synthesize events=_events;
@property(retain) NSString *homePlmn; // @synthesize homePlmn=_homePlmn;
@property long long deviceTime; // @synthesize deviceTime=_deviceTime;
- (id)messageBody;	// IMP=0x001000000001eb40
- (id)requiredKeys;	// IMP=0x001000000001eb06
- (id)bagKey;	// IMP=0x001000000001eaf9
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x001000000001ea2b

@end

