//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@interface IDSUserProperties : NSObject
{
    _Bool _disableRegistration;	// 8 = 0x8
}

+ (_Bool);	// IMP=0x002000000000ae19
@property(readonly, nonatomic) _Bool disableRegistration; // @synthesize disableRegistration=_disableRegistration;
- (id)initWithCoder:(id)arg1;	// IMP=0x001000000000ae44
- (void)encodeWithCoder:(id)arg1;	// IMP=0x001000000000ae21
- (id)description;	// IMP=0x001000000000adad
- (unsigned long long)hash;	// IMP=0x001000000000ad75
- (_Bool)isEqualToUserProperties:(id)arg1;	// IMP=0x001000000000ad2e
- (_Bool)isEqual:(id)arg1;	// IMP=0x001000000000acd5
- (id)propsByupdatingDisableRegistration:(_Bool)arg1;	// IMP=0x001000000000acaf
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x001000000000ac8c

@end

