//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSArray, NSAttributedString, NSNumber, NSPersonNameComponents, NSString, TVSObserverSet, TVSUIAccountProfilePictureObserver, UIImage;

@interface TVSSSuggestedUser : NSObject
{
    TVSObserverSet *_observers;	// 8 = 0x8
    TVSUIAccountProfilePictureObserver *_userProfilePictureObserver;	// 16 = 0x10
    _Bool _currentUser;	// 24 = 0x18
    _Bool _suggestedUser;	// 25 = 0x19
    NSString *_identifier;	// 32 = 0x20
    NSPersonNameComponents *_personNameComponents;	// 40 = 0x28
    NSString *_formattedShortName;	// 48 = 0x30
    UIImage *_image;	// 56 = 0x38
}

- (void).cxx_destruct;	// IMP=0x0020000000098270
@property(readonly, nonatomic, getter=isSuggestedUser) _Bool suggestedUser; // @synthesize suggestedUser=_suggestedUser;
@property(readonly, nonatomic, getter=isCurrentUser) _Bool currentUser; // @synthesize currentUser=_currentUser;
@property(readonly, nonatomic) UIImage *image; // @synthesize image=_image;
@property(readonly, copy, nonatomic) NSString *formattedShortName; // @synthesize formattedShortName=_formattedShortName;
@property(readonly, copy, nonatomic) NSPersonNameComponents *personNameComponents; // @synthesize personNameComponents=_personNameComponents;
@property(readonly, copy, nonatomic) NSString *identifier; // @synthesize identifier=_identifier;
- (void)_updateWithSuggestedUserProfile:(id)arg1 notifyObservers:(_Bool)arg2;	// IMP=0x0010000000097f30
- (void)_updateWithUserImage:(id)arg1;	// IMP=0x0010000000097d20
- (id)_userProfilePictureObserver;	// IMP=0x0010000000097d00
@property(readonly, copy) NSString *debugDescription;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"NSString",?,R,C

@property(readonly, copy) NSString *description;
- (id)descriptionBuilderWithMultilinePrefix:(id)arg1;	// IMP=0x0010000000097ba0
- (id)descriptionWithMultilinePrefix:(id)arg1;	// IMP=0x0010000000097b00
- (id)succinctDescriptionBuilder;	// IMP=0x0010000000097a20
- (id)succinctDescription;	// IMP=0x00100000000979b0
- (void)_updateWithSuggestedUserProfile:(id)arg1;	// IMP=0x00100000000971d0
- (void)removeObserver:(id)arg1;	// IMP=0x0010000000096f20
- (void)addObserver:(id)arg1;	// IMP=0x0010000000096bd0
- (id)_initWithSuggestedUserProfile:(id)arg1 userProfilePictureService:(id)arg2;	// IMP=0x0010000000095cb0
@property(readonly, nonatomic) UIImage *contentImage;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"UIImage",?,R,N

@property(readonly, nonatomic) NSString *contentTitle;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"NSString",?,R,N


// Remaining properties
@property(readonly, nonatomic) NSAttributedString *contentAttrText1;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"NSAttributedString",?,R,N

@property(readonly, nonatomic) NSAttributedString *contentAttrText2;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"NSAttributedString",?,R,N

@property(readonly, nonatomic) NSAttributedString *contentAttrText3;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"NSAttributedString",?,R,N

@property(readonly, nonatomic) NSArray *contentChildIdentifiers;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"NSArray",?,R,N

@property(readonly, nonatomic) UIImage *contentImage1;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"UIImage",?,R,N

@property(readonly, nonatomic) UIImage *contentImage2;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"UIImage",?,R,N

@property(readonly, nonatomic) UIImage *contentImage3;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"UIImage",?,R,N

@property(readonly, nonatomic) UIImage *contentImage4;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"UIImage",?,R,N

@property(nonatomic) _Bool contentIsDisabled;
// Preceding property had unknown attributes: ?
// Original attribute string: TB,?,N

@property(nonatomic) _Bool contentIsSelected;
// Preceding property had unknown attributes: ?
// Original attribute string: TB,?,N

@property(retain, nonatomic) NSNumber *contentPercentage;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"NSNumber",?,&,N

@property(readonly, nonatomic) NSString *contentText1;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"NSString",?,R,N

@property(readonly, nonatomic) NSString *contentText2;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"NSString",?,R,N

@property(readonly, nonatomic) NSString *contentText3;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"NSString",?,R,N

@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

