//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSDate, NSString, TVSObserverSet, TVSSNowPlayingMediaItemMetadata, UIImage;
@protocol MPArtworkCacheReference;

@interface TVSSNowPlayingMediaItem : NSObject
{
    TVSObserverSet *_observers;	// 8 = 0x8
    id <MPArtworkCacheReference> _artworkCacheReference;	// 16 = 0x10
    NSString *_artworkCacheIdentifier;	// 24 = 0x18
    TVSSNowPlayingMediaItemMetadata *_metadata;	// 32 = 0x20
}

- (void).cxx_destruct;	// IMP=0x002000000013d410
@property(readonly, copy, nonatomic) TVSSNowPlayingMediaItemMetadata *metadata; // @synthesize metadata=_metadata;
@property(readonly, copy) NSString *debugDescription;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"NSString",?,R,C

@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
- (_Bool)isEqual:(id)arg1;	// IMP=0x001000000013d120
- (id)descriptionBuilderWithMultilinePrefix:(id)arg1;	// IMP=0x001000000013d040
- (id)descriptionWithMultilinePrefix:(id)arg1;	// IMP=0x001000000013cfa0
- (id)succinctDescriptionBuilder;	// IMP=0x001000000013ce90
- (id)succinctDescription;	// IMP=0x001000000013ce20
- (void)_updateWithMetadata:(id)arg1;	// IMP=0x001000000013c9c0
- (void)removeObserver:(id)arg1;	// IMP=0x001000000013c740
- (void)addObserver:(id)arg1;	// IMP=0x001000000013c4c0
- (void)requestArtworkWithFittingSize:(struct CGSize)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x001000000013be60
@property(readonly, nonatomic, getter=isPodcast) _Bool podcast;
@property(readonly, nonatomic, getter=isLiveContent) _Bool liveContent;
@property(readonly, nonatomic) double duration;
@property(readonly, copy, nonatomic) NSDate *elapsedTimeDate;
@property(readonly, nonatomic) double elapsedTime;
@property(readonly, nonatomic) id artworkToken;
@property(readonly, copy, nonatomic) NSString *artistTitle;
@property(readonly, copy, nonatomic) NSString *albumTitle;
@property(readonly, copy, nonatomic) NSString *title;
@property(readonly, copy, nonatomic) NSString *identifier;
- (id)_initWithMetadata:(id)arg1 artworkCacheIdentifier:(id)arg2 artworkCacheReference:(id)arg3;	// IMP=0x001000000013bb20
@property(retain, nonatomic) UIImage *platterArtworkImage;

// Remaining properties
@property(readonly) Class superclass;

@end

