//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <TVSystemPanelUI/TVSPRenderer.h>

@class UIActivityIndicatorView;

@interface TVSSGameControllerRenderer : TVSPRenderer
{
    UIActivityIndicatorView *_activityIndicatorView;	// 8 = 0x8
}

+ (id)rendererWithGameController:(id)arg1;	// IMP=0x0040000000098440
- (void).cxx_destruct;	// IMP=0x002000000009aa20
- (id)_detailTextCompositingFilterForInterfaceStyle:(long long)arg1 state:(unsigned long long)arg2;	// IMP=0x001000000009a950
- (id)_detailTextColorForInterfaceStyle:(long long)arg1 state:(unsigned long long)arg2;	// IMP=0x001000000009a8b0
- (id)_gameController;	// IMP=0x001000000009a770
- (id)layoutConstraintsWithSubviews:(id)arg1 contentView:(id)arg2;	// IMP=0x0010000000099560
- (id)subviewIdentifiersWantingAutolayout;	// IMP=0x00100000000993d0
- (id)overrideStylingForIdentifier:(id)arg1;	// IMP=0x0010000000099050
- (id)stylingForState:(unsigned long long)arg1 identifier:(id)arg2;	// IMP=0x0010000000098c40
- (void)applyStylingsWithAnimator:(id)arg1;	// IMP=0x0010000000098b10
- (void)applyContent:(id)arg1 animator:(id)arg2;	// IMP=0x00100000000989f0
- (void)configureContentView:(id)arg1;	// IMP=0x0010000000098690
- (id)initWithIdentifier:(id)arg1 format:(long long)arg2 content:(id)arg3 overrideStylings:(id)arg4;	// IMP=0x0010000000098500

@end

