//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class BSCompoundAssertion, NSString, TVSObserverSet;
@protocol OS_dispatch_source;

@interface TVSSPrivacyViewPixelShifter : NSObject
{
    _Bool _timerRunning;	// 8 = 0x8
    NSString *_identifier;	// 16 = 0x10
    TVSObserverSet *_observerSet;	// 24 = 0x18
    BSCompoundAssertion *_shifterActiveAssertion;	// 32 = 0x20
    unsigned long long _currentStep;	// 40 = 0x28
    double _timerInterval;	// 48 = 0x30
    NSObject<OS_dispatch_source> *_timer;	// 56 = 0x38
    struct CGPoint _offset;	// 64 = 0x40
}

+ (id)_prefKeyForIdentifier:(id)arg1;	// IMP=0x0020000000053980
+ (struct CGPoint)offsetForStep:(unsigned long long)arg1;	// IMP=0x0010000000052d00
- (void).cxx_destruct;	// IMP=0x0020000000053b20
@property(readonly, nonatomic) _Bool timerRunning; // @synthesize timerRunning=_timerRunning;
@property(readonly, nonatomic) NSObject<OS_dispatch_source> *timer; // @synthesize timer=_timer;
@property(readonly, nonatomic) double timerInterval; // @synthesize timerInterval=_timerInterval;
@property(readonly, nonatomic) unsigned long long currentStep; // @synthesize currentStep=_currentStep;
@property(readonly, nonatomic) BSCompoundAssertion *shifterActiveAssertion; // @synthesize shifterActiveAssertion=_shifterActiveAssertion;
@property(readonly, nonatomic) TVSObserverSet *observerSet; // @synthesize observerSet=_observerSet;
@property(readonly, nonatomic) struct CGPoint offset; // @synthesize offset=_offset;
@property(readonly, nonatomic) NSString *identifier; // @synthesize identifier=_identifier;
- (void)_updateOffset;	// IMP=0x0010000000053650
- (void)_updateState;	// IMP=0x00100000000532d0
- (void)_timerFired;	// IMP=0x00100000000531e0
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;	// IMP=0x0010000000053050
- (void)displayState:(id)arg1 didChangeWithConnection:(long long)arg2;	// IMP=0x0010000000052ca0
- (id)acquireAssertionWithReason:(id)arg1;	// IMP=0x0010000000052c20
- (void)removeObserver:(id)arg1;	// IMP=0x00100000000529a0
- (void)addObserver:(id)arg1;	// IMP=0x0010000000052720
- (void)dealloc;	// IMP=0x0010000000052630
- (id)initWithIdentifier:(id)arg1;	// IMP=0x0010000000051bb0

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"NSString",?,R,C

@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

