//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSString, NSXPCListener;

@interface ConnectionReceiver : NSObject
{
    NSXPCListener *_connectionListener;	// 8 = 0x8
}

+ (id)sharedReceiver;	// IMP=0x002000000000a896
- (void).cxx_destruct;	// IMP=0x002000000000bdae
@property(retain, nonatomic) NSXPCListener *connectionListener; // @synthesize connectionListener=_connectionListener;
- (void)didReceiveStorePushNotificationWithPayload:(id)arg1;	// IMP=0x001000000000bc2b
- (void)restartAPNSConnection;	// IMP=0x001000000000bbe7
- (void)checkDownloadQueueWithContentType:(long long)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x001000000000b8ab
- (void)resetAccountWithType:(long long)arg1;	// IMP=0x001000000000b44c
- (void)addRequestWithURL:(id)arg1 account:(id)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x001000000000afe2
- (_Bool)listener:(id)arg1 shouldAcceptNewConnection:(id)arg2;	// IMP=0x001000000000aac3
- (void)start;	// IMP=0x001000000000a8eb

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"NSString",?,R,C

@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

