//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface GEOBackgroundDirectionsRequestConfig
{
}

- (_Bool)usesBackgroundURL;	// IMP=0x0040000000036821
- (unsigned long long)urlType;	// IMP=0x0010000000036816
- (id)initWithRequest:(id)arg1 requestPriority:(id)arg2;	// IMP=0x00100000000367e7

@end

