//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <GeoServices/GEOServer.h>

@class GEOETAServiceRequester;

@interface GEOETAServer : GEOServer
{
    GEOETAServiceRequester *_serviceRequester;	// 8 = 0x8
}

+ (id)identifier;	// IMP=0x001000000001264b
- (void).cxx_destruct;	// IMP=0x002000000004482f
- (void)cancelETARequestWithRequest:(id)arg1;	// IMP=0x001000000004479b
- (void)startETARequestWithRequest:(id)arg1;	// IMP=0x001000000004433e
- (void)cancelSimpleETARequestWithRequest:(id)arg1;	// IMP=0x001000000004420c
- (void)startSimpleETARequestWithRequest:(id)arg1;	// IMP=0x0010000000043f51
- (id)serviceRequester;	// IMP=0x0010000000043f10
- (_Bool)handleIncomingMessage:(id)arg1 withObject:(id)arg2 fromPeer:(id)arg3 signpostId:(unsigned long long)arg4;	// IMP=0x0010000000012658

@end

