//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <GeoServices/GEOServer.h>

@interface GEOUtilityServer : GEOServer
{
}

+ (id)identifier;	// IMP=0x0020000000015c9d
- (void)currentServicesStateWithMessage:(id)arg1;	// IMP=0x002000000001e98b
- (void)getGeoServicesCacheDirectoryWithMessage:(id)arg1;	// IMP=0x001000000001e8b0
- (void)getHomeDirectoryWithMessage:(id)arg1;	// IMP=0x001000000001e7d5
- (void)heartbeatWithMessage:(id)arg1;	// IMP=0x001000000001e731
- (_Bool)handleIncomingMessage:(id)arg1 withObject:(id)arg2 fromPeer:(id)arg3 signpostId:(unsigned long long)arg4;	// IMP=0x0010000000015caa

@end

