//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class SUCoreLog;
@protocol OS_dispatch_queue;

__attribute__((visibility("hidden")))
@interface MABAACertManager : NSObject
{
    int _certType;	// 8 = 0x8
    SUCoreLog *_logger;	// 16 = 0x10
    NSObject<OS_dispatch_queue> *_certManagerQueue;	// 24 = 0x18
    NSObject<OS_dispatch_queue> *_deviceIdentityQueue;	// 32 = 0x20
}

+ (id)certificateParameters;	// IMP=0x006000000028ade9
+ (id)certificateSubject;	// IMP=0x006000000028abfb
+ (id)keyParameters;	// IMP=0x006000000028ab66
+ (_Bool)isSupported;	// IMP=0x00600000002899ef
- (void).cxx_destruct;	// IMP=0x000000000028b14b
@property(readonly, retain, nonatomic) NSObject<OS_dispatch_queue> *deviceIdentityQueue; // @synthesize deviceIdentityQueue=_deviceIdentityQueue;
@property(readonly, retain, nonatomic) NSObject<OS_dispatch_queue> *certManagerQueue; // @synthesize certManagerQueue=_certManagerQueue;
@property(readonly, retain, nonatomic) SUCoreLog *logger; // @synthesize logger=_logger;
@property int certType; // @synthesize certType=_certType;
- (id)issueSelfSignedCertInternal:(struct __SecKey **)arg1;	// IMP=0x000000000028ae62
- (id)issueAndCopyCertsInternal:(struct __SecKey **)arg1;	// IMP=0x000000000028aad0
- (id)copyPreviouslyCreatedCertsIfPresent:(struct __SecKey **)arg1;	// IMP=0x000000000028aa3a
- (id)copyDeviceIdentityOptionsForCertAndRequestType:(int)arg1 skipNetworkRequest:(_Bool)arg2 invalidateExistingCert:(_Bool)arg3;	// IMP=0x000000000028a97b
- (_Bool)shouldInvalidateExistingCertificateIfAny;	// IMP=0x000000000028a7f7
- (id)copyCurrentBootManifestHash;	// IMP=0x000000000028a587
- (id)copyBase64EncodedCertificateChain:(_Bool)arg1 referenceKey:(struct __SecKey **)arg2;	// IMP=0x0000000000289ec0
- (id)issueAndCopySelfSignedCert:(struct __SecKey **)arg1;	// IMP=0x0000000000289c7f
- (id)issueAndCopyCerts:(struct __SecKey **)arg1;	// IMP=0x0000000000289a86
- (id)initWithCertType:(int)arg1;	// IMP=0x00000000002898d1

@end

