//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSDictionary, NSMutableDictionary;
@protocol OS_dispatch_queue;

__attribute__((visibility("hidden")))
@interface MADAnalyticsEventSubmitter : NSObject
{
    NSMutableDictionary *_events;	// 8 = 0x8
    NSObject<OS_dispatch_queue> *_stateQueue;	// 16 = 0x10
}

- (void).cxx_destruct;	// IMP=0x000000000000f5c9
- (void)_queue_registerSendEvent:(id)arg1;	// IMP=0x000000000000f446
- (void)_queue_submitAllEvents;	// IMP=0x000000000000f1e6
- (void)_queue_submitEventsWithName:(id)arg1;	// IMP=0x000000000000ef3a
- (void)_queue_submitEvent:(id)arg1;	// IMP=0x000000000000ede3
- (void)_queue_removeAllEvents;	// IMP=0x000000000000ed9e
- (void)_queue_removeEventsWithName:(id)arg1;	// IMP=0x000000000000eaf8
- (void)_queue_removeEvent:(id)arg1;	// IMP=0x000000000000e98a
- (void)_queue_setEvent:(id)arg1;	// IMP=0x000000000000e8a0
@property(readonly, retain, nonatomic) NSDictionary *events;
- (void)submitAllEvents;	// IMP=0x000000000000e704
- (void)submitEventsWithName:(id)arg1;	// IMP=0x000000000000e623
- (void)submitEvent:(id)arg1;	// IMP=0x000000000000e50c
- (void)removeAllEvents;	// IMP=0x000000000000e4a0
- (void)removeEventsWithName:(id)arg1;	// IMP=0x000000000000e3bf
- (void)removeEvent:(id)arg1;	// IMP=0x000000000000e2de
- (void)setEvent:(id)arg1;	// IMP=0x000000000000e1fd
- (id)init;	// IMP=0x000000000000e164

@end

