//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSDictionary;

__attribute__((visibility("hidden")))
@interface MANAutoAssetSetPolicy : NSObject
{
    _Bool _userInitiated;	// 8 = 0x8
    _Bool _lockInhibitsEmergencyRemoval;	// 9 = 0x9
    _Bool _supportingShortTermLocks;	// 10 = 0xa
    _Bool _allowCheckDownloadOnBattery;	// 11 = 0xb
    _Bool _allowCheckDownloadWhenBatteryLow;	// 12 = 0xc
    _Bool _allowCheckDownloadWhenCPUHigh;	// 13 = 0xd
    _Bool _allowCheckDownloadOverExpensive;	// 14 = 0xe
    _Bool _allowCheckDownloadOverCellular;	// 15 = 0xf
    _Bool _blockCheckDownload;	// 16 = 0x10
    NSDictionary *_additionalPolicyControl;	// 24 = 0x18
}

+ (_Bool)supportsSecureCoding;	// IMP=0x00100000000b213c
- (void).cxx_destruct;	// IMP=0x00000000000b2807
@property(retain, nonatomic) NSDictionary *additionalPolicyControl; // @synthesize additionalPolicyControl=_additionalPolicyControl;
@property(nonatomic) _Bool blockCheckDownload; // @synthesize blockCheckDownload=_blockCheckDownload;
@property(nonatomic) _Bool allowCheckDownloadOverCellular; // @synthesize allowCheckDownloadOverCellular=_allowCheckDownloadOverCellular;
@property(nonatomic) _Bool allowCheckDownloadOverExpensive; // @synthesize allowCheckDownloadOverExpensive=_allowCheckDownloadOverExpensive;
@property(nonatomic) _Bool allowCheckDownloadWhenCPUHigh; // @synthesize allowCheckDownloadWhenCPUHigh=_allowCheckDownloadWhenCPUHigh;
@property(nonatomic) _Bool allowCheckDownloadWhenBatteryLow; // @synthesize allowCheckDownloadWhenBatteryLow=_allowCheckDownloadWhenBatteryLow;
@property(nonatomic) _Bool allowCheckDownloadOnBattery; // @synthesize allowCheckDownloadOnBattery=_allowCheckDownloadOnBattery;
@property(nonatomic) _Bool supportingShortTermLocks; // @synthesize supportingShortTermLocks=_supportingShortTermLocks;
@property(nonatomic) _Bool lockInhibitsEmergencyRemoval; // @synthesize lockInhibitsEmergencyRemoval=_lockInhibitsEmergencyRemoval;
@property(nonatomic) _Bool userInitiated; // @synthesize userInitiated=_userInitiated;
- (id)summary;	// IMP=0x00000000000b23cc
- (id)description;	// IMP=0x00000000000b22c4
- (id)copy;	// IMP=0x00000000000b2144
- (void)encodeWithCoder:(id)arg1;	// IMP=0x00000000000b1fa5
- (id)initWithCoder:(id)arg1;	// IMP=0x00000000000b1d44
- (id)init;	// IMP=0x00000000000b1cf0

@end

