//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

__attribute__((visibility("hidden")))
@interface MASAutoAssetSetInfoFound : NSObject
{
}

+ (id)newShimmedFromFrameworkMessage:(id)arg1 forKey:(id)arg2;	// IMP=0x00800000000c2a0f
+ (id)newShimmedFromFramework:(id)arg1;	// IMP=0x00800000000c28b4
+ (id)newShimmedToFramework:(id)arg1;	// IMP=0x00800000000c2781
+ (id)newServerMessageClasses:(id)arg1;	// IMP=0x00800000000c25ba

@end

