//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <ProtocolBuffer/PBCodable.h>

@class NSString;

@interface TASKResponse : PBCodable
{
    NSString *_errorMessage;	// 8 = 0x8
    int _status;	// 16 = 0x10
    unsigned int _taskId;	// 20 = 0x14
}

- (void).cxx_destruct;	// IMP=0x00200000000542b7
@property(retain, nonatomic) NSString *errorMessage; // @synthesize errorMessage=_errorMessage;
@property(nonatomic) unsigned int taskId; // @synthesize taskId=_taskId;
@property(nonatomic) int status; // @synthesize status=_status;
- (void)mergeFrom:(id)arg1;	// IMP=0x0010000000054214
- (unsigned long long)hash;	// IMP=0x00100000000541c7
- (_Bool)isEqual:(id)arg1;	// IMP=0x0010000000054117
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x0000000000054081
- (void)copyTo:(id)arg1;	// IMP=0x001000000005403d
- (void)writeTo:(id)arg1;	// IMP=0x0010000000053fcd
- (_Bool)readFrom:(id)arg1;	// IMP=0x0010000000053fc0
- (id)dictionaryRepresentation;	// IMP=0x0010000000053c47
- (id)description;	// IMP=0x0010000000053b98
@property(readonly, nonatomic) _Bool hasErrorMessage;
- (int)StringAsStatus:(id)arg1;	// IMP=0x0010000000053ab1
- (id)statusAsString:(int)arg1;	// IMP=0x0010000000053a68

@end

