//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface _TtC9storekitdP33_E619F6C7E2B7960B25E94D759ACE384B19PurchaseIntentStore
{
}

+ (_Bool)createOrMigrateStoreUsingSchema:(id)arg1;	// IMP=0x00200000000d6580
+ (id)storeDescriptor;	// IMP=0x00100000000d6030
- (void).cxx_destruct;	// IMP=0x00400000000d6663
- (id)init;	// IMP=0x00100000000d6631
- (id)initWithDatabase:(id)arg1;	// IMP=0x00100000000d660e

@end

