//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface SQLiteComparisonPredicate
{
    long long _comparisonType;	// 24 = 0x18
    id _value;	// 32 = 0x20
}

+ (id)predicateWithProperty:(id)arg1 value:(id)arg2 comparisonType:(long long)arg3;	// IMP=0x00200000000656f7
+ (id)predicateWithProperty:(id)arg1 equalToValue:(id)arg2;	// IMP=0x00100000000656df
+ (id)predicateWithProperty:(id)arg1 equalToLongLong:(long long)arg2;	// IMP=0x0010000000065658
- (void).cxx_destruct;	// IMP=0x0020000000065c51
@property(readonly, nonatomic) id value; // @synthesize value=_value;
@property(readonly, nonatomic) long long comparisonType; // @synthesize comparisonType=_comparisonType;
- (id)_comparisonTypeString;	// IMP=0x0010000000065c02
- (id)SQLForEntityClass:(Class)arg1;	// IMP=0x0010000000065b6f
- (_Bool)isEqual:(id)arg1;	// IMP=0x0010000000065a35
- (unsigned long long)hash;	// IMP=0x00100000000659a9
- (id)description;	// IMP=0x00100000000658e8
- (void)applyBinding:(id)arg1 atIndex:(inout int *)arg2;	// IMP=0x00100000000657f5
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x00100000000657ea

@end

