//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSArray, NSOperationQueue, NSString;

@interface TaskQueue : NSObject
{
    NSOperationQueue *_operationQueue;	// 8 = 0x8
}

+ (id)networkQueue;	// IMP=0x004000000000ed99
- (void).cxx_destruct;	// IMP=0x002000000000efb0
- (void)waitUntilAllTasksAreFinished;	// IMP=0x001000000000ef9a
- (void)cancelAllTasks;	// IMP=0x001000000000ef84
- (void)addTaskWithBlock:(CDUnknownBlockType)arg1;	// IMP=0x001000000000ef6e
- (void)addTasks:(id)arg1 waitUntilFinished:(_Bool)arg2;	// IMP=0x001000000000ef58
- (void)addTask:(id)arg1;	// IMP=0x001000000000ef42
@property long long qualityOfService;
@property(readonly, copy) NSArray *tasks;
@property(copy) NSString *name;
- (void)setUnderlyingQueue:(id)arg1;	// IMP=0x001000000000eebe
@property long long maxConcurrentOperationCount;
- (id)init;	// IMP=0x001000000000ee09

@end

