//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class AKCustodianContext;

@interface AKCustodianRequestProvider
{
    _Bool _authenticatedRequest;	// 8 = 0x8
    _Bool _signWithIdentityToken;	// 9 = 0x9
    AKCustodianContext *_custodianContext;	// 16 = 0x10
}

- (void).cxx_destruct;	// IMP=0x0020000000035134
@property(retain, nonatomic) AKCustodianContext *custodianContext; // @synthesize custodianContext=_custodianContext;
@property(nonatomic) _Bool signWithIdentityToken; // @synthesize signWithIdentityToken=_signWithIdentityToken;
@property(nonatomic) _Bool authenticatedRequest; // @synthesize authenticatedRequest=_authenticatedRequest;
- (_Bool)validateResponseData:(id)arg1 error:(id *)arg2;	// IMP=0x0010000000034e9e
- (id)_bodyForTrustedContactsDataSync;	// IMP=0x0010000000034aca
- (id)_bodyForEmbargoEndFeedback;	// IMP=0x0010000000034777
- (id)_bodyForCustodianUpdateRecoveryKeyRequest;	// IMP=0x0010000000034532
- (id)_bodyForFinalizeCustodianRequest;	// IMP=0x0010000000034322
- (id)_bodyForAddAndRevokeCustodianRequest;	// IMP=0x00100000000341d3
- (id)_bodyForRecoveryCircle;	// IMP=0x00100000000338f5
- (id)authKitBody;	// IMP=0x00100000000335e9
- (_Bool)signRequest:(id)arg1 error:(id *)arg2;	// IMP=0x00100000000331c5
- (unsigned long long)requestBodyType;	// IMP=0x00100000000331ba
- (unsigned long long)expectedResponseType;	// IMP=0x00100000000331af
- (id)initWithContext:(id)arg1 urlBagKey:(id)arg2;	// IMP=0x0010000000033131

@end

