//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class AKAppleIDAuthenticationContext, NSString;

@interface AKSRPAuthenticationContextHelper
{
    NSString *_passwordResetBackupToken;	// 8 = 0x8
    _Bool __masterKeyAsSecondFactor;	// 16 = 0x10
    AKAppleIDAuthenticationContext *_authContext;	// 24 = 0x18
}

- (void).cxx_destruct;	// IMP=0x00200000000268d6
@property(nonatomic, setter=_setMasterKeyAsSecondFactor:) _Bool _masterKeyAsSecondFactor; // @synthesize _masterKeyAsSecondFactor=__masterKeyAsSecondFactor;
@property(retain, nonatomic) AKAppleIDAuthenticationContext *authContext; // @synthesize authContext=_authContext;
- (id)_identityAuthorizationPayload;	// IMP=0x00100000000266f6
- (id)_passwordResetBackupToken;	// IMP=0x0010000000026622
- (_Bool)canPresentRemoteUI;	// IMP=0x00100000000265a2
- (void)clientProvidedDataHelper:(id)arg1;	// IMP=0x0010000000025cac
- (void)_updateHeadersWithCompanionAnisetteData:(id)arg1 clientProvidedData:(id)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x00100000000257f2
- (void)_updateHeadersWithProxiedDeviceAnisetteData:(id)arg1 clientProvidedData:(id)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x00100000000253ff
- (void)_authenticationParameters:(CDUnknownBlockType)arg1;	// IMP=0x0010000000023d06
- (void)authenticationParametersWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x00100000000237b1
- (id)initWithContext:(id)arg1;	// IMP=0x0010000000023740

@end

