//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <ProtocolBuffer/PBCodable.h>

@class NSData;

@interface _ADPBDeviceExecuteOnRemoteResponse : PBCodable
{
    NSData *_content;	// 8 = 0x8
}

- (void).cxx_destruct;	// IMP=0x00200000000e29a0
@property(retain, nonatomic) NSData *content; // @synthesize content=_content;
- (void)mergeFrom:(id)arg1;	// IMP=0x00100000000e2957
- (unsigned long long)hash;	// IMP=0x00100000000e293a
- (_Bool)isEqual:(id)arg1;	// IMP=0x00100000000e28aa
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x00100000000e2832
- (void)copyTo:(id)arg1;	// IMP=0x00100000000e2808
- (void)writeTo:(id)arg1;	// IMP=0x00100000000e27e4
- (_Bool)readFrom:(id)arg1;	// IMP=0x00100000000e269b
- (id)dictionaryRepresentation;	// IMP=0x00100000000e263f
- (id)description;	// IMP=0x00100000000e2590
@property(readonly, nonatomic) _Bool hasContent;

@end

