//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSString;

@interface ADAudioSessionCoordinationMessageEndAudioSessionResponse : NSObject
{
}

+ (_Bool)supportsSecureCoding;	// IMP=0x002000000025059e
+ (id)newWithBuilder:(CDUnknownBlockType)arg1;	// IMP=0x0010000000250551
- (id)buildDictionaryRepresentation;	// IMP=0x00200000002504be
- (id)initWithDictionaryRepresentation:(id)arg1;	// IMP=0x0010000000250483
- (void)encodeWithCoder:(id)arg1;	// IMP=0x001000000025047d
- (id)initWithCoder:(id)arg1;	// IMP=0x001000000025046b
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x0010000000250460
- (_Bool)isEqual:(id)arg1;	// IMP=0x0010000000250431
@property(readonly) unsigned long long hash;
- (id)_descriptionWithIndent:(unsigned long long)arg1;	// IMP=0x00100000002503c4
@property(readonly, copy) NSString *description;
- (id)init;	// IMP=0x001000000025039c
- (id)initWithBuilder:(CDUnknownBlockType)arg1;	// IMP=0x00100000002502f6
- (id)mutatedCopyWithMutator:(CDUnknownBlockType)arg1;	// IMP=0x00100000002505a6

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"NSString",?,R,C

@property(readonly) Class superclass;

@end

