//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <SAObjects/SASFinishSpeech.h>

@interface SASFinishSpeech (AFAdditions)
- (void)af_logDiagnostics;	// IMP=0x0020000000245a9b
- (void)ad_setCSEndpointerMetrics:(id)arg1;	// IMP=0x0010000000374de9
- (void)ad_setAFEndpointMode:(long long)arg1;	// IMP=0x0010000000374d98
@end

