//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <SAObjects/SASStartSpeech.h>

@interface SASStartSpeech (AFAdditions)
- (void)af_logDiagnostics;	// IMP=0x0020000000245a57
- (id)ad_deferredMetricsContext;	// IMP=0x0010000000374346
- (void)ad_setCSSiriRecordingInfo:(id)arg1;	// IMP=0x00100000003740a7
- (void)ad_setAFSpeechRequestOptions:(id)arg1;	// IMP=0x0010000000373f77
- (void)ad_setAFSpeechEvent:(long long)arg1;	// IMP=0x0010000000373f3a
- (id)ad_languageModel;	// IMP=0x0010000000373f32
@end

