//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class MISSING_TYPE;

@interface _TtC13callservicesd27CSDSuperboxProviderDelegate : NSObject
{
    MISSING_TYPE *queue;	// 8 = 0x8
    MISSING_TYPE *provider;	// 16 = 0x10
    MISSING_TYPE *incomingAudioCallNotifyToken;	// 24 = 0x18
    MISSING_TYPE *incomingVideoCallNotifyToken;	// 28 = 0x1c
}

- (void).cxx_destruct;	// IMP=0x00200000002e53d4
- (id)init;	// IMP=0x00100000002e539e
- (id)initWithCallSource:(id)arg1;	// IMP=0x00100000002e4c70
- (void)providerDidReset:(id)arg1;	// IMP=0x00100000002e5fe7
- (void)provider:(id)arg1 performSetMutedCallAction:(id)arg2;	// IMP=0x00100000002e62e6
- (void)provider:(id)arg1 performEndCallAction:(id)arg2;	// IMP=0x00100000002e5f89
- (void)provider:(id)arg1 performAnswerCallAction:(id)arg2;	// IMP=0x00100000002e5f0e
- (void)provider:(id)arg1 performStartCallAction:(id)arg2;	// IMP=0x00100000002e5a9f

@end

