//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class MISSING_TYPE;
@protocol CSDAVCMomentsDelegate;

@interface _TtC13callservicesd13CSDAVCMoments : NSObject
{
    MISSING_TYPE *moments;	// 8 = 0x8
    MISSING_TYPE *delegate;	// 16 = 0x10
}

- (void).cxx_destruct;	// IMP=0x002000000030fdcd
- (id)init;	// IMP=0x001000000030fd97
- (id)newRequestWithMediaType:(unsigned char)arg1 mode:(unsigned char)arg2 requesteeID:(id)arg3;	// IMP=0x001000000030fcfd
@property(nonatomic, readonly) int pendingRequestCount;
@property(nonatomic, readonly) int activeRequestCount;
@property(nonatomic, readonly) unsigned int capabilities;
@property(nonatomic, readonly) long long streamToken;
- (id)initWithStreamToken:(long long)arg1 requesterID:(id)arg2 delegate:(id)arg3 dispatchQueue:(id)arg4;	// IMP=0x001000000030fafc
@property(nonatomic) __weak id <CSDAVCMomentsDelegate> delegate; // @synthesize delegate;
- (void)momentsServerDidDisconnect:(id)arg1;	// IMP=0x0010000000310332
- (void)moments:(id)arg1 didEndProcessingRequest:(id)arg2 stillImageURL:(id)arg3 movieURL:(id)arg4 error:(id)arg5;	// IMP=0x0010000000310197
- (void)moments:(id)arg1 didEndProcessingRequest:(id)arg2 url:(id)arg3 error:(id)arg4;	// IMP=0x001000000030ffc6
- (void)moments:(id)arg1 didStartProcessingRequest:(id)arg2 error:(id)arg3;	// IMP=0x001000000030ff31
- (void)moments:(id)arg1 didFinishRequest:(id)arg2 error:(id)arg3;	// IMP=0x001000000030feaa
- (void)moments:(id)arg1 capabilitiesDidChange:(unsigned int)arg2;	// IMP=0x001000000030fe55

@end

