//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class CSDConversationManager, CXProvider, FTDeviceSupport, FTNetworkSupport, NSMutableDictionary, NSMutableSet, NSString;
@protocol CSDConversationInvitationResolving, CSDConversationServerBag, CSDFaceTimeProviderDelegateManagerDelegate, OS_dispatch_queue, TUFeatureFlags;

@interface CSDAbstractFaceTimeConversationProviderDelegate : NSObject
{
    _Bool _audioSessionActive;	// 8 = 0x8
    NSMutableSet *_conversationUUIDsWaitingToJoin;	// 16 = 0x10
    NSMutableDictionary *_callUUIDsByConversationUUID;	// 24 = 0x18
    NSMutableDictionary *_conversationUUIDsByCallUUID;	// 32 = 0x20
    NSMutableSet *_callUUIDsUpgradedForAVMode;	// 40 = 0x28
    FTNetworkSupport *_networkSupport;	// 48 = 0x30
    id <TUFeatureFlags> _featureFlags;	// 56 = 0x38
    NSObject<OS_dispatch_queue> *_queue;	// 64 = 0x40
    CXProvider *_provider;	// 72 = 0x48
    CSDConversationManager *_conversationManager;	// 80 = 0x50
    id <CSDFaceTimeProviderDelegateManagerDelegate> _faceTimeDemuxerDelegate;	// 88 = 0x58
    id <CSDConversationServerBag> _serverBag;	// 96 = 0x60
    FTDeviceSupport *_deviceSupport;	// 104 = 0x68
    id <CSDConversationInvitationResolving> _invitationResolver;	// 112 = 0x70
    NSMutableSet *_conversationUUIDsAwaitingActiveAudioSession;	// 120 = 0x78
    CDUnknownBlockType _providerDidBegin;	// 128 = 0x80
}

- (void).cxx_destruct;	// IMP=0x002000000020d5f9
@property(copy, nonatomic) CDUnknownBlockType providerDidBegin; // @synthesize providerDidBegin=_providerDidBegin;
@property(nonatomic, getter=isAudioSessionActive) _Bool audioSessionActive; // @synthesize audioSessionActive=_audioSessionActive;
@property(readonly, nonatomic) NSMutableSet *conversationUUIDsAwaitingActiveAudioSession; // @synthesize conversationUUIDsAwaitingActiveAudioSession=_conversationUUIDsAwaitingActiveAudioSession;
@property(retain, nonatomic) id <CSDConversationInvitationResolving> invitationResolver; // @synthesize invitationResolver=_invitationResolver;
@property(retain, nonatomic) FTDeviceSupport *deviceSupport; // @synthesize deviceSupport=_deviceSupport;
@property(readonly, nonatomic) id <CSDConversationServerBag> serverBag; // @synthesize serverBag=_serverBag;
@property(nonatomic) __weak id <CSDFaceTimeProviderDelegateManagerDelegate> faceTimeDemuxerDelegate; // @synthesize faceTimeDemuxerDelegate=_faceTimeDemuxerDelegate;
@property(readonly, nonatomic) CSDConversationManager *conversationManager; // @synthesize conversationManager=_conversationManager;
@property(retain, nonatomic) CXProvider *provider; // @synthesize provider=_provider;
@property(readonly, nonatomic) NSObject<OS_dispatch_queue> *queue; // @synthesize queue=_queue;
@property(readonly, nonatomic) id <TUFeatureFlags> featureFlags; // @synthesize featureFlags=_featureFlags;
@property(readonly, nonatomic) FTNetworkSupport *networkSupport; // @synthesize networkSupport=_networkSupport;
@property(readonly, nonatomic) NSMutableSet *callUUIDsUpgradedForAVMode; // @synthesize callUUIDsUpgradedForAVMode=_callUUIDsUpgradedForAVMode;
- (void)provider:(id)arg1 performSetMutedCallAction:(id)arg2;	// IMP=0x001000000020d1fe
- (void)provider:(id)arg1 performJoinCallAction:(id)arg2;	// IMP=0x001000000020d149
- (void)provider:(id)arg1 performEndCallAction:(id)arg2;	// IMP=0x001000000020cdab
- (void)provider:(id)arg1 timedOutPerformingAction:(id)arg2;	// IMP=0x001000000020cc3d
- (void)provider:(id)arg1 didDeactivateAudioSession:(id)arg2;	// IMP=0x001000000020cb9c
- (void)providerDidReset:(id)arg1;	// IMP=0x001000000020ca92
- (void)providerDidBegin:(id)arg1;	// IMP=0x001000000020c950
- (_Bool)isLocalMemberOf:(id)arg1 associatedTo:(id)arg2;	// IMP=0x001000000020c862
- (_Bool)isConversationJoiningOrJoined:(id)arg1;	// IMP=0x001000000020c841
- (_Bool)shouldAutomaticallyLeaveConversation:(id)arg1;	// IMP=0x001000000020c4e5
- (void)conversationManager:(id)arg1 conversation:(id)arg2 removedActiveParticipant:(id)arg3 withReason:(unsigned long long)arg4;	// IMP=0x001000000020bd10
- (void)proceedToJoinForConversation:(id)arg1 action:(id)arg2;	// IMP=0x001000000020ac3c
- (void)leaveConversation:(id)arg1 withCallUUID:(id)arg2 reason:(long long)arg3;	// IMP=0x001000000020a883
- (void)leaveConversationForCallUUID:(id)arg1 endedReason:(long long)arg2;	// IMP=0x001000000020a3b7
- (void)cleanUpConversationIfNecessaryForConversationUUID:(id)arg1 failureContext:(id)arg2;	// IMP=0x0010000000209de7
- (void)endCallWithUUIDAsLocalHangup:(id)arg1;	// IMP=0x0010000000209d21
- (void)endCallWithUUIDAsDeclinedElsewhere:(id)arg1;	// IMP=0x0010000000209c5d
- (void)endCallWithUUIDAsAnsweredElsewhere:(id)arg1;	// IMP=0x0010000000209b99
- (id)upgradeSessionUUIDForCallWithUUID:(id)arg1;	// IMP=0x0010000000209b91
- (_Bool)hasCallStartedConnectingWithUUID:(id)arg1;	// IMP=0x0010000000209a6b
- (id)pendingConversationUUIDForCallWithUUID:(id)arg1;	// IMP=0x00100000002097c4
- (_Bool)isManagingPendingConversationForCallWithUUID:(id)arg1;	// IMP=0x0010000000209544
- (_Bool)isManagingCallWithUUID:(id)arg1;	// IMP=0x001000000020940c
- (void)displayGreenTeaAlertForAppleTV;	// IMP=0x0010000000209406
- (void)cleanupConversationWithCallUUID:(id)arg1;	// IMP=0x00100000002093f4
- (void)fullfillPendingJoinActionsForCallUUIDIfNecessary:(id)arg1;	// IMP=0x0010000000209052
- (void)reportNewIncomingCallForConversation:(id)arg1 fromHandle:(id)arg2 callUUID:(id)arg3 isReRing:(_Bool)arg4;	// IMP=0x0010000000207da4
- (void)reportNewIncomingCallForConversation:(id)arg1 fromHandle:(id)arg2 isReRing:(_Bool)arg3;	// IMP=0x0010000000207d10
- (void)conversationManager:(id)arg1 avModeChanged:(unsigned long long)arg2 toAVMode:(unsigned long long)arg3 forParticipantWithHandle:(id)arg4 forConversation:(id)arg5;	// IMP=0x0010000000207b15
- (void)conversationManager:(id)arg1 reportedNewIncomingConversation:(id)arg2 fromHandle:(id)arg3;	// IMP=0x0010000000207876
- (void)associateCallUUID:(id)arg1 withConversationUUID:(id)arg2 waitingToJoin:(_Bool)arg3;	// IMP=0x00100000002077d5
- (id)_findPendingConversationWithCallUUID:(id)arg1;	// IMP=0x001000000020736d
- (void)startAudioForConversationsIfNecessary;	// IMP=0x0010000000207065
- (void)enqueueOrStartAudioForConversationUUID:(id)arg1;	// IMP=0x0010000000206fab
- (void)enqueueConversationWaitingForAudioWithConversationUUID:(id)arg1;	// IMP=0x0010000000206f2c
- (_Bool)usesAudioSession;	// IMP=0x0010000000206f24
- (void)handleAudioInterruptionPropertiesChanged:(id)arg1;	// IMP=0x0010000000206da3
- (void)setConversationUUID:(id)arg1 forCallUUID:(id)arg2;	// IMP=0x0010000000206cec
- (id)conversationUUIDForCallUUID:(id)arg1;	// IMP=0x0010000000206b3c
@property(readonly, nonatomic) NSMutableDictionary *conversationUUIDsByCallUUID; // @synthesize conversationUUIDsByCallUUID=_conversationUUIDsByCallUUID;
- (void)updateNetworkCriticalStateIfNecessary;	// IMP=0x001000000020698c
- (void)removeActiveAudioSessionObjectForConversationWithUUID:(id)arg1;	// IMP=0x00100000002068f4
- (void)setCallUUID:(id)arg1 forConversationUUID:(id)arg2;	// IMP=0x001000000020683d
- (id)callUUIDForConversationUUID:(id)arg1;	// IMP=0x0010000000206668
@property(readonly, nonatomic) NSMutableDictionary *callUUIDsByConversationUUID; // @synthesize callUUIDsByConversationUUID=_callUUIDsByConversationUUID;
- (void)setWaitingToJoin:(_Bool)arg1 forConversationUUID:(id)arg2;	// IMP=0x0010000000206580
- (_Bool)_isWaitingToJoinForConversationUUID:(id)arg1;	// IMP=0x00100000002064e3
- (_Bool)isWaitingToJoinForConversationUUID:(id)arg1;	// IMP=0x00100000002063ae
@property(readonly, nonatomic) NSMutableSet *conversationUUIDsWaitingToJoin; // @synthesize conversationUUIDsWaitingToJoin=_conversationUUIDsWaitingToJoin;
- (void)dealloc;	// IMP=0x00100000002062f9
- (id)initWithQueue:(id)arg1 conversationManager:(id)arg2 networkSupport:(id)arg3 serverBag:(id)arg4 featureFlags:(id)arg5 invitationResolver:(id)arg6;	// IMP=0x001000000020608c
- (id)initWithConversationManager:(id)arg1 queue:(id)arg2 invitationResolver:(id)arg3;	// IMP=0x0010000000205fc9

// Remaining properties
// Error: Property attributes should begin with the type ('T') attribute, property name: debugDescription
// Property attributes: (null)

@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

