//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSArray, NSMapTable;

@interface CSDCallDataSourceMap : NSObject
{
    NSMapTable *_dataSourceToIdentifierToCalls;	// 8 = 0x8
}

- (void).cxx_destruct;	// IMP=0x002000000017f8a6
@property(retain, nonatomic) NSMapTable *dataSourceToIdentifierToCalls; // @synthesize dataSourceToIdentifierToCalls=_dataSourceToIdentifierToCalls;
- (id)callsForDataSource:(id)arg1 identifier:(id)arg2;	// IMP=0x001000000017f7a1
- (void)addCalls:(id)arg1 forIdentifier:(id)arg2;	// IMP=0x001000000017f474
@property(readonly, copy, nonatomic) NSArray *dataSources;
- (id)init;	// IMP=0x001000000017f3c7

@end

