//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class CSDSharedConversationServerBag, CXCallDirectoryManager, CXCallDirectoryNSExtensionManager, NSString, TUFeatureFlags;
@protocol CSDDeviceLockStateObserver, OS_dispatch_queue;

@interface CSDCallDirectoryManager : NSObject
{
    NSObject<OS_dispatch_queue> *_queue;	// 8 = 0x8
    id <CSDDeviceLockStateObserver> _deviceLockObserver;	// 16 = 0x10
    CXCallDirectoryManager *_manager;	// 24 = 0x18
    CXCallDirectoryNSExtensionManager *_nsExtensionManager;	// 32 = 0x20
    unsigned long long _countOfNotificationsReceived;	// 40 = 0x28
    TUFeatureFlags *_featureFlags;	// 48 = 0x30
    CSDSharedConversationServerBag *_serverBag;	// 56 = 0x38
}

+ (id)sharedInstanceWithQueue:(id)arg1;	// IMP=0x00200000000817eb
+ (id)sharedInstance;	// IMP=0x00100000000817cb
- (void).cxx_destruct;	// IMP=0x00200000000829a3
@property(readonly, nonatomic) CSDSharedConversationServerBag *serverBag; // @synthesize serverBag=_serverBag;
@property(readonly, nonatomic) TUFeatureFlags *featureFlags; // @synthesize featureFlags=_featureFlags;
@property(nonatomic) unsigned long long countOfNotificationsReceived; // @synthesize countOfNotificationsReceived=_countOfNotificationsReceived;
@property(readonly, nonatomic) CXCallDirectoryNSExtensionManager *nsExtensionManager; // @synthesize nsExtensionManager=_nsExtensionManager;
@property(retain, nonatomic) CXCallDirectoryManager *manager; // @synthesize manager=_manager;
@property(readonly, nonatomic) id <CSDDeviceLockStateObserver> deviceLockObserver; // @synthesize deviceLockObserver=_deviceLockObserver;
@property(readonly, nonatomic) NSObject<OS_dispatch_queue> *queue; // @synthesize queue=_queue;
- (void)callDirectoryNSExtensionManager:(id)arg1 extensionsChanged:(id)arg2;	// IMP=0x00100000000825eb
- (void)beginDailyMaintenanceWithActivity:(id)arg1;	// IMP=0x0010000000082075
- (id)firstEnabledLiveBlockingExtensionIdentifierForPhoneNumber:(id)arg1;	// IMP=0x0010000000081e77
- (_Bool)fetchLiveBlockingInfoForHandle:(id)arg1;	// IMP=0x0010000000081c6f
- (id)initWithQueue:(id)arg1;	// IMP=0x00100000000818cd

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"NSString",?,R,C

@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

