//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <ProtocolBuffer/PBCodable.h>

@class NSData;

@interface CSDMessagingEncryptedConversationMessage : PBCodable
{
    NSData *_conversationMessageBytes;	// 8 = 0x8
    NSData *_publicKey;	// 16 = 0x10
}

- (void).cxx_destruct;	// IMP=0x00200000000056bf
@property(retain, nonatomic) NSData *conversationMessageBytes; // @synthesize conversationMessageBytes=_conversationMessageBytes;
@property(retain, nonatomic) NSData *publicKey; // @synthesize publicKey=_publicKey;
- (void)mergeFrom:(id)arg1;	// IMP=0x0010000000005612
- (unsigned long long)hash;	// IMP=0x00100000000055c5
- (_Bool)isEqual:(id)arg1;	// IMP=0x001000000000550d
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x001000000000546f
- (void)copyTo:(id)arg1;	// IMP=0x001000000000540c
- (void)writeTo:(id)arg1;	// IMP=0x00100000000053af
- (_Bool)readFrom:(id)arg1;	// IMP=0x00100000000053a2
- (id)dictionaryRepresentation;	// IMP=0x00100000000051b5
- (id)description;	// IMP=0x0010000000005106
@property(readonly, nonatomic) _Bool hasConversationMessageBytes;
@property(readonly, nonatomic) _Bool hasPublicKey;

@end

