//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <SiriActivation/SiriActivationSource.h>

@interface SiriQuickTypeGestureSource : SiriActivationSource
{
}

- (void)activate;	// IMP=0x0040000000051f89
- (id)prewarm;	// IMP=0x0010000000051d65
- (void)configureConnection;	// IMP=0x0010000000051716
- (id)init;	// IMP=0x00100000000516ca

@end

