//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@interface SRErrorUtility : NSObject
{
}

+ (void)_logDummyAssistantUtteranceViewWithDialogIdentifier:(id)arg1;	// IMP=0x0040000000003dc4
+ (id)_localizedErrorString:(id)arg1;	// IMP=0x0010000000003d2f
+ (long long)_getUpdatedErrorCount;	// IMP=0x0010000000003c40
+ (void)resetErrorState;	// IMP=0x0010000000003bc8
+ (id)userStringForError:(id)arg1 reflectionDialogWasPlayed:(_Bool)arg2;	// IMP=0x0010000000003970

@end

