//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <UIKit/UIView.h>

@class NSArray;

@interface TVSBSLevelBarView : UIView
{
    NSArray *_boxes;	// 8 = 0x8
    unsigned long long _numLevels;	// 16 = 0x10
    unsigned long long _level;	// 24 = 0x18
}

+ (struct CGRect)_boundsForNumLevels:(unsigned long long)arg1;	// IMP=0x0040000000007200
- (void).cxx_destruct;	// IMP=0x0020000000007550
@property(nonatomic) unsigned long long level; // @synthesize level=_level;
@property(readonly, nonatomic) unsigned long long numLevels; // @synthesize numLevels=_numLevels;
- (void)_updateLevels;	// IMP=0x00100000000072a0
- (void)layoutSubviews;	// IMP=0x0010000000006f10
- (id)initWithNumLevels:(unsigned long long)arg1;	// IMP=0x0010000000006c90
- (id)initWithCoder:(id)arg1;	// IMP=0x0010000000006bd0
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x0010000000006b70

@end

