//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class MISSING_TYPE, NSMapTable, NSMutableDictionary, NSString, PBBulletinToBannerAdapter, PBSystemOverlayController, PBSystemServiceConnection;
@protocol PBSBulletinServiceDelegate, PBSBulletinServiceInteractionDelegate;

@interface PBBulletinService : NSObject
{
    PBSystemServiceConnection *_remoteConnection;	// 8 = 0x8
    NSMapTable *_viewControllersByBulletin;	// 16 = 0x10
    NSMapTable *_bulletinInfoByBulletin;	// 24 = 0x18
    NSMutableDictionary *_pendingBulletinsByRequestID;	// 32 = 0x20
    id <PBSBulletinServiceDelegate> _delegateProxy;	// 40 = 0x28
    id <PBSBulletinServiceInteractionDelegate> _interactionDelegateProxy;	// 48 = 0x30
    PBSystemOverlayController *_overlayController;	// 56 = 0x38
    PBBulletinToBannerAdapter *_bulletinToBannerAdapter;	// 64 = 0x40
}

+ (void)_setBulletinService:(id)arg1 forViewController:(id)arg2;	// IMP=0x0020000000107dcc
+ (id)_bulletinServiceForViewController:(id)arg1;	// IMP=0x0010000000107d0c
+ (double)_timeoutForBulletin:(id)arg1;	// IMP=0x0010000000106aeb
+ (id)observingBulletinActionHandlerForBulletinWithIdentifier:(id)arg1;	// IMP=0x001000000010370c
+ (void)applicationTerminateBulletinViewController:(id)arg1;	// IMP=0x0010000000103620
+ (void)applicationRetireBulletinViewController:(id)arg1;	// IMP=0x0010000000103534
+ (_Bool)applicationDismissBulletinViewController:(id)arg1;	// IMP=0x0010000000103438
+ (void)applicationDeactivateBulletinViewController:(id)arg1;	// IMP=0x001000000010334f
+ (void)applicationBulletinHandleMenuButtonForViewController:(id)arg1 withCompletion:(CDUnknownBlockType)arg2;	// IMP=0x001000000010324b
+ (void)applicationToggleBulletinViewControllerSize:(id)arg1;	// IMP=0x00100000001031e0
+ (unsigned long long)applicationActivateBulletinViewController:(id)arg1;	// IMP=0x00100000001030b3
+ (_Bool)applicationShouldActivateBulletinViewController:(id)arg1 forAction:(unsigned long long)arg2;	// IMP=0x001000000010308d
+ (unsigned long long)applicationActivationActionsForBulletinViewController:(id)arg1;	// IMP=0x0010000000102ecd
+ (id)_bulletinServicesByBulletinIdentifier;	// IMP=0x0010000000102227
+ (id)_bulletinServicesByViewController;	// IMP=0x00100000001021b6
- (void).cxx_destruct;	// IMP=0x0020000000108055
@property(readonly, nonatomic) PBBulletinToBannerAdapter *bulletinToBannerAdapter; // @synthesize bulletinToBannerAdapter=_bulletinToBannerAdapter;
@property(readonly, nonatomic) PBSystemOverlayController *overlayController; // @synthesize overlayController=_overlayController;
@property(retain) id <PBSBulletinServiceInteractionDelegate> interactionDelegateProxy; // @synthesize interactionDelegateProxy=_interactionDelegateProxy;
@property(retain) id <PBSBulletinServiceDelegate> delegateProxy; // @synthesize delegateProxy=_delegateProxy;
@property(readonly, nonatomic) NSMutableDictionary *pendingBulletinsByRequestID; // @synthesize pendingBulletinsByRequestID=_pendingBulletinsByRequestID;
@property(readonly, nonatomic) NSMapTable *bulletinInfoByBulletin; // @synthesize bulletinInfoByBulletin=_bulletinInfoByBulletin;
@property(readonly, nonatomic) NSMapTable *viewControllersByBulletin; // @synthesize viewControllersByBulletin=_viewControllersByBulletin;
@property(readonly, nonatomic) __weak PBSystemServiceConnection *remoteConnection; // @synthesize remoteConnection=_remoteConnection;
- (void)_setBulletinInfo:(id)arg1 forBulletin:(id)arg2;	// IMP=0x0010000000107ad3
- (id)_bulletinInfoForBulletin:(id)arg1;	// IMP=0x0010000000107a13
- (id)_bulletinForBulletinInfo:(id)arg1;	// IMP=0x00100000001077de
- (void)_setViewController:(id)arg1 forBulletin:(id)arg2;	// IMP=0x00100000001075a5
- (id)_viewControllerForBulletin:(id)arg1;	// IMP=0x00100000001074e5
- (id)_bulletinForViewController:(id)arg1;	// IMP=0x00100000001072b0
- (_Bool)_shouldBeginUserInteractionOnActivationForViewController:(id)arg1;	// IMP=0x00100000001071fb
- (_Bool)_bulletinIsPending:(id)arg1;	// IMP=0x001000000010712b
- (void)_updateRequestForBulletin:(id)arg1 withBulletin:(id)arg2;	// IMP=0x0010000000106eb9
- (id)_bulletinForRequestID:(unsigned long long)arg1;	// IMP=0x0010000000106de0
- (void)_setBulletin:(id)arg1 forRequestID:(unsigned long long)arg2;	// IMP=0x0010000000106cb5
- (void)_updateVideoBulletinViewController:(id)arg1 withBulletin:(id)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x00100000001067de
- (void)toggleBulletinSizeForViewController:(id)arg1;	// IMP=0x0010000000106753
- (void)_setUserInteractionEnabled:(_Bool)arg1 forViewController:(id)arg2;	// IMP=0x00100000001066c4
- (void)_handleMenuButtonForViewController:(id)arg1 withCompletion:(CDUnknownBlockType)arg2;	// IMP=0x0010000000106622
- (void)_prepareToPresentViewController:(id)arg1;	// IMP=0x001000000010655a
- (void)_handleApplicationDismissalForViewController:(id)arg1 withReason:(unsigned long long)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x00100000001060d8
- (void)_handleApplicationDismissalForViewController:(id)arg1 withReason:(unsigned long long)arg2;	// IMP=0x00100000001060c2
- (void)_handleApplicationDismissalForBulletin:(id)arg1 withReason:(unsigned long long)arg2;	// IMP=0x0010000000105e76
- (void)_completeWithBulletin:(id)arg1 success:(_Bool)arg2 error:(id)arg3 completion:(CDUnknownBlockType)arg4;	// IMP=0x0010000000105cae
- (id)_reserveTableSpaceForBulletin:(id)arg1 error:(id *)arg2;	// IMP=0x0010000000105b52
- (void)adapter:(id)arg1 cleanupForBulletin:(id)arg2;	// IMP=0x0010000000105a54
- (id)adapter:(id)arg1 bulletinInfoForBulletin:(id)arg2;	// IMP=0x0010000000105a2e
- (id)serviceDelegateForAdapter:(id)arg1;	// IMP=0x0010000000105a0b
- (void)remoteBulletinViewController:(id)arg1 didReceiveBulletinResponse:(id)arg2;	// IMP=0x00100000001055cb
- (void)setInteractionDelegate:(id)arg1;	// IMP=0x00100000001055b8
- (void)setDelegate:(id)arg1;	// IMP=0x00100000001055a5
- (void)_mainqueue_dismissBulletin:(id)arg1;	// IMP=0x00100000001051af
- (void)dismissBulletin:(id)arg1;	// IMP=0x001000000010510f
- (id)_updateBulletin:(id)arg1 withMessage:(id)arg2 withCompletion:(CDUnknownBlockType)arg3;	// IMP=0x0010000000104cd7
- (id)updateBulletin:(id)arg1 withMessage:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;	// IMP=0x001000000010487b
- (void)xpcUpdateBulletin:(id)arg1 withMessage:(id)arg2 withCompletion:(CDUnknownBlockType)arg3;	// IMP=0x001000000010476b
- (void)_presentBulletin:(id)arg1 prepared:(CDUnknownBlockType)arg2 withCompletion:(CDUnknownBlockType)arg3;	// IMP=0x0010000000103808
- (void)presentBulletin:(id)arg1 withCompletion:(CDUnknownBlockType)arg2;	// IMP=0x00100000001037f0
- (void)bulletinManager:(id)arg1 willPresentBulletinViewController:(id)arg2 withActivationActions:(unsigned long long)arg3;	// IMP=0x0010000000102dd7
- (MISSING_TYPE *)invalidate;	// IMP=0x001000000010245f
- (void)dealloc;	// IMP=0x00100000001023ea
- (id)initWithRemoteConnection:(id)arg1;	// IMP=0x001000000010229c
- (id)init;	// IMP=0x001000000010228e

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"NSString",?,R,C

@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

