//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class BSServiceConnection, NSString;
@protocol BSServiceConnectionHost;

@interface PBScheduledSleepService : NSObject
{
    BSServiceConnection<BSServiceConnectionHost> *_remoteConnection;	// 8 = 0x8
}

- (void).cxx_destruct;	// IMP=0x002000000019bcb1
@property(readonly, nonatomic) __weak BSServiceConnection<BSServiceConnectionHost> *remoteConnection; // @synthesize remoteConnection=_remoteConnection;
- (oneway void)cancelScheduledSleepWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x001000000019b9df
- (oneway void)getCurrentScheduledSleepWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x001000000019b803
- (oneway void)getAvailableScheduledSleepRequestsWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x001000000019b627
- (oneway void)scheduleSleepWithRequest:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x001000000019b3fa
- (id)initWithRemoteConnection:(id)arg1;	// IMP=0x001000000019b37f

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"NSString",?,R,C

@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

