//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSMutableSet, NSString, PBSystemGestureManager;
@protocol PBSystemGestureRecognizerManager;

@interface PBSystemGestureKeychordAssistant : NSObject
{
    id <PBSystemGestureRecognizerManager> _systemGestureRecognizerManager;	// 8 = 0x8
    PBSystemGestureManager *_systemGestureManager;	// 16 = 0x10
    NSMutableSet *_gestureRecognizers;	// 24 = 0x18
}

- (void).cxx_destruct;	// IMP=0x002000000015e583
@property(readonly, nonatomic) NSMutableSet *gestureRecognizers; // @synthesize gestureRecognizers=_gestureRecognizers;
@property(readonly, nonatomic) __weak PBSystemGestureManager *systemGestureManager; // @synthesize systemGestureManager=_systemGestureManager;
@property(readonly, nonatomic) id <PBSystemGestureRecognizerManager> systemGestureRecognizerManager; // @synthesize systemGestureRecognizerManager=_systemGestureRecognizerManager;
- (void)_systemKeychordRecognized:(id)arg1;	// IMP=0x001000000015e3d7
- (_Bool)gestureRecognizer:(id)arg1 shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)arg2;	// IMP=0x001000000015e3cf
- (void)addKeychordGestureWithPressTypes:(id)arg1 minimumPressDuration:(double)arg2 target:(id)arg3 action:(SEL)arg4;	// IMP=0x001000000015e2c2
- (void)dealloc;	// IMP=0x001000000015e16e
- (id)initWithSystemGestureRecognizerManager:(id)arg1 systemGestureManager:(id)arg2;	// IMP=0x001000000015e098

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"NSString",?,R,C

@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

