//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class MRAVConcreteOutputContext, MRDeviceInfo, MROrigin;
@protocol OS_dispatch_queue;

@interface MRDAirPlayLeaderInfoPublisher : NSObject
{
    MRDeviceInfo *_deviceInfo;	// 8 = 0x8
    MROrigin *_origin;	// 16 = 0x10
    MRAVConcreteOutputContext *_outputContext;	// 24 = 0x18
    NSObject<OS_dispatch_queue> *_workerQueue;	// 32 = 0x20
}

- (void).cxx_destruct;	// IMP=0x0020000000058bab
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *workerQueue; // @synthesize workerQueue=_workerQueue;
@property(readonly, nonatomic) MRAVConcreteOutputContext *outputContext; // @synthesize outputContext=_outputContext;
@property(readonly, nonatomic) MROrigin *origin; // @synthesize origin=_origin;
- (void)publish;	// IMP=0x0010000000058a1b
- (void)publishToOutputDevices:(id)arg1;	// IMP=0x00100000000587fb
- (id)currentData;	// IMP=0x001000000005874d
- (_Bool)isValidOutputDevice:(id)arg1;	// IMP=0x00100000000586f8
- (void)handleDeviceInfoDidChange:(id)arg1;	// IMP=0x00100000000585e9
@property(retain, nonatomic) MRDeviceInfo *deviceInfo; // @synthesize deviceInfo=_deviceInfo;
- (id)init;	// IMP=0x001000000005842b
- (id)initWithOrigin:(id)arg1 outputContext:(id)arg2;	// IMP=0x001000000005819f

@end

