//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class MRDHostedRoutingController, NSMutableSet, NSString, NSXPCListener;
@protocol OS_dispatch_queue;

@interface MRDAVHostedRoutingService : NSObject
{
    NSObject<OS_dispatch_queue> *_serialQueue;	// 8 = 0x8
    NSXPCListener *_anonymousListener;	// 16 = 0x10
    NSMutableSet *_hostedDiscoverySessions;	// 24 = 0x18
    MRDHostedRoutingController *_hostedRoutingController;	// 32 = 0x20
}

- (void).cxx_destruct;	// IMP=0x0020000000073c98
@property(readonly, nonatomic) MRDHostedRoutingController *hostedRoutingController; // @synthesize hostedRoutingController=_hostedRoutingController;
- (void)collectDiagnostic:(id)arg1;	// IMP=0x0010000000073ae8
- (_Bool)listener:(id)arg1 shouldAcceptNewConnection:(id)arg2;	// IMP=0x00100000000739eb
- (void)hostedDiscoverySessionDidInvalidate:(id)arg1;	// IMP=0x001000000007393f
- (id)endpointForDeviceUID:(id)arg1;	// IMP=0x00100000000736ba
- (id)endpointForOrigin:(id)arg1;	// IMP=0x0010000000073274
- (id)xpcEndpoint;	// IMP=0x001000000007325e
- (id)init;	// IMP=0x0010000000073151

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"NSString",?,R,C

@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

