//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class CUSystemMonitor, IDSAccountController, MISSING_TYPE, MRGroupSessionEligibilityStatus, NSHashTable, NSString;
@protocol OS_dispatch_queue;

@interface MRDGroupSessionEligibilityMonitor : NSObject
{
    MRGroupSessionEligibilityStatus *_eligibilityStatus;	// 8 = 0x8
    NSObject<OS_dispatch_queue> *_queue;	// 16 = 0x10
    MISSING_TYPE *_notificationQueue;	// 24 = 0x18
    IDSAccountController *_accountController;	// 32 = 0x20
    CUSystemMonitor *_systemMonitor;	// 40 = 0x28
    NSHashTable *_observers;	// 48 = 0x30
}

+ (id)sharedMonitor;	// IMP=0x0020000000194632
- (void).cxx_destruct;	// IMP=0x00200000001966e5
@property(retain, nonatomic) NSHashTable *observers; // @synthesize observers=_observers;
@property(retain, nonatomic) CUSystemMonitor *systemMonitor; // @synthesize systemMonitor=_systemMonitor;
@property(retain, nonatomic) IDSAccountController *accountController; // @synthesize accountController=_accountController;
@property(readonly, nonatomic) NSObject<OS_dispatch_queue> *notificationQueue; // @synthesize notificationQueue=_notificationQueue;
@property(readonly, nonatomic) NSObject<OS_dispatch_queue> *queue; // @synthesize queue=_queue;
@property(retain, nonatomic) MRGroupSessionEligibilityStatus *eligibilityStatus; // @synthesize eligibilityStatus=_eligibilityStatus;
- (void)accountController:(id)arg1 accountDisabled:(id)arg2;	// IMP=0x001000000019665d
- (void)accountController:(id)arg1 accountEnabled:(id)arg2;	// IMP=0x001000000019664b
- (void)accountController:(id)arg1 accountRemoved:(id)arg2;	// IMP=0x0010000000196639
- (void)accountController:(id)arg1 accountAdded:(id)arg2;	// IMP=0x0010000000196627
- (void)handleDeviceInfoChangeNotification:(id)arg1;	// IMP=0x00100000001964f7
- (void)handleEndpointNotification:(id)arg1;	// IMP=0x0010000000196470
- (void)handleCloudStateChangeNotification:(id)arg1;	// IMP=0x00100000001963e9
- (_Bool)isCarPlay;	// IMP=0x00100000001963e1
- (_Bool)needsAcknowledgement;	// IMP=0x00100000001963d7
- (unsigned char)pickedRouteType;	// IMP=0x00100000001962cf
- (unsigned long long)hostingStateForUserState:(id)arg1 reason:(id *)arg2;	// IMP=0x0010000000195ecf
- (unsigned long long)bestHostingStateForUserStates:(id)arg1 reason:(id *)arg2;	// IMP=0x0010000000195bbe
- (unsigned long long)hostingStateForEligibilityStatus:(id)arg1 reason:(id *)arg2;	// IMP=0x0010000000195b1d
- (unsigned long long)joiningStateForEligibilityStatus:(id)arg1 reason:(id *)arg2;	// IMP=0x0010000000195b08
- (void)_onQueue_notifyObservers:(id)arg1;	// IMP=0x0010000000195904
- (void)removeObserver:(id)arg1;	// IMP=0x0010000000195859
- (void)addObserver:(id)arg1;	// IMP=0x00100000001956d4
- (void)reevaluateState;	// IMP=0x0010000000195027
@property(readonly, copy) NSString *description;
- (void)dealloc;	// IMP=0x0010000000194e07
- (void)initializeObserversAndState;	// IMP=0x001000000019482c
- (id)init;	// IMP=0x0010000000194687

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"NSString",?,R,C

@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

