//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSMutableDictionary;

@interface MRDIDSRemoteControlServiceRemoteControlChannels : NSObject
{
    NSMutableDictionary *_channels;	// 8 = 0x8
}

- (void).cxx_destruct;	// IMP=0x002000000007a6d4
- (id)channelForDestination:(id)arg1 session:(id)arg2;	// IMP=0x001000000007a64e
- (void)removeChannelForDestination:(id)arg1;	// IMP=0x001000000007a425
- (void)addChannel:(id)arg1 forDestination:(id)arg2 session:(id)arg3;	// IMP=0x001000000007a32d
- (id)debugDescription;	// IMP=0x001000000007a297

@end

