//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <MediaRemote/MRAVRoutingDiscoverySession.h>

@class NSObject, NSString;
@protocol OS_dispatch_queue;

@interface MRDRoutingDiscoverySession : MRAVRoutingDiscoverySession
{
    unsigned int _discoveryMode;	// 8 = 0x8
    NSObject<OS_dispatch_queue> *_workerQueue;	// 16 = 0x10
}

- (void).cxx_destruct;	// IMP=0x0020000000084654
- (_Bool)onlyDiscoversBluetoothDevices;	// IMP=0x001000000008464c
- (void)setOnlyDiscoversBluetoothDevices:(_Bool)arg1;	// IMP=0x0010000000084646
- (id)routingContextUID;	// IMP=0x001000000008463e
- (void)setRoutingContextUID:(id)arg1;	// IMP=0x0010000000084638
- (unsigned int)targetAudioSessionID;	// IMP=0x0010000000084630
- (void)setTargetAudioSessionID:(unsigned int)arg1;	// IMP=0x001000000008462a
- (_Bool)devicePresenceDetected;	// IMP=0x00100000000845e2
- (id)availableOutputDevices;	// IMP=0x00100000000845d0
- (id)availableEndpoints;	// IMP=0x0010000000084513
- (unsigned int)endpointFeatures;	// IMP=0x0010000000084508
- (void)hostedRoutingController:(id)arg1 outputDevicesDidChange:(id)arg2 forFeature:(unsigned int)arg3;	// IMP=0x00100000000844f3
- (void)hostedRoutingController:(id)arg1 endpointsDidChange:(id)arg2;	// IMP=0x0010000000084437
@property(nonatomic) unsigned int discoveryMode;
@property(readonly, nonatomic) NSString *clientIdentifier;
@property(readonly, copy) NSString *debugDescription;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"NSString",?,R,C

@property(readonly, copy) NSString *description;
- (void)dealloc;	// IMP=0x0010000000083eb4
- (id)initWithConfiguration:(id)arg1;	// IMP=0x0010000000083c99

// Remaining properties
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

