//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <UIKit/UIViewController.h>

@class NSString, VUIAccessViewController;

@interface TVAccessViewServiceViewController : UIViewController
{
    VUIAccessViewController *_accessViewController;	// 8 = 0x8
}

+ (id)_remoteViewControllerInterface;	// IMP=0x0020000000001d0b
+ (id)_exportedInterface;	// IMP=0x0010000000001c07
- (void).cxx_destruct;	// IMP=0x0020000000001ded
- (void)_menuPressed:(id)arg1;	// IMP=0x0010000000001da9
- (void)viewServiceEndPresentationWithOptions:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x0010000000001bf0
- (void)viewServiceUpdatePresentationWithOptions:(id)arg1;	// IMP=0x0010000000001bea
- (void)viewServiceBeginPresentationWithOptions:(id)arg1;	// IMP=0x0010000000001870
- (void)viewDidLoad;	// IMP=0x00100000000017bb

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"NSString",?,R,C

@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

