//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSArray;

@interface SecureBackupLog : NSObject
{
    _Bool _allActivitiesComplete;	// 8 = 0x8
    unsigned long long _totalOperations;	// 16 = 0x10
    NSArray *_activities;	// 24 = 0x18
}

+ (_Bool)supportsSecureCoding;	// IMP=0x002000000003b291
- (void).cxx_destruct;	// IMP=0x002000000003b8c4
@property(readonly, nonatomic) NSArray *activities; // @synthesize activities=_activities;
@property(readonly, nonatomic) unsigned long long totalOperations; // @synthesize totalOperations=_totalOperations;
@property(readonly, nonatomic) _Bool allActivitiesComplete; // @synthesize allActivitiesComplete=_allActivitiesComplete;
- (void)enumerateAllOperationsWithBlock:(CDUnknownBlockType)arg1;	// IMP=0x001000000003b6d5
- (_Bool)isEqual:(id)arg1;	// IMP=0x001000000003b595
- (void)encodeWithCoder:(id)arg1;	// IMP=0x001000000003b4bb
- (id)initWithCoder:(id)arg1;	// IMP=0x001000000003b32f
- (id)initWithActivities:(id)arg1 allComplete:(_Bool)arg2 totalOperations:(unsigned long long)arg3;	// IMP=0x001000000003b299

@end

