//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface MCCertificateTransparencyPayloadHandler
{
}

- (id)exceptionsDictionary;	// IMP=0x0040000000023f22
- (_Bool)setExceptions:(id)arg1 outError:(id *)arg2;	// IMP=0x0010000000023ed1
- (id)applicationID;	// IMP=0x0010000000023d3f
- (void)_remove;	// IMP=0x0010000000023d29
- (_Bool)_installOutError:(id *)arg1;	// IMP=0x0010000000023cd3
- (void)unsetAside;	// IMP=0x0010000000023cbf
- (void)setAside;	// IMP=0x0010000000023cad
- (void)remove;	// IMP=0x0010000000023c41
- (_Bool)installWithInstaller:(id)arg1 options:(id)arg2 interactionClient:(id)arg3 outError:(id *)arg4;	// IMP=0x0010000000023c2c

@end

