//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class NSString;

@interface MCGlobalEthernetPayloadHandler
{
    NSString *_setAsideProfileID;	// 32 = 0x20
}

- (void).cxx_destruct;	// IMP=0x002000000007d9f0
- (void)unsetAside;	// IMP=0x001000000007d9ea
- (void)setAside;	// IMP=0x001000000007d9e4
- (void)remove;	// IMP=0x001000000007d9c3
- (_Bool)installWithInstaller:(id)arg1 options:(id)arg2 interactionClient:(id)arg3 outError:(id *)arg4;	// IMP=0x001000000007d960
- (id)profileMetadata;	// IMP=0x001000000007d8d2
- (id)initWithPayload:(id)arg1 profileHandler:(id)arg2;	// IMP=0x001000000007d8a3

@end

