//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@interface MCProfileAnalyticsHelper : NSObject
{
}

+ (id)_getBoolDictionaryFromKeySet:(id)arg1;	// IMP=0x0040000000074295
+ (id)_containsPayloadsDictionary;	// IMP=0x0010000000074158
+ (void)addContainsPayloadInfoWithProfile:(id)arg1 eventPayload:(id)arg2;	// IMP=0x0010000000073e43

@end

