//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <ProtocolBuffer/PBCodable.h>

@class NSData, NSString;

@interface CPLCloudKitFeatureVersion : PBCodable
{
    long long _version;	// 8 = 0x8
    NSString *_etag;	// 16 = 0x10
    NSData *_serverToken;	// 24 = 0x18
    struct {
        unsigned int version:1;
    } _has;	// 32 = 0x20
}

- (void).cxx_destruct;	// IMP=0x00200000000cebb0
@property(retain, nonatomic) NSString *etag; // @synthesize etag=_etag;
@property(retain, nonatomic) NSData *serverToken; // @synthesize serverToken=_serverToken;
@property(nonatomic) long long version; // @synthesize version=_version;
- (void)mergeFrom:(id)arg1;	// IMP=0x00100000000cead1
- (unsigned long long)hash;	// IMP=0x00100000000cea54
- (_Bool)isEqual:(id)arg1;	// IMP=0x00100000000ce96c
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x00100000000ce8a9
- (void)copyTo:(id)arg1;	// IMP=0x00100000000ce825
- (void)writeTo:(id)arg1;	// IMP=0x00100000000ce7a2
- (_Bool)readFrom:(id)arg1;	// IMP=0x00100000000ce795
- (id)dictionaryRepresentation;	// IMP=0x00100000000ce4a7
- (id)description;	// IMP=0x00100000000ce3f8
@property(readonly, nonatomic) _Bool hasEtag;
@property(readonly, nonatomic) _Bool hasServerToken;
@property(nonatomic) _Bool hasVersion;

@end

