//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSMutableDictionary;

@interface CPLCKRecordFetchCache : NSObject
{
    NSMutableDictionary *_mapping;	// 8 = 0x8
    unsigned long long _missCount;	// 16 = 0x10
    unsigned long long _hitCount;	// 24 = 0x18
    unsigned long long _dropCount;	// 32 = 0x20
    unsigned long long _fetchCount;	// 40 = 0x28
}

- (void).cxx_destruct;	// IMP=0x002000000009da5a
- (id)redactedDescription;	// IMP=0x001000000009da48
- (id)description;	// IMP=0x001000000009d9da
- (void)willFetchRecordCount:(unsigned long long)arg1;	// IMP=0x001000000009d9d0
- (void)resetTrackingCounts;	// IMP=0x001000000009d9bf
- (void)didModifyRecordWithID:(id)arg1;	// IMP=0x001000000009d948
- (id)cachedRecordWithID:(id)arg1;	// IMP=0x001000000009d8e3
- (void)didFetchRecordWithID:(id)arg1 record:(id)arg2;	// IMP=0x001000000009d872
- (id)init;	// IMP=0x001000000009d807

@end

