//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class CPLConfigurationDictionary, CPLConfigurationFetcher, NSArray, NSMutableArray, NSMutableDictionary, NSString;
@protocol CPLEngineParametersStorage, CPLEngineWrapperArrayDelegate, OS_dispatch_queue;

@interface CPLEngineWrapperArray : NSObject
{
    NSMutableDictionary *_wrappers;	// 8 = 0x8
    NSMutableDictionary *_unopenedWrappers;	// 16 = 0x10
    NSMutableDictionary *_previousOpenErrors;	// 24 = 0x18
    NSMutableArray *_stopAllBlocks;	// 32 = 0x20
    NSMutableDictionary *_openObservers;	// 40 = 0x28
    CPLConfigurationFetcher *_configurationFetcher;	// 48 = 0x30
    NSMutableDictionary *_autoClosingWrappers;	// 56 = 0x38
    id <CPLEngineParametersStorage> _parametersStorage;	// 64 = 0x40
    NSObject<OS_dispatch_queue> *_queue;	// 72 = 0x48
    id <CPLEngineWrapperArrayDelegate> _delegate;	// 80 = 0x50
}

+ (void)setTimeToWaitForRegisteredWrapper:(double)arg1;	// IMP=0x002000000000fa84
+ (double)timeToWaitForRegisteredWrapper;	// IMP=0x001000000000fa76
- (void).cxx_destruct;	// IMP=0x0020000000015a82
@property(nonatomic) __weak id <CPLEngineWrapperArrayDelegate> delegate; // @synthesize delegate=_delegate;
@property(readonly, nonatomic) NSObject<OS_dispatch_queue> *queue; // @synthesize queue=_queue;
@property(readonly, nonatomic) id <CPLEngineParametersStorage> parametersStorage; // @synthesize parametersStorage=_parametersStorage;
- (void)wrapperDidCompleteInitialSyncOfMainScope:(id)arg1;	// IMP=0x00100000000159eb
- (void)wrapperNeedsInitialDownloadOfMainScope:(id)arg1;	// IMP=0x001000000001598f
- (void)wrapperShouldBeDropped:(id)arg1;	// IMP=0x00100000000157b5
- (void)wrapper:(id)arg1 getStatusDictionaryWithCompletionHandler:(CDUnknownBlockType)arg2;	// IMP=0x0010000000015742
- (void)wrapper:(id)arg1 getStatusWithCompletionHandler:(CDUnknownBlockType)arg2;	// IMP=0x00100000000156cf
- (void)wrapperLibraryDidClose:(id)arg1;	// IMP=0x001000000001542f
- (void)wrapper:(id)arg1 libraryDidOpenWithError:(id)arg2;	// IMP=0x00100000000151b7
- (void)_registerOpenError:(id)arg1 forWrapper:(id)arg2;	// IMP=0x0010000000015083
- (void)wrapperEmergencyExit:(id)arg1;	// IMP=0x0010000000014e4e
- (void)configurationFetcher:(id)arg1 didUpdateConfigurationDictionary:(id)arg2 configurationHasChanged:(_Bool)arg3;	// IMP=0x0010000000014cd8
- (void)cancelConfigurationDictionariesRefresh;	// IMP=0x0010000000014c9d
- (void)refreshAllConfigurationDictionariesWithCompletionHandler:(CDUnknownBlockType)arg1;	// IMP=0x00100000000149ea
- (void)refreshAllConfigurationDictionaries;	// IMP=0x00100000000149d6
@property(readonly, nonatomic) CPLConfigurationDictionary *oldestConfigurationDictionary;
@property(readonly, nonatomic) CPLConfigurationDictionary *mostRecentConfigurationDictionary;
@property(readonly, nonatomic) NSArray *wrapperStatuses;
- (void)_dropWrapper:(id)arg1;	// IMP=0x00100000000141a8
- (void)wipeEnginesIfNecessary;	// IMP=0x0010000000013f42
- (void)requestRegisteredWrapperWithIdentifier:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;	// IMP=0x001000000001304a
- (void)executePeriodicUploadOfComputeStatesWithCompletionHandler:(CDUnknownBlockType)arg1;	// IMP=0x0010000000012dd4
- (void)executeMaintenanceWithCompletionHandler:(CDUnknownBlockType)arg1;	// IMP=0x0010000000012b1a
- (void)_executeMaintenanceWithEnumerator:(id)arg1 progress:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;	// IMP=0x00100000000124e2
- (void)forceBackupWithActivity:(id)arg1 forceClientPush:(_Bool)arg2 completionHandler:(CDUnknownBlockType)arg3;	// IMP=0x001000000001237b
- (void)_forceBackupWithActivity:(id)arg1 forceClientPush:(_Bool)arg2 enumerator:(id)arg3 progress:(id)arg4 completionHandler:(CDUnknownBlockType)arg5;	// IMP=0x0010000000011c23
- (id)_wrappersLibraryIdentifierEnumerator;	// IMP=0x0010000000011bd3
- (_Bool)isWrapperOpened:(id)arg1;	// IMP=0x0010000000011b68
- (void)enumerateOpenedWrappersWithBlock:(CDUnknownBlockType)arg1;	// IMP=0x0010000000011a3a
- (void)enumerateWrappersWithBlock:(CDUnknownBlockType)arg1;	// IMP=0x001000000001187b
- (id)openedWrapperWithLibraryIdentifier:(id)arg1;	// IMP=0x00100000000117ec
- (id)registeredWrapperWithLibraryIdentifier:(id)arg1 error:(id *)arg2;	// IMP=0x001000000001168a
- (id)registeredWrapperCreateIfNecessaryWithParameters:(id)arg1 error:(id *)arg2;	// IMP=0x00100000000111fc
@property(readonly, nonatomic) NSArray *registeredLibraryIdentifiers;
@property(readonly, nonatomic) unsigned long long unopenedCount;
- (unsigned long long)_countOfUltimatelyOpenedWrappers;	// IMP=0x001000000001106b
@property(readonly, nonatomic) unsigned long long count;
- (void)emergencyStop;	// IMP=0x0010000000010f7c
- (void)stopAllWithCompletionHandler:(CDUnknownBlockType)arg1;	// IMP=0x0010000000010d6e
- (void)_removeEngineWrapperOpenObserverWithIdentifier:(id)arg1;	// IMP=0x0010000000010d22
- (void)_addEngineWrapperOpenObserver:(CDUnknownBlockType)arg1 withIdentifier:(id)arg2;	// IMP=0x0010000000010c64
- (void)_callStopAllBlocks;	// IMP=0x0010000000010b3b
- (id)_instantiateWrapperWithParameters:(id)arg1 createIfNecessary:(_Bool)arg2 error:(id *)arg3;	// IMP=0x0010000000010471
- (id)_loadWrapperWithIdentifier:(id)arg1 error:(id *)arg2;	// IMP=0x0010000000010230
- (_Bool)_canReallyOpenWrapper:(id)arg1 error:(id *)arg2;	// IMP=0x001000000001012f
- (_Bool)_autoCloseOneWrapper;	// IMP=0x0010000000010046
- (_Bool)_autoCloseWrapper:(id)arg1;	// IMP=0x001000000000ff3d
- (_Bool)_canAutoCloseWrapper:(id)arg1;	// IMP=0x001000000000fee8
- (_Bool)_shouldAutoOpenWrapper:(id)arg1 error:(id *)arg2;	// IMP=0x001000000000fddc
- (void)loadRegisteredWrappers;	// IMP=0x001000000000fb98
- (id)initWithParametersStorage:(id)arg1 queue:(id)arg2;	// IMP=0x001000000000fab3

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"NSString",?,R,C

@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

