//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface CPLPrequeliteSynthesizedVariable
{
}

+ (void)initialize;	// IMP=0x00400000001a0387
- (void)setValue:(id)arg1;	// IMP=0x00400000001a044d
- (id)valueWithConstructor:(CDUnknownBlockType)arg1;	// IMP=0x00100000001a03ac

@end

