//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class NSString;

@interface CPLPrequeliteClientCache
{
}

- (_Bool)deleteRecordsForScopeIndex:(long long)arg1 maxCount:(long long)arg2 deletedCount:(long long *)arg3 error:(id *)arg4;	// IMP=0x00200000001b7617
- (void)fillRelatedIdentifiersInChange:(id)arg1;	// IMP=0x00100000001b7393
- (id)statusPerScopeIndex;	// IMP=0x00100000001b7331
- (id)statusDictionary;	// IMP=0x00100000001b71ce
- (id)status;	// IMP=0x00100000001b7060
- (_Bool)_updateRelatedIdentifier:(id)arg1 forRecordWithIdentifier:(id)arg2;	// IMP=0x00100000001b6f7a
- (_Bool)_deleteBadRelations;	// IMP=0x00100000001b6eae
- (id)_badContainerRelationsIdentifiers;	// IMP=0x00100000001b6daa
- (unsigned long long)countOfRecordsWithRelatedScopedIdentifier:(id)arg1 class:(Class)arg2;	// IMP=0x00100000001b6c55
- (_Bool)hasRecordWithRelatedScopedIdentifier:(id)arg1 class:(Class)arg2;	// IMP=0x00100000001b6b00
- (id)recordsWithRelatedScopedIdentifier:(id)arg1 class:(Class)arg2;	// IMP=0x00100000001b6605
- (id)recordsWithRelatedScopedIdentifier:(id)arg1;	// IMP=0x00100000001b6142
- (_Bool)hasRecordWithScopedIdentifier:(id)arg1;	// IMP=0x00100000001b6019
- (id)relatedScopedIdentifierForRecordWithScopedIdentifier:(id)arg1;	// IMP=0x00100000001b5e6a
- (id)recordWithScopedIdentifier:(id)arg1;	// IMP=0x00100000001b5b34
- (_Bool)deleteRecordWithScopedIdentifier:(id)arg1 error:(id *)arg2;	// IMP=0x00100000001b58e1
- (_Bool)updateRecord:(id)arg1 error:(id *)arg2;	// IMP=0x00100000001b54d5
- (_Bool)addRecord:(id)arg1 error:(id *)arg2;	// IMP=0x00100000001b509f
- (_Bool)upgradeStorageToVersion:(long long)arg1;	// IMP=0x00100000001b4e19
- (_Bool)initializeStorage;	// IMP=0x00100000001b4c9b
- (id)initWithAbstractObject:(id)arg1;	// IMP=0x00100000001b4c6c

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"NSString",?,R,C

@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

