//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSSet, NSURL;

@interface MIJournal : NSObject
{
}

+ (id)sharedInstance;	// IMP=0x00400000000306b7
- (id)journaledEntriesWithError:(id *)arg1;	// IMP=0x002000000003151b
- (id)journalEntryForUniqueIdentifier:(id)arg1;	// IMP=0x001000000003134a
- (void)reconcile;	// IMP=0x00100000000311b6
- (void)_enumerateJournaledEntriesContinuingOnFailure:(_Bool)arg1 withBlock:(CDUnknownBlockType)arg2;	// IMP=0x0010000000030de1
- (_Bool)purgeJournalEntry:(id)arg1 withError:(id *)arg2;	// IMP=0x0010000000030b6f
- (_Bool)writeJournalEntry:(id)arg1 withError:(id *)arg2;	// IMP=0x001000000003088f
- (id)_journalStorageURLForUniqueIdentifier:(id)arg1;	// IMP=0x0010000000030800
@property(readonly, nonatomic) NSURL *journalStorageBase;
@property(readonly, nonatomic) NSSet *journalEntryClasses;
- (id)init;	// IMP=0x0010000000030744

@end

