//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@interface NDFileUtilities : NSObject
{
}

+ (_Bool)itemShouldBePurged:(id)arg1;	// IMP=0x004000000003c136
+ (void)markItemAsPurged:(id)arg1;	// IMP=0x001000000003c0ea
+ (id)fetchStreamingZipModificationDate:(id)arg1;	// IMP=0x001000000003c064
+ (void)removeStreamingZipModificationDate:(id)arg1;	// IMP=0x001000000003c002
+ (void)updateStreamingZipModificationDate:(id)arg1;	// IMP=0x001000000003bf6c
+ (void)setDaemonWorkState:(_Bool)arg1;	// IMP=0x001000000003bdd5
+ (id)defaultDownloadDirectoryForBundleID:(id)arg1;	// IMP=0x001000000003bd37
+ (id)defaultDownloadDirectoryContainer;	// IMP=0x001000000003bab0
+ (void)createDirectoryAtURL:(id)arg1;	// IMP=0x001000000003b92d
+ (void)createDirectoryAtPath:(id)arg1;	// IMP=0x001000000003b7aa
+ (_Bool)createDataVaultDirectoryAtPath:(id)arg1;	// IMP=0x001000000003b2d0
+ (void)removeItemAtURL:(id)arg1;	// IMP=0x001000000003b155
+ (void)removeItemAtPath:(id)arg1;	// IMP=0x001000000003afda
+ (id)nsurlsessiondLaunchdPath;	// IMP=0x001000000003af68
+ (id)sessionPath:(id)arg1 forBundleID:(id)arg2;	// IMP=0x001000000003ae99
+ (id)bundleManagerPath:(id)arg1;	// IMP=0x001000000003add0
+ (id)nsurlsessiondPath;	// IMP=0x001000000003ad22

@end

