//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class ACAccount, NSNumber, NSString, UnfairLock;
@protocol OS_dispatch_queue;

@interface ActiveAccountObserver : NSObject
{
    ACAccount *_account;	// 8 = 0x8
    NSString *_cachedStoreFront;	// 16 = 0x10
    NSNumber *_lockedCachedOneAccountDSID;	// 24 = 0x18
    NSObject<OS_dispatch_queue> *_dispatchQueue;	// 32 = 0x20
    UnfairLock *_lock;	// 40 = 0x28
}

+ (id)activeSandboxAccount;	// IMP=0x00200000000dbdc6
+ (id)activeAccount;	// IMP=0x00100000000dbd6f
+ (id)sharedInstance;	// IMP=0x00100000000dbab3
- (void).cxx_destruct;	// IMP=0x00200000000dd314
- (void)handleStorefrontChangedNotification:(id)arg1;	// IMP=0x00100000000dcf2b
- (void)handleAccountStoreDidChangeNotification:(id)arg1;	// IMP=0x00100000000dc4b9
- (void)handleSandboxAccountDidChangeNotification:(id)arg1;	// IMP=0x00100000000dc295
- (id)oneAccountDSIDWithLogKey:(id)arg1;	// IMP=0x00100000000dbe27
- (id)init;	// IMP=0x00100000000dbb08

@end

