//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface LaunchEventEntity
{
}

+ (Class)memoryEntityClass;	// IMP=0x00400000001b3bf7
+ (id)defaultProperties;	// IMP=0x00100000001b3b4e
+ (id)databaseTable;	// IMP=0x00100000001b3b41

@end

