//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class NSString;

@interface MigrationRequestTask
{
    NSString *_clientID;	// 8 = 0x8
}

- (void).cxx_destruct;	// IMP=0x0020000000228f90
- (void)main;	// IMP=0x0010000000228ed0

@end

