//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface MigratorMiscellaneousTask
{
}

- (void)main;	// IMP=0x0040000000146e33
- (id)migratorType;	// IMP=0x0010000000146e22
- (id)copyConfiguration;	// IMP=0x0010000000146e02
- (id)initWithConfiguration:(id)arg1;	// IMP=0x0010000000146dd3

@end

