//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSData, NSURL, _TtC9appstored6LogKey;

@interface TFPendingImageUpload : NSObject
{
    NSData *_data;	// 8 = 0x8
    _TtC9appstored6LogKey *_logKey;	// 16 = 0x10
    NSURL *_URL;	// 24 = 0x18
}

+ (_Bool)supportsSecureCoding;	// IMP=0x00200000001708f2
- (void).cxx_destruct;	// IMP=0x0020000000170a8b
- (id)initWithCoder:(id)arg1;	// IMP=0x001000000017097b
- (void)encodeWithCoder:(id)arg1;	// IMP=0x00100000001708fa
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x0010000000170891
- (_Bool)isEqual:(id)arg1;	// IMP=0x00100000001707da

@end

