//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class AKCredentialRequestContext, BSContinuousMachTimer, CDCredentialRequestBuilder, CDRequesterViewService, NSArray, RPCompanionLinkDevice;
@protocol CDAuthInfoProviding;

@interface CDRequesterAppSignInSession
{
    id <CDAuthInfoProviding> _authInfo;	// 8 = 0x8
    CDCredentialRequestBuilder *_credentialRequestBuilder;	// 16 = 0x10
    AKCredentialRequestContext *_localCredentialRequest;	// 24 = 0x18
    NSArray *_associatedDomains;	// 32 = 0x20
    CDRequesterViewService *_viewService;	// 40 = 0x28
    BSContinuousMachTimer *_sessionFinishedTimer;	// 48 = 0x30
    RPCompanionLinkDevice *_meDevice;	// 56 = 0x38
}

- (void).cxx_destruct;	// IMP=0x0020000000017ea9
- (id)_idsMessageRecipientUsernames;	// IMP=0x0010000000016089
- (id)_notifyDeviceIDSIdentifier;	// IMP=0x0010000000015ffe
- (unsigned long long)_authFlags;	// IMP=0x0010000000015f96
- (void)_sessionActivated;	// IMP=0x0010000000015f39
- (_Bool)_requireOwnerDevice;	// IMP=0x0010000000015ed6
- (id)_responseForGetNotifInfoRequest:(id)arg1;	// IMP=0x0010000000015e68
- (void)_prepareForActivationWithCompletionHandler:(CDUnknownBlockType)arg1;	// IMP=0x0010000000015a6d
- (void)_invalidated;	// IMP=0x00100000000159db
- (void)_presentViewService;	// IMP=0x00100000000156ed
- (void)_notifyDeviceStartedAuthentication:(id)arg1;	// IMP=0x0010000000015677
- (void)_notifyDeviceAcceptedNotification:(id)arg1;	// IMP=0x0010000000015601
- (unsigned char)_deviceActionType;	// IMP=0x00100000000155b0
- (void)_configureRapportClient:(id)arg1;	// IMP=0x0010000000013ff0

@end

