//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface MADMomentsDeferredBackgroundSystemTask
{
}

+ (long long)taskPriority;	// IMP=0x004000000014285a
+ (long long)taskGracePeriod;	// IMP=0x001000000014273c
+ (id)identifier;	// IMP=0x001000000014272f
+ (id)sharedTask;	// IMP=0x00100000001426a2
- (void)executeWithCancelBlock:(CDUnknownBlockType)arg1 progressHandler:(CDUnknownBlockType)arg2 completionHandler:(CDUnknownBlockType)arg3;	// IMP=0x0040000000142d54
- (void)submitTask:(id *)arg1;	// IMP=0x0010000000142984

@end

