//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class PHPhotoLibrary, VCPDatabaseWriter;

@interface MADPhotosFullClusterProcessingTask
{
    PHPhotoLibrary *_photoLibrary;	// 8 = 0x8
    VCPDatabaseWriter *_database;	// 16 = 0x10
    _Bool _requiresProgressQuery;	// 24 = 0x18
    _Bool _fullModeClusterOnly;	// 25 = 0x19
}

+ (id)taskWithPhotoLibrary:(id)arg1;	// IMP=0x0040000000154893
- (void).cxx_destruct;	// IMP=0x00200000001558e1
@property(nonatomic) _Bool fullModeClusterOnly; // @synthesize fullModeClusterOnly=_fullModeClusterOnly;
@property(nonatomic) _Bool requiresProgressQuery; // @synthesize requiresProgressQuery=_requiresProgressQuery;
- (void)process;	// IMP=0x0010000000154dd6
- (void)cacheMediaAnalysisImagePriority1Progress;	// IMP=0x0010000000154b00
- (unsigned long long)queryMediaAnalysisImagePriority1ProgressPercentage;	// IMP=0x00100000001548f0
- (id)initWithPhotoLibrary:(id)arg1;	// IMP=0x00100000001547c5

@end

