//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class VCPWatchdog;

@interface MADScopedWatchdog : NSObject
{
    VCPWatchdog *_internalWatchdog;	// 8 = 0x8
}

- (void).cxx_destruct;	// IMP=0x00200000000ea6c0
- (void)pet;	// IMP=0x00100000000ea6aa
- (void)dealloc;	// IMP=0x00100000000ea56a
- (id)init;	// IMP=0x00100000000ea37c

@end

