//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSDictionary, NSSet, NSString, TVSSAudioNowPlayingController, TVSSBluetoothRemoteController, TVSSCriticalInfoController, TVSSDoNotDisturbController, TVSSFaceTimeMenuItemProvider, TVSSHeadphonesMenuItemProvider, TVSSHomeKitController, TVSSMenuModeController, TVSSNetworkController, TVSSNowPlayingMenuItemProvider, TVSSPrivacyController, TVSSSensorActivityController, TVSSSleepTimerController, TVSSSystemOutputDeviceRouteController;
@protocol BSInvalidatable;

@interface TVSSMenuDataSourceControllerOverlord : NSObject
{
    TVSSAudioNowPlayingController *_audioNowPlayingController;	// 8 = 0x8
    TVSSBluetoothRemoteController *_bluetoothRemoteController;	// 16 = 0x10
    TVSSCriticalInfoController *_criticalInfoController;	// 24 = 0x18
    TVSSDoNotDisturbController *_doNotDisturbController;	// 32 = 0x20
    TVSSHomeKitController *_homeKitController;	// 40 = 0x28
    TVSSSensorActivityController *_sensorActivityController;	// 48 = 0x30
    TVSSSleepTimerController *_sleepTimerController;	// 56 = 0x38
    TVSSSystemOutputDeviceRouteController *_systemOutputDeviceRouteController;	// 64 = 0x40
    TVSSNetworkController *_networkController;	// 72 = 0x48
    TVSSNowPlayingMenuItemProvider *_nowPlayingMenuItemProvider;	// 80 = 0x50
    TVSSFaceTimeMenuItemProvider *_faceTimeMenuItemProvider;	// 88 = 0x58
    TVSSFaceTimeMenuItemProvider *_faceTimeAnimatingMenuItemProvider;	// 96 = 0x60
    TVSSHeadphonesMenuItemProvider *_headphonesMenuItemProvider;	// 104 = 0x68
    NSDictionary *_dataSourceControllerByMenuMode;	// 112 = 0x70
    id <BSInvalidatable> _stateCaptureHandle;	// 120 = 0x78
    TVSSMenuModeController *_menuModeController;	// 128 = 0x80
    TVSSPrivacyController *_privacyController;	// 136 = 0x88
}

- (void).cxx_destruct;	// IMP=0x002000000012e0f0
@property(readonly, nonatomic) TVSSDoNotDisturbController *doNotDisturbController; // @synthesize doNotDisturbController=_doNotDisturbController;
@property(readonly, nonatomic) TVSSPrivacyController *privacyController; // @synthesize privacyController=_privacyController;
@property(readonly, nonatomic) TVSSMenuModeController *menuModeController; // @synthesize menuModeController=_menuModeController;
@property(readonly, copy) NSString *debugDescription;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"NSString",?,R,C

@property(readonly, copy) NSString *description;
- (id)stateDumpBuilder;	// IMP=0x001000000012df50
- (id)descriptionBuilderWithMultilinePrefix:(id)arg1;	// IMP=0x001000000012de10
- (id)descriptionWithMultilinePrefix:(id)arg1;	// IMP=0x001000000012dd70
- (id)succinctDescriptionBuilder;	// IMP=0x001000000012dc00
- (id)succinctDescription;	// IMP=0x001000000012db90
- (void)_updateActiveModeAwareProviders;	// IMP=0x001000000012dad0
- (void)menuModeControllerModeDidChange:(id)arg1 withTransitionContext:(id)arg2;	// IMP=0x001000000012d900
- (id)_interactiveProviderForIdentifier:(id)arg1;	// IMP=0x001000000012d500
- (void)dismissBannerWithPresentable:(id)arg1 bannerContext:(id)arg2;	// IMP=0x001000000012d250
- (void)presentBannerWithPresentable:(id)arg1 bannerContext:(id)arg2;	// IMP=0x001000000012cfe0
- (id)controllerForMode:(unsigned long long)arg1;	// IMP=0x001000000012cf50
@property(readonly, copy, nonatomic) NSSet *controllers;
- (void)dealloc;	// IMP=0x001000000012cdc0
- (id)initWithMenuModeController:(id)arg1 privacyController:(id)arg2 doNotDisturbController:(id)arg3 nowPlayingController:(id)arg4;	// IMP=0x001000000012b5e0

// Remaining properties
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

