//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class MISSING_TYPE, NSString, PBSBulletin, TVHMBannerCameraPresentableViewController, TVSSBannerManager, UIScene, UIViewController;

@interface TVSSBannerBulletinBridgeManager : NSObject
{
    UIScene *_scene;	// 8 = 0x8
    UIViewController *_fullScreenCameraPresenterViewController;	// 16 = 0x10
    TVSSBannerManager *_bannerManager;	// 24 = 0x18
    PBSBulletin *_activeBulletin;	// 32 = 0x20
    TVHMBannerCameraPresentableViewController *_activePresentable;	// 40 = 0x28
}

- (void).cxx_destruct;	// IMP=0x002000000006bed0
@property(retain, nonatomic) TVHMBannerCameraPresentableViewController *activePresentable; // @synthesize activePresentable=_activePresentable;
@property(retain, nonatomic) PBSBulletin *activeBulletin; // @synthesize activeBulletin=_activeBulletin;
@property(retain, nonatomic) TVSSBannerManager *bannerManager; // @synthesize bannerManager=_bannerManager;
@property(nonatomic) __weak UIViewController *fullScreenCameraPresenterViewController; // @synthesize fullScreenCameraPresenterViewController=_fullScreenCameraPresenterViewController;
@property(nonatomic, getter=_scene, setter=_setScene:) __weak UIScene *_scene; // @synthesize _scene;
- (MISSING_TYPE *)_sendObservingActionWithBulletin:state:reason: /* Error: Ran out of types for this method. */;	// IMP=0x001000000006ba20
- (void)_cleanup;	// IMP=0x001000000006b9a0
- (_Bool)_isHomeUIVideoBulletin:(id)arg1;	// IMP=0x001000000006b910
- (void)_updatePresentable:(id)arg1 withBulletin:(id)arg2;	// IMP=0x001000000006b670
- (_Bool)_isSupportedBulletin:(id)arg1;	// IMP=0x001000000006b310
- (void)_handleSendBulletinAction:(id)arg1;	// IMP=0x001000000006a5c0
- (void)bannerCameraViewControllerDidDismissFullScreen:(id)arg1;	// IMP=0x001000000006a560
- (void)bannerCameraViewControllerWillPresentFullScreen:(id)arg1;	// IMP=0x001000000006a500
- (id)fullScreenPresenterForBannerCameraViewController:(id)arg1;	// IMP=0x001000000006a4a0
- (void)bannerCameraViewController:(id)arg1 needsRevocationWithReason:(id)arg2;	// IMP=0x001000000006a260
- (void)presentableWillNotAppearAsBanner:(id)arg1 withReason:(id)arg2;	// IMP=0x001000000006a090
- (void)presentableDidDisappearAsBanner:(id)arg1 withReason:(id)arg2;	// IMP=0x0010000000069ec0
- (void)presentableDidAppearAsBanner:(id)arg1;	// IMP=0x0010000000069d40
- (id)_respondToActions:(id)arg1 forFBSScene:(id)arg2 inUIScene:(id)arg3 fromTransitionContext:(id)arg4;	// IMP=0x0010000000069940
- (id)_actionRespondersForScene:(id)arg1;	// IMP=0x0010000000069660
- (id)initWithScene:(id)arg1;	// IMP=0x0010000000069420
- (id)initWithBannerManager:(id)arg1 scene:(id)arg2;	// IMP=0x0010000000068e70

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"NSString",?,R,C

@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

