//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <UIKitCore/UIViewController.h>

@class NSLayoutConstraint, NSString, NSTimer, TVSPPillView, TVSSMenuBarAnimationContext, TVSSMenuDataSourceControllerOverlord, TVSSMenuItem, TVSSMenuItemPanelHostingViewController, TVSSMenuModeController, TVSSPillContentViewProvider, TVSSPrivacyController, TVSSPrivacyStateAdapterView, TVSSPrivacyViewPixelShifter, TVSSerialTransactionManager, UIFocusGuide, UIView, _TVSSMenuBarPendingPresentableRequest;
@protocol BSInvalidatable;

@interface TVSSMenuBarViewController : UIViewController
{
    _Bool _shouldHaveInitialFocusInPanel;	// 8 = 0x8
    _Bool _moveFocusToPanel;	// 9 = 0x9
    int _token;	// 12 = 0xc
    TVSSMenuDataSourceControllerOverlord *_dataSourceControllerOverlord;	// 16 = 0x10
    TVSPPillView *_pillView;	// 24 = 0x18
    TVSSPillContentViewProvider *_contentViewProvider;	// 32 = 0x20
    TVSSMenuItemPanelHostingViewController *_panelHostingViewController;	// 40 = 0x28
    TVSSMenuItem *_activeMenuItem;	// 48 = 0x30
    _TVSSMenuBarPendingPresentableRequest *_pendingBannerPresentable;	// 56 = 0x38
    TVSSerialTransactionManager *_transactionManager;	// 64 = 0x40
    TVSSMenuModeController *_menuModeController;	// 72 = 0x48
    TVSSPrivacyController *_privacyController;	// 80 = 0x50
    TVSSPrivacyStateAdapterView *_privacyStateAdapterView;	// 88 = 0x58
    UIView *_dimmingOverlayView;	// 96 = 0x60
    TVSSPrivacyViewPixelShifter *_microphoneIndicatorPixelShifter;	// 104 = 0x68
    TVSSPrivacyViewPixelShifter *_cameraIndicatorPixelShifter;	// 112 = 0x70
    id <BSInvalidatable> _microphonePixelShifterActiveAssertion;	// 120 = 0x78
    id <BSInvalidatable> _cameraPixelShifterActiveAssertion;	// 128 = 0x80
    NSLayoutConstraint *_barTopToCenterYConstraint;	// 136 = 0x88
    NSLayoutConstraint *_privacyCenterXConstraint;	// 144 = 0x90
    NSLayoutConstraint *_privacyCenterYConstraint;	// 152 = 0x98
    UIFocusGuide *_panelExitGuide;	// 160 = 0xa0
    TVSSMenuBarAnimationContext *_currentRunningAnimationContext;	// 168 = 0xa8
    NSLayoutConstraint *_pillViewTrailingConstraint;	// 176 = 0xb0
    NSTimer *_focusActivationTimer;	// 184 = 0xb8
    id _scaledUINotificationToken;	// 192 = 0xc0
}

- (void).cxx_destruct;	// IMP=0x00200000000e4670
@property(retain, nonatomic) id scaledUINotificationToken; // @synthesize scaledUINotificationToken=_scaledUINotificationToken;
@property(retain, nonatomic) NSTimer *focusActivationTimer; // @synthesize focusActivationTimer=_focusActivationTimer;
@property(retain, nonatomic) NSLayoutConstraint *pillViewTrailingConstraint; // @synthesize pillViewTrailingConstraint=_pillViewTrailingConstraint;
@property(retain, nonatomic) TVSSMenuBarAnimationContext *currentRunningAnimationContext; // @synthesize currentRunningAnimationContext=_currentRunningAnimationContext;
@property(retain, nonatomic) UIFocusGuide *panelExitGuide; // @synthesize panelExitGuide=_panelExitGuide;
@property(retain, nonatomic) NSLayoutConstraint *privacyCenterYConstraint; // @synthesize privacyCenterYConstraint=_privacyCenterYConstraint;
@property(retain, nonatomic) NSLayoutConstraint *privacyCenterXConstraint; // @synthesize privacyCenterXConstraint=_privacyCenterXConstraint;
@property(retain, nonatomic) NSLayoutConstraint *barTopToCenterYConstraint; // @synthesize barTopToCenterYConstraint=_barTopToCenterYConstraint;
@property(retain, nonatomic) id <BSInvalidatable> cameraPixelShifterActiveAssertion; // @synthesize cameraPixelShifterActiveAssertion=_cameraPixelShifterActiveAssertion;
@property(retain, nonatomic) id <BSInvalidatable> microphonePixelShifterActiveAssertion; // @synthesize microphonePixelShifterActiveAssertion=_microphonePixelShifterActiveAssertion;
@property(retain, nonatomic) TVSSPrivacyViewPixelShifter *cameraIndicatorPixelShifter; // @synthesize cameraIndicatorPixelShifter=_cameraIndicatorPixelShifter;
@property(retain, nonatomic) TVSSPrivacyViewPixelShifter *microphoneIndicatorPixelShifter; // @synthesize microphoneIndicatorPixelShifter=_microphoneIndicatorPixelShifter;
@property(readonly, nonatomic) UIView *dimmingOverlayView; // @synthesize dimmingOverlayView=_dimmingOverlayView;
@property(readonly, nonatomic) TVSSPrivacyStateAdapterView *privacyStateAdapterView; // @synthesize privacyStateAdapterView=_privacyStateAdapterView;
@property(readonly, nonatomic) TVSSPrivacyController *privacyController; // @synthesize privacyController=_privacyController;
@property(readonly, nonatomic) TVSSMenuModeController *menuModeController; // @synthesize menuModeController=_menuModeController;
@property(retain, nonatomic) TVSSerialTransactionManager *transactionManager; // @synthesize transactionManager=_transactionManager;
@property(retain, nonatomic) _TVSSMenuBarPendingPresentableRequest *pendingBannerPresentable; // @synthesize pendingBannerPresentable=_pendingBannerPresentable;
@property(retain, nonatomic) TVSSMenuItem *activeMenuItem; // @synthesize activeMenuItem=_activeMenuItem;
@property(retain, nonatomic) TVSSMenuItemPanelHostingViewController *panelHostingViewController; // @synthesize panelHostingViewController=_panelHostingViewController;
@property(retain, nonatomic) TVSSPillContentViewProvider *contentViewProvider; // @synthesize contentViewProvider=_contentViewProvider;
@property(retain, nonatomic) TVSPPillView *pillView; // @synthesize pillView=_pillView;
@property(readonly, nonatomic) TVSSMenuDataSourceControllerOverlord *dataSourceControllerOverlord; // @synthesize dataSourceControllerOverlord=_dataSourceControllerOverlord;
- (void)privacyControllerStateDidChange:(id)arg1;	// IMP=0x00100000000e4010
- (_Bool)_shouldForceFocusToPanelDuringAnimationWithContext:(id)arg1;	// IMP=0x00100000000e3f10
- (void)_updatePrivacyStateAdapterView;	// IMP=0x00100000000e39e0
- (void)_updateBarYOffset;	// IMP=0x00100000000e3930
- (void)_updateActiveItemTraits;	// IMP=0x00100000000e3850
- (id)_initialMenuItemForTransitionContext:(id)arg1 focusInPanel:(_Bool *)arg2;	// IMP=0x00100000000e3460
- (void)_cleanUpDismissedBannerViewController:(id)arg1;	// IMP=0x00100000000e33f0
- (void)_updateWithMenuMode:(unsigned long long)arg1 previousMode:(unsigned long long)arg2 previousBannerContext:(id)arg3 activeMenuItem:(id)arg4 presentationReason:(unsigned long long)arg5 animated:(_Bool)arg6;	// IMP=0x00100000000e24f0
- (void)_moveFocusToPanel;	// IMP=0x00100000000e2490
- (void)wantsOrthogonalMoveWithFocusHeading:(unsigned long long)arg1;	// IMP=0x00100000000e2150
- (void)transactionManager:(id)arg1 didCompleteTransaction:(id)arg2;	// IMP=0x00100000000e1f50
- (_Bool)environmentAllowsFocus;	// IMP=0x00100000000e1dc0
- (void)didPerformPrimaryActionWithHostView:(id)arg1;	// IMP=0x00100000000e1d70
- (void)updateOrthogonalDelegateOfActiveMenuItem:(id)arg1;	// IMP=0x00100000000e1a50
- (void)actuallySetActiveMenuItem:(id)arg1 presentationReason:(unsigned long long)arg2 focusHeading:(unsigned long long)arg3 orthogonalNavigation:(_Bool)arg4;	// IMP=0x00100000000e1830
- (void)setActiveMenuItem:(id)arg1 presentationReason:(unsigned long long)arg2 focusHeading:(unsigned long long)arg3 orthogonalNavigation:(_Bool)arg4;	// IMP=0x00100000000e1470
- (void)setActiveMenuItem:(id)arg1 presentationReason:(unsigned long long)arg2 focusHeading:(unsigned long long)arg3;	// IMP=0x00100000000e13f0
- (void)setActiveMenuItem:(id)arg1 presentationReason:(unsigned long long)arg2;	// IMP=0x00100000000e1380
- (void)pixelShifter:(id)arg1 didUpdateOffset:(struct CGPoint)arg2;	// IMP=0x00100000000e12c0
- (void)menuModeControllerModeDidChange:(id)arg1 withTransitionContext:(id)arg2;	// IMP=0x00100000000e1120
- (id)pillContentViewWantsUpdateContext;	// IMP=0x00100000000e1050
- (void)pillContentViewProviderWillUpdateCurrentContentView:(id)arg1;	// IMP=0x00100000000e0c90
- (void)pillContentViewConfigurationWillChange:(id)arg1;	// IMP=0x00100000000e0bc0
- (struct CGSize)sizeForChildContentContainer:(id)arg1 withParentContainerSize:(struct CGSize)arg2;	// IMP=0x00100000000e0990
- (void)didUpdateFocusInContext:(id)arg1 withAnimationCoordinator:(id)arg2;	// IMP=0x00100000000e06f0
- (id)preferredFocusEnvironments;	// IMP=0x00100000000e0570
- (void)viewDidLoad;	// IMP=0x00100000000deb10
- (void)dealloc;	// IMP=0x00100000000de910
- (id)initWithDataSourceControllerOverlord:(id)arg1;	// IMP=0x00100000000de260

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"NSString",?,R,C

@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

