//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <TVSystemPanelUI/TVSPPlatterViewController.h>

@class MISSING_TYPE, TVSSAudioNowPlayingController, TVSSNowPlayingPanelPlatterController;

@interface TVSSNowPlayingPanelViewController : TVSPPlatterViewController
{
    MISSING_TYPE *_platterController;	// 8 = 0x8
    TVSSAudioNowPlayingController *_audioNowPlayingController;	// 16 = 0x10
}

- (void).cxx_destruct;	// IMP=0x00200000000043e0
@property(readonly, nonatomic) TVSSAudioNowPlayingController *audioNowPlayingController; // @synthesize audioNowPlayingController=_audioNowPlayingController;
@property(readonly, nonatomic) TVSSNowPlayingPanelPlatterController *platterController; // @synthesize platterController=_platterController;
- (id)initWithAudioNowPlayingController:(id)arg1;	// IMP=0x00100000000042a0

@end

