//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class NSTimer, TVSSHUDTimeIntervalVisualization, UILabel;

@interface TVSSHUDTimeIntervalVisualizationView
{
    UILabel *_titleAndTimeLabel;	// 16 = 0x10
    NSTimer *_timer;	// 24 = 0x18
}

- (void).cxx_destruct;	// IMP=0x0020000000006960
- (void)_updateTitleAndTimeLabel;	// IMP=0x00100000000067d0
- (void)_timerTick;	// IMP=0x00100000000067a0
- (void)_cleanupTimer;	// IMP=0x0010000000006740
- (void)_setupTimer;	// IMP=0x00100000000065b0
- (void)_updateTimer;	// IMP=0x00100000000063d0
- (void)dealloc;	// IMP=0x0010000000006360
- (void)visualizationDidUpdate;	// IMP=0x0010000000006320
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x00100000000061c0

// Remaining properties
@property(retain, nonatomic) TVSSHUDTimeIntervalVisualization *visualization; // @dynamic visualization;

@end

