//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSOrderedSet, NSString;

@interface TVSSMenuDataSource : NSObject
{
    NSOrderedSet *_items;	// 8 = 0x8
}

- (void).cxx_destruct;	// IMP=0x002000000010b530
@property(readonly, copy, nonatomic) NSOrderedSet *items; // @synthesize items=_items;
@property(readonly, copy) NSString *debugDescription;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"NSString",?,R,C

@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
- (_Bool)isEqual:(id)arg1;	// IMP=0x001000000010b220
- (id)descriptionBuilderWithMultilinePrefix:(id)arg1;	// IMP=0x001000000010b0e0
- (id)descriptionWithMultilinePrefix:(id)arg1;	// IMP=0x001000000010b040
- (id)succinctDescriptionBuilder;	// IMP=0x001000000010aed0
- (id)succinctDescription;	// IMP=0x001000000010ae60
- (id)initWithItems:(id)arg1;	// IMP=0x001000000010ad90
- (id)init;	// IMP=0x001000000010ad00

// Remaining properties
@property(readonly) Class superclass;

@end

