//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class NSString, TVSSFaceTimePlatterBackingStore;
@protocol BSInvalidatable, TVSSMenuModeStateContributingDelegate;

@interface TVSSFaceTimeMenuItemProvider
{
    _Bool _privacyPlusMode;	// 8 = 0x8
    id <BSInvalidatable> _stateCaptureHandle;	// 16 = 0x10
    id <TVSSMenuModeStateContributingDelegate> contributorDelegate;	// 24 = 0x18
    NSString *_cachedPlatterState;	// 32 = 0x20
    TVSSFaceTimePlatterBackingStore *_backingStore;	// 40 = 0x28
}

- (void).cxx_destruct;	// IMP=0x0020000000085310
@property(readonly, nonatomic) TVSSFaceTimePlatterBackingStore *backingStore; // @synthesize backingStore=_backingStore;
@property(retain, nonatomic) NSString *cachedPlatterState; // @synthesize cachedPlatterState=_cachedPlatterState;
@property(nonatomic) __weak id <TVSSMenuModeStateContributingDelegate> contributorDelegate; // @synthesize contributorDelegate;
- (id)stateDumpBuilder;	// IMP=0x0010000000085110
- (void)updateMenuModeState:(id)arg1;	// IMP=0x0010000000085090
- (id)_currentItemContent;	// IMP=0x0010000000084940
- (_Bool)_isSharePlayIconForState:(id)arg1;	// IMP=0x0010000000084820
- (_Bool)updateVisualContentForMenuItem:(id)arg1;	// IMP=0x0010000000084790
- (id)log;	// IMP=0x0010000000084770
- (id)newMenuItem;	// IMP=0x0010000000084660
- (_Bool)shouldShowMenuItem;	// IMP=0x0010000000084620
- (void)faceTimePlatterBackingStoreDidChange:(id)arg1;	// IMP=0x0010000000084590
- (void)updateFromPlatterState:(id)arg1;	// IMP=0x0010000000084020
- (void)dealloc;	// IMP=0x0010000000083fc0
- (id)initForPrivacyPlus:(_Bool)arg1;	// IMP=0x0010000000083bf0

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"NSString",?,R,C

@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

