//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@interface TVSSMenuPresentationContext : NSObject
{
    unsigned long long _reason;	// 8 = 0x8
}

- (_Bool)isEqual:(id)arg1;	// IMP=0x00200000000ffd20
@property(readonly, nonatomic) unsigned long long reason;
- (id)mutableCopyWithZone:(struct _NSZone *)arg1;	// IMP=0x00100000000ffcc0
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x00100000000ffca0
- (id)initWithPresentationContext:(id)arg1;	// IMP=0x00100000000ffbd0

@end

