//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class GTServiceConnection, NSSet;

@interface GTLoopbackServiceXPCProxy : NSObject
{
    GTServiceConnection *_connection;	// 8 = 0x8
    NSSet *_ignoreMethods;	// 16 = 0x10
}

- (void).cxx_destruct;	// IMP=0x00200000000140de
- (void)echo:(id)arg1 repeat:(unsigned long long)arg2 callback:(CDUnknownBlockType)arg3 complete:(CDUnknownBlockType)arg4;	// IMP=0x0010000000013e9a
- (void)echo:(id)arg1 repeat:(unsigned long long)arg2 callback:(CDUnknownBlockType)arg3;	// IMP=0x0010000000013d7f
- (void)echo:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;	// IMP=0x0010000000013c3b
- (id)echo:(id)arg1;	// IMP=0x0010000000013b83
- (_Bool)respondsToSelector:(SEL)arg1;	// IMP=0x0010000000013afe
- (id)initWithConnection:(id)arg1 remoteProperties:(id)arg2;	// IMP=0x00100000000139b5

@end

