//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <ProtocolBuffer/PBCodable.h>

@class NSString;

@interface ALSMeta : PBCodable
{
    NSString *_productId;	// 8 = 0x8
    NSString *_softwareBuild;	// 16 = 0x10
}

@property(retain, nonatomic) NSString *productId; // @synthesize productId=_productId;
@property(retain, nonatomic) NSString *softwareBuild; // @synthesize softwareBuild=_softwareBuild;
- (void)mergeFrom:(id)arg1;	// IMP=0x0010000000dcdf01
- (unsigned long long)hash;	// IMP=0x0010000000dcdeb4
- (_Bool)isEqual:(id)arg1;	// IMP=0x0010000000dcde32
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x0010000000dcdd8f
- (void)copyTo:(id)arg1;	// IMP=0x0010000000dcdd39
- (void)writeTo:(id)arg1;	// IMP=0x0010000000dcdce9
- (_Bool)readFrom:(id)arg1;	// IMP=0x0010000000dcdcdc
- (id)dictionaryRepresentation;	// IMP=0x0010000000dcdae1
- (id)description;	// IMP=0x0010000000dcda6a
@property(readonly, nonatomic) _Bool hasProductId;
@property(readonly, nonatomic) _Bool hasSoftwareBuild;
- (void)dealloc;	// IMP=0x0010000000dcd9e9

@end

