//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class NSString;

@interface CLBTLEBeaconProviderMockAdapter
{
}

+ (id)getSilo;	// IMP=0x0020000000e8974e
+ (void)performSyncOnSilo:(id)arg1 invoker:(CDUnknownBlockType)arg2;	// IMP=0x0010000000e89735
+ (void)becameFatallyBlocked:(id)arg1 index:(unsigned long long)arg2;	// IMP=0x0010000000e896d8
- (void)requestScan:(double)arg1;	// IMP=0x0020000000e89b55
- (void)addProximityScanEvent:(CDUnknownBlockType)arg1;	// IMP=0x0010000000e89a95
- (void)addProximityZoneEvent:(CDUnknownBlockType)arg1;	// IMP=0x0010000000e89962
- (_Bool)syncgetDoSync:(CDUnknownBlockType)arg1;	// IMP=0x0010000000e8993a
- (void)doAsync:(CDUnknownBlockType)arg1 withReply:(CDUnknownBlockType)arg2;	// IMP=0x0010000000e8990d
- (void)doAsync:(CDUnknownBlockType)arg1;	// IMP=0x0010000000e898e5
- (void *)adaptee;	// IMP=0x0010000000e898b2
- (void)endService;	// IMP=0x0010000000e89897
- (void)beginService;	// IMP=0x0010000000e897e7
- (id)init;	// IMP=0x0010000000e897aa

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"NSString",?,R,C

@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@property(nonatomic) _Bool valid;

@end

