//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class NSString;

@interface CLCatherineNotifierAdapter
{
}

+ (id)getSilo;	// IMP=0x00200000006ccd2a
+ (void)performSyncOnSilo:(id)arg1 invoker:(CDUnknownBlockType)arg2;	// IMP=0x00100000006ccd11
+ (void)becameFatallyBlocked:(id)arg1 index:(unsigned long long)arg2;	// IMP=0x00100000006cccb4
+ (_Bool)isSupported;	// IMP=0x00100000006ccf3e
- (_Bool)syncgetDoSync:(CDUnknownBlockType)arg1;	// IMP=0x00200000006ccf16
- (void)doAsync:(CDUnknownBlockType)arg1 withReply:(CDUnknownBlockType)arg2;	// IMP=0x00100000006ccee9
- (void)doAsync:(CDUnknownBlockType)arg1;	// IMP=0x00100000006ccec1
- (void *)adaptee;	// IMP=0x00100000006cce8e
- (void)endService;	// IMP=0x00100000006cce73
- (void)beginService;	// IMP=0x00100000006ccdc3
- (id)init;	// IMP=0x00100000006ccd86

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"NSString",?,R,C

@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@property(nonatomic) _Bool valid;

@end

