//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSDate, NSOutputStream, NSString;
@protocol OS_dispatch_queue;

@interface CLFallLogger : NSObject
{
    NSObject<OS_dispatch_queue> *fQueue;	// 8 = 0x8
    NSString *fLogDirectory;	// 16 = 0x10
    NSString *fLogFilePrefix;	// 24 = 0x18
    long long fRotation;	// 32 = 0x20
    NSOutputStream *fOutputStream;	// 40 = 0x28
    long long fHour;	// 48 = 0x30
    NSDate *fDate;	// 56 = 0x38
}

- (void)logData:(id)arg1;	// IMP=0x0020000000efefb7
- (id)_outputStream;	// IMP=0x0010000000efe9bc
- (void)flushInMemoryDataWithCompletionQueue:(id)arg1 completionBlock:(CDUnknownBlockType)arg2;	// IMP=0x0010000000efe8bb
- (void)flushToFile;	// IMP=0x0010000000efe834
- (void)clearLogs;	// IMP=0x0010000000efe789
- (void)stopLogging;	// IMP=0x0010000000efe728
- (_Bool)_shouldRotateToHour:(long long *)arg1 date:(id *)arg2;	// IMP=0x0010000000efe660
- (_Bool)_shouldRotate;	// IMP=0x0010000000efe64a
- (void)_stopLoggingOnQueue;	// IMP=0x0010000000efe606
- (id)currentFilename;	// IMP=0x0010000000efe4e6
- (id)_currentFilename;	// IMP=0x0010000000efe41d
- (id)logDirectory;	// IMP=0x0010000000efe413
- (void)dealloc;	// IMP=0x0010000000efe3b3
- (id)initToDirectory:(id)arg1 prefix:(id)arg2 rotation:(long long)arg3;	// IMP=0x0010000000efe356
- (id)init;	// IMP=0x0010000000efe308

@end

