//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@interface CLFallMslSink : NSObject
{
    struct list<CMMsl::Item *, std::allocator<CMMsl::Item *>> fOrderedSample;	// 8 = 0x8
    struct ImpactEvent fImpactEvent;	// 32 = 0x20
    _Bool fIncludeDerivedFeatures;	// 223 = 0xdf
}

- (id).cxx_construct;	// IMP=0x002000000096948e
- (void).cxx_destruct;	// IMP=0x0010000000969480
- (void)cleanUp;	// IMP=0x001000000096946c
- (void)cleanUpIncludingDerivedFeatures:(_Bool)arg1;	// IMP=0x0010000000969378
- (void)sendData:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x0010000000968d6b
- (void)logOdometer:(const struct OdometerEntry *)arg1;	// IMP=0x0010000000968ade
- (void)logSuppressionFeartures:(const FalsePositiveSuppressionFeatures_8c0e6519 *)arg1;	// IMP=0x0010000000968946
- (void)logFallStats:(const struct ImpactEvent *)arg1;	// IMP=0x0010000000968362
- (void)logFallState:(const struct ImpactEvent *)arg1;	// IMP=0x0010000000968204
- (void)logWristState:(const struct WristState *)arg1;	// IMP=0x00100000009680fd
- (void)logHeartRate:(const struct CLCatherineData *)arg1;	// IMP=0x0010000000967f97
- (void)logPressure:(const Pressure_df92a120 *)arg1;	// IMP=0x0010000000967eb3
- (void)logFilteredPressure:(const FilteredPressure_e74e912d *)arg1;	// IMP=0x0010000000967dcf
- (void)logDeviceMotion:(const struct ImpactData *)arg1;	// IMP=0x0010000000967cac
- (void)logGyro200:(const struct ImpactData *)arg1;	// IMP=0x0010000000967bab
- (void)logGyro100:(id)arg1 startTime:(double)arg2 timestamp:(unsigned long long)arg3;	// IMP=0x00100000009679c8
- (void)logHgal:(const struct ImpactData *)arg1;	// IMP=0x00100000009678ce
- (void)logAccel800:(const struct ImpactData *)arg1;	// IMP=0x00100000009677d1
- (void)logAccel100:(id)arg1 startTime:(double)arg2 timestamp:(unsigned long long)arg3;	// IMP=0x00100000009675f2
- (void)dealloc;	// IMP=0x00100000009675b4
- (id)initInUniverse:(id)arg1;	// IMP=0x0010000000967579
- (void)_insertSample:(void *)arg1;	// IMP=0x0010000000967326

@end

