//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class NSString;

@interface CLGyroCalibrationDatabaseLocationdAdapter
{
}

+ (_Bool)isSupported;	// IMP=0x002000000033480f
+ (id)getSilo;	// IMP=0x001000000033465a
+ (void)performSyncOnSilo:(id)arg1 invoker:(CDUnknownBlockType)arg2;	// IMP=0x0010000000334641
+ (void)becameFatallyBlocked:(id)arg1 index:(unsigned long long)arg2;	// IMP=0x00100000003345e4
- (int)syncgetNumTemperatures;	// IMP=0x0020000000334b20
- (_Bool)syncgetWipeDatabase;	// IMP=0x0010000000334b02
- (void)dumpDatabase:(id)arg1 onCompletion:(CDUnknownBlockType)arg2;	// IMP=0x0010000000334ac9
- (_Bool)syncgetInsertWithBias:(const CDStruct_869f9c67 *)arg1 variance:(const CDStruct_869f9c67 *)arg2 temperature:(float)arg3 timestamp:(double)arg4;	// IMP=0x0010000000334a7a
- (double)syncgetLastMiniCalibration;	// IMP=0x0010000000334a42
- (_Bool)syncgetSupportsMiniCalibration;	// IMP=0x0010000000334a24
- (int)syncgetNonFactoryRoundCount;	// IMP=0x0010000000334a06
- (void)getBiasFitWithReply:(CDUnknownBlockType)arg1;	// IMP=0x0010000000334973
- (_Bool)syncgetBiasFit:(CDStruct_6fc73bc8 *)arg1;	// IMP=0x0010000000334945
- (void)startFactoryGYTT;	// IMP=0x0010000000334927
- (int)syncgetMaxDynamicTemperature;	// IMP=0x0010000000334909
- (_Bool)syncgetGyroStatsWithBias:(CDStruct_869f9c67 *)arg1 slope:(CDStruct_869f9c67 *)arg2 l2Error:(CDStruct_869f9c67 *)arg3 isDynamic:(_Bool)arg4 deltaBias:(CDStruct_869f9c67 *)arg5 deltaSlope:(CDStruct_869f9c67 *)arg6 deltaError:(CDStruct_869f9c67 *)arg7 isDeltaDynamic:(_Bool)arg8;	// IMP=0x0010000000334851
- (_Bool)syncgetDoSync:(CDUnknownBlockType)arg1;	// IMP=0x00100000003347e7
- (void)doAsync:(CDUnknownBlockType)arg1 withReply:(CDUnknownBlockType)arg2;	// IMP=0x00100000003347ba
- (void)doAsync:(CDUnknownBlockType)arg1;	// IMP=0x0010000000334792
- (void *)adaptee;	// IMP=0x001000000033475f
- (void)endService;	// IMP=0x0010000000334744
- (void)beginService;	// IMP=0x00100000003346f3
- (id)init;	// IMP=0x00100000003346b6

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"NSString",?,R,C

@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@property(nonatomic) _Bool valid;

@end

