//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class NSString;

@interface CLKappaNotifierAdapter
{
}

+ (_Bool)isSupported;	// IMP=0x002000000100b46f
+ (id)getSilo;	// IMP=0x001000000100b2ba
+ (void)performSyncOnSilo:(id)arg1 invoker:(CDUnknownBlockType)arg2;	// IMP=0x001000000100b2a1
+ (void)becameFatallyBlocked:(id)arg1 index:(unsigned long long)arg2;	// IMP=0x001000000100b244
- (_Bool)syncgetDoSync:(CDUnknownBlockType)arg1;	// IMP=0x002000000100b447
- (void)doAsync:(CDUnknownBlockType)arg1 withReply:(CDUnknownBlockType)arg2;	// IMP=0x000000000100b41a
- (void)doAsync:(CDUnknownBlockType)arg1;	// IMP=0x001000000100b3f2
- (void *)adaptee;	// IMP=0x001000000100b3bf
- (void)endService;	// IMP=0x001000000100b3a4
- (void)beginService;	// IMP=0x001000000100b353
- (id)init;	// IMP=0x001000000100b316
- (void)forceTriggerIgneous:(id)arg1;	// IMP=0x001000000100a936
- (void)shouldLockoutNilr:(_Bool)arg1;	// IMP=0x001000000100a930
- (void)emergencyStateChange:(CDUnknownBlockType)arg1;	// IMP=0x001000000100a6cb
- (void)emergencySettingsChange:(CDUnknownBlockType)arg1 withReason:(int)arg2;	// IMP=0x001000000100a6c5
- (int)syncgetKappaState;	// IMP=0x001000000100a664
- (void)forceTrigger;	// IMP=0x001000000100a5fe
- (void)stopDem;	// IMP=0x001000000100a456
- (void)startDem;	// IMP=0x001000000100a2ab
- (void)forceCompanionHeartbeat;	// IMP=0x001000000100a291
- (void)companionHeartbeat:(id)arg1;	// IMP=0x001000000100a0e4
- (void)remoteTimeout;	// IMP=0x001000000100a0ca
- (void)dontcollect:(struct OverrideClient)arg1 isLocal:(_Bool)arg2;	// IMP=0x0010000001009dc5
- (void)collect:(struct OverrideClient)arg1 isLocal:(_Bool)arg2;	// IMP=0x0010000001009ac0
- (void)simulateTriggerWithDelay:(int)arg1 forMode:(unsigned char)arg2;	// IMP=0x0010000001009819
- (void)simulateTriggerWithDelay:(int)arg1;	// IMP=0x0010000001009802

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"NSString",?,R,C

@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@property(nonatomic) _Bool valid;

@end

