//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class MISSING_TYPE, NSString;

@interface CLNoMovementServiceClient : NSObject
{
    struct CLNoMovementSubscription *_subscription;	// 8 = 0x8
    _Bool _valid;	// 16 = 0x10
}

@property(nonatomic) _Bool valid; // @synthesize valid=_valid;
- (void)invalidate;	// IMP=0x00100000009e8819
- (MISSING_TYPE *)onStateUpdate: /* Error: Ran out of types for this method. */;	// IMP=0x00100000009e843f
- (id)initWithSubscription:(struct CLNoMovementSubscription *)arg1;	// IMP=0x00100000009e83fe

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"NSString",?,R,C

@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

