//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class NSString;

@interface CLSkiNotifierAdapter
{
}

+ (id)getSilo;	// IMP=0x0020000000a511c0
+ (void)performSyncOnSilo:(id)arg1 invoker:(CDUnknownBlockType)arg2;	// IMP=0x0010000000a511a7
+ (void)becameFatallyBlocked:(id)arg1 index:(unsigned long long)arg2;	// IMP=0x0010000000a5114a
+ (_Bool)isSupported;	// IMP=0x0010000000a51482
- (void)queryUsingRecord:(struct CLSkiEntry)arg1 withReply:(CDUnknownBlockType)arg2;	// IMP=0x0020000000a51375
- (_Bool)syncgetDoSync:(CDUnknownBlockType)arg1;	// IMP=0x0010000000a5134d
- (void)doAsync:(CDUnknownBlockType)arg1 withReply:(CDUnknownBlockType)arg2;	// IMP=0x0010000000a51320
- (void)doAsync:(CDUnknownBlockType)arg1;	// IMP=0x0010000000a512f8
- (void *)adaptee;	// IMP=0x0010000000a512c5
- (void)endService;	// IMP=0x0010000000a512aa
- (void)beginService;	// IMP=0x0010000000a51259
- (id)init;	// IMP=0x0010000000a5121c

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"NSString",?,R,C

@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@property(nonatomic) _Bool valid;

@end

