//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface CMPedometerTableRawSpeedToKValue
{
}

+ (id)sharedInstance;	// IMP=0x0040000000c38e65
- (_Bool)isRawSpeedRun:(double)arg1;	// IMP=0x0040000000c39a68
- (_Bool)isRawSpeedValid:(double)arg1;	// IMP=0x0010000000c39a56
- (double)kValueForRawSpeed:(double)arg1;	// IMP=0x0010000000c39a44
- (CDStruct_2c43369c)binIntervalForRawSpeed:(double)arg1;	// IMP=0x0010000000c39a32
- (_Bool)isRunCalibrationAvailable;	// IMP=0x0010000000c39a20
- (_Bool)isWalkCalibrationAvailable;	// IMP=0x0010000000c39a0e
- (void)updateBinsWithTrack:(id)arg1;	// IMP=0x0010000000c395d6
- (void)binsDidChange;	// IMP=0x0010000000c39560
- (void)logBins;	// IMP=0x0010000000c390c6
- (id)initWithTestMode:(_Bool)arg1;	// IMP=0x0010000000c38ebc
- (_Bool)isBinaryLogging;	// IMP=0x0010000000c38df7

@end

