//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSArray, NSString, PBSDisplayMode, TSKMappingFormatter, TVSettingsDisplayAssistantActionInfo;

@interface TVSettingsDisplayModeFacade : NSObject
{
    PBSDisplayMode *_cachedCurrentDisplayMode;	// 8 = 0x8
    NSArray *_cachedSortedDisplayModes;	// 16 = 0x10
    NSArray *_cachedUnverifiedDisplayModes;	// 24 = 0x18
    _Bool _cachedCanHandleHighBandwidthModes;	// 32 = 0x20
    _Bool _cachedShouldModeSwitchForDynamicRange;	// 33 = 0x21
    _Bool _cachedShouldModeSwitchForFrameRate;	// 34 = 0x22
    NSString *_cachedDisplaySizeIdentifier;	// 40 = 0x28
    _Bool _shouldModeSwitchForDynamicRange;	// 48 = 0x30
    _Bool _shouldModeSwitchForFrameRate;	// 49 = 0x31
    PBSDisplayMode *_selectedSDRColorMappingMode;	// 56 = 0x38
    NSArray *_userVisibleSDRColorMappingModes;	// 64 = 0x40
    PBSDisplayMode *_selectedSDRChromaMode;	// 72 = 0x48
    NSArray *_userVisibleSDRChromaModes;	// 80 = 0x50
    PBSDisplayMode *_selectedHDRChromaMode;	// 88 = 0x58
    NSArray *_userVisibleHDRChromaModes;	// 96 = 0x60
    NSArray *_commonResolutionsModes60Hz;	// 104 = 0x68
    NSArray *_commonResolutionsModes50Hz;	// 112 = 0x70
    NSArray *_commonResolutionsModesOthers;	// 120 = 0x78
    NSArray *_otherResolutionsModes60Hz;	// 128 = 0x80
    NSArray *_otherResolutionsModesExact60Hz;	// 136 = 0x88
    NSArray *_otherResolutionsModes30Hz;	// 144 = 0x90
    NSArray *_otherResolutionsModesExact30Hz;	// 152 = 0x98
    NSArray *_otherResolutionsModes24Hz;	// 160 = 0xa0
    NSArray *_otherResolutionsModesExact24Hz;	// 168 = 0xa8
    NSArray *_otherResolutionsModes50Hz;	// 176 = 0xb0
    NSArray *_otherResolutionsModes25Hz;	// 184 = 0xb8
    NSArray *_otherResolutionsModesOthers;	// 192 = 0xc0
    NSArray *_userVisibleSortedDisplayModes;	// 200 = 0xc8
    NSArray *_unverifiedDisplayModes;	// 208 = 0xd0
    TSKMappingFormatter *_dynamicRangeOptionFormatter;	// 216 = 0xd8
    TSKMappingFormatter *_dynamicRangeDescriptionFormatter;	// 224 = 0xe0
    TSKMappingFormatter *_frameRateOptionFormatter;	// 232 = 0xe8
    TSKMappingFormatter *_frameRateDescriptionFormatter;	// 240 = 0xf0
    TSKMappingFormatter *_preferredDisplaySizeOptionFormatter;	// 248 = 0xf8
    TSKMappingFormatter *_preferredDisplaySizeDescriptionFormatter;	// 256 = 0x100
    NSString *_localizedCurrentSettings;	// 264 = 0x108
}

+ (_Bool)automaticallyNotifiesObserversForKey:(id)arg1;	// IMP=0x00200000000aa40c
+ (id)sharedInstance;	// IMP=0x00100000000a6e4d
- (void).cxx_destruct;	// IMP=0x00200000000aa88c
@property(nonatomic) _Bool shouldModeSwitchForFrameRate; // @synthesize shouldModeSwitchForFrameRate=_shouldModeSwitchForFrameRate;
@property(nonatomic) _Bool shouldModeSwitchForDynamicRange; // @synthesize shouldModeSwitchForDynamicRange=_shouldModeSwitchForDynamicRange;
@property(readonly, nonatomic) NSString *localizedCurrentSettings; // @synthesize localizedCurrentSettings=_localizedCurrentSettings;
@property(retain, nonatomic) TSKMappingFormatter *preferredDisplaySizeDescriptionFormatter; // @synthesize preferredDisplaySizeDescriptionFormatter=_preferredDisplaySizeDescriptionFormatter;
@property(retain, nonatomic) TSKMappingFormatter *preferredDisplaySizeOptionFormatter; // @synthesize preferredDisplaySizeOptionFormatter=_preferredDisplaySizeOptionFormatter;
@property(retain, nonatomic) TSKMappingFormatter *frameRateDescriptionFormatter; // @synthesize frameRateDescriptionFormatter=_frameRateDescriptionFormatter;
@property(retain, nonatomic) TSKMappingFormatter *frameRateOptionFormatter; // @synthesize frameRateOptionFormatter=_frameRateOptionFormatter;
@property(retain, nonatomic) TSKMappingFormatter *dynamicRangeDescriptionFormatter; // @synthesize dynamicRangeDescriptionFormatter=_dynamicRangeDescriptionFormatter;
@property(retain, nonatomic) TSKMappingFormatter *dynamicRangeOptionFormatter; // @synthesize dynamicRangeOptionFormatter=_dynamicRangeOptionFormatter;
@property(retain, nonatomic) NSArray *unverifiedDisplayModes; // @synthesize unverifiedDisplayModes=_unverifiedDisplayModes;
@property(retain, nonatomic) NSArray *userVisibleSortedDisplayModes; // @synthesize userVisibleSortedDisplayModes=_userVisibleSortedDisplayModes;
@property(retain, nonatomic) NSArray *otherResolutionsModesOthers; // @synthesize otherResolutionsModesOthers=_otherResolutionsModesOthers;
@property(retain, nonatomic) NSArray *otherResolutionsModes25Hz; // @synthesize otherResolutionsModes25Hz=_otherResolutionsModes25Hz;
@property(retain, nonatomic) NSArray *otherResolutionsModes50Hz; // @synthesize otherResolutionsModes50Hz=_otherResolutionsModes50Hz;
@property(retain, nonatomic) NSArray *otherResolutionsModesExact24Hz; // @synthesize otherResolutionsModesExact24Hz=_otherResolutionsModesExact24Hz;
@property(retain, nonatomic) NSArray *otherResolutionsModes24Hz; // @synthesize otherResolutionsModes24Hz=_otherResolutionsModes24Hz;
@property(retain, nonatomic) NSArray *otherResolutionsModesExact30Hz; // @synthesize otherResolutionsModesExact30Hz=_otherResolutionsModesExact30Hz;
@property(retain, nonatomic) NSArray *otherResolutionsModes30Hz; // @synthesize otherResolutionsModes30Hz=_otherResolutionsModes30Hz;
@property(retain, nonatomic) NSArray *otherResolutionsModesExact60Hz; // @synthesize otherResolutionsModesExact60Hz=_otherResolutionsModesExact60Hz;
@property(retain, nonatomic) NSArray *otherResolutionsModes60Hz; // @synthesize otherResolutionsModes60Hz=_otherResolutionsModes60Hz;
@property(retain, nonatomic) NSArray *commonResolutionsModesOthers; // @synthesize commonResolutionsModesOthers=_commonResolutionsModesOthers;
@property(retain, nonatomic) NSArray *commonResolutionsModes50Hz; // @synthesize commonResolutionsModes50Hz=_commonResolutionsModes50Hz;
@property(retain, nonatomic) NSArray *commonResolutionsModes60Hz; // @synthesize commonResolutionsModes60Hz=_commonResolutionsModes60Hz;
@property(retain, nonatomic) NSArray *userVisibleHDRChromaModes; // @synthesize userVisibleHDRChromaModes=_userVisibleHDRChromaModes;
@property(retain, nonatomic) PBSDisplayMode *selectedHDRChromaMode; // @synthesize selectedHDRChromaMode=_selectedHDRChromaMode;
@property(retain, nonatomic) NSArray *userVisibleSDRChromaModes; // @synthesize userVisibleSDRChromaModes=_userVisibleSDRChromaModes;
@property(retain, nonatomic) PBSDisplayMode *selectedSDRChromaMode; // @synthesize selectedSDRChromaMode=_selectedSDRChromaMode;
@property(retain, nonatomic) NSArray *userVisibleSDRColorMappingModes; // @synthesize userVisibleSDRColorMappingModes=_userVisibleSDRColorMappingModes;
@property(retain, nonatomic) PBSDisplayMode *selectedSDRColorMappingMode; // @synthesize selectedSDRColorMappingMode=_selectedSDRColorMappingMode;
- (void)displayState:(id)arg1 didChangeWithConnection:(long long)arg2;	// IMP=0x00100000000aa19f
- (void)_reloadDataFromCache;	// IMP=0x00100000000a9f9c
- (id)_sortedDisplayModesForUserPresentation:(id)arg1;	// IMP=0x00100000000a9346
- (void)presentCableCheckDisplayAssistant;	// IMP=0x00100000000a92c2
- (void)presentUpgradeAttemptDisplayAssistant;	// IMP=0x00100000000a922c
- (void)resetVideoSettingsWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x00100000000a90fb
- (void)updateDisplayManagerWithDisplayMode:(id)arg1 reason:(id)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x00100000000a90c5
- (void)updateDisplayManagerWithDisplayMode:(id)arg1 reason:(id)arg2 requestConfiguration:(CDUnknownBlockType)arg3 completion:(CDUnknownBlockType)arg4;	// IMP=0x00000000000a8ee8
- (void)_enumerateValidColorModesFromSortedModes:(id)arg1 existingFiltering:(id)arg2 withBlock:(CDUnknownBlockType)arg3;	// IMP=0x00100000000a895a
@property(readonly, nonatomic) TVSettingsDisplayAssistantActionInfo *displayAssistantActionInfo;
- (_Bool)shouldShowDisplayAssistant;	// IMP=0x00100000000a875f
@property(readonly, nonatomic) NSArray *preferredDisplaySizeOptions;
@property(retain, nonatomic) NSString *preferredDisplaySizeIdentifier;
@property(readonly, nonatomic) NSArray *frameRateOptions;
@property(nonatomic) unsigned long long preferredFrameRate;
@property(readonly, nonatomic) NSArray *dynamicRangeOptions;
@property(nonatomic) unsigned long long preferredDynamicRange;
- (id)_recalculatedUnverifiedModes;	// IMP=0x00100000000a7b4e
- (id)_recalculatedUserVisibleHDRChromaModes;	// IMP=0x00100000000a7867
- (id)_recalculatedUserVisibleSDRChromaModes;	// IMP=0x00100000000a7564
- (id)_recalculatedUserVisibleSDRColorMappingModes;	// IMP=0x00100000000a70d8
- (void)dealloc;	// IMP=0x00100000000a7047
- (id)init;	// IMP=0x00100000000a6ed2

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"NSString",?,R,C

@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

