//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <UIKitCore/UIViewController.h>

@class NSArray, TVPhotoCollection, TVSettingsDeckImageView;

@interface TVSettingsPhotoCollectionPreviewViewController : UIViewController
{
    TVSettingsDeckImageView *_deckImageView;	// 8 = 0x8
    NSArray *_assetImageProxies;	// 16 = 0x10
    TVPhotoCollection *_photoCollection;	// 24 = 0x18
}

- (void).cxx_destruct;	// IMP=0x00200000000dbfbd
@property(retain, nonatomic) TVPhotoCollection *photoCollection; // @synthesize photoCollection=_photoCollection;
- (void)_updateViewWithImageProxies:(id)arg1 inCollection:(id)arg2;	// IMP=0x00100000000dbf1d
- (void)viewDidLayoutSubviews;	// IMP=0x00100000000dba1a
- (void)loadView;	// IMP=0x00100000000db965

@end

