//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface TVSettingsSiriAccessFacade
{
}

+ (id)sharedInstance;	// IMP=0x00400000000bdae2
- (_Bool)setAllowAccess:(_Bool)arg1 forInfo:(id)arg2;	// IMP=0x00400000000be287
- (id)fetchEnabledAppIds;	// IMP=0x00100000000be05a
- (id)fetchInfoMapping;	// IMP=0x00100000000bdb89

@end

