//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSXPCConnection;
@protocol MobileGestaltHelper;

@interface MobileGestaltHelperProxy : NSObject
{
    int _error;	// 8 = 0x8
    id <MobileGestaltHelper> _helper;	// 16 = 0x10
    NSXPCConnection *_connection;	// 24 = 0x18
}

+ (id)proxy;	// IMP=0x0060000000001e9b
@property int error; // @synthesize error=_error;
@property(readonly) NSXPCConnection *connection; // @synthesize connection=_connection;
@property(readonly) id <MobileGestaltHelper> helper; // @synthesize helper=_helper;
- (_Bool)proxySetCacheSentinel;	// IMP=0x0000000000001dd9
- (_Bool)proxyRebuildCache;	// IMP=0x0000000000001d04
- (void)invalidate;	// IMP=0x0000000000001ce2
- (id)init;	// IMP=0x0000000000001a73
- (void)dealloc;	// IMP=0x0000000000001a18

@end

