//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class CALayer, NSArray, NSMutableDictionary;

@interface BKDisplayAnnotationContainedSubnodeRenderer
{
    CALayer *_backgroundLayer;	// 8 = 0x8
    NSMutableDictionary *_sectionTitleAnnotations;	// 16 = 0x10
    NSArray *_subannotations;	// 24 = 0x18
}

- (void).cxx_destruct;	// IMP=0x0020000000052adb
@property(retain, nonatomic) NSArray *subannotations; // @synthesize subannotations=_subannotations;
@property(retain, nonatomic) NSMutableDictionary *sectionTitleAnnotations; // @synthesize sectionTitleAnnotations=_sectionTitleAnnotations;
@property(retain, nonatomic) CALayer *backgroundLayer; // @synthesize backgroundLayer=_backgroundLayer;
- (void)layoutAnnotationStack:(id)arg1;	// IMP=0x0010000000051c6f
- (struct CGSize)_getFrames:(struct CGRect *)arg1 ofAnnotations:(id)arg2 fixSuperlayer:(id)arg3 scale:(double)arg4;	// IMP=0x00100000000518d9
- (void)regenerateLayerTree;	// IMP=0x00100000000517b7
- (void)styleSheetDidChange;	// IMP=0x00100000000514f9
- (_Bool)shouldRenderWithSupernode;	// IMP=0x00100000000514f1

@end

