//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <UIKit/UIResponder.h>

@class NSString, TVSHUICameraRootViewController, UIWindow;
@protocol BSInvalidatable;

@interface TVSHUICameraWindowSceneDelegate : UIResponder
{
    UIWindow *_window;	// 8 = 0x8
    TVSHUICameraRootViewController *_rootViewController;	// 16 = 0x10
    id <BSInvalidatable> _sceneVisibilityAssertion;	// 24 = 0x18
}

- (void).cxx_destruct;	// IMP=0x0020000000005be0
@property(readonly, nonatomic) id <BSInvalidatable> sceneVisibilityAssertion; // @synthesize sceneVisibilityAssertion=_sceneVisibilityAssertion;
@property(readonly, nonatomic) __weak TVSHUICameraRootViewController *rootViewController; // @synthesize rootViewController=_rootViewController;
@property(retain, nonatomic) UIWindow *window; // @synthesize window=_window;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"UIWindow",?,&,N,V_window

- (id)_FBSScene;	// IMP=0x0010000000005ac0
- (void)_sendAction:(id)arg1;	// IMP=0x0010000000005520
- (void)_dismissScene;	// IMP=0x00100000000054c0
- (void)_didPrepareForPresentationWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x0010000000005150
- (void)cameraWindowScene:(id)arg1 didReceiveCameraActivationContext:(id)arg2;	// IMP=0x00100000000050b0
- (void)cameraRootViewControllerRequestsDismissal:(id)arg1;	// IMP=0x0010000000004e00
- (void)cameraRootViewController:(id)arg1 didPrepareForPresentationWithCompletion:(CDUnknownBlockType)arg2;	// IMP=0x0010000000004b20
- (void)scene:(id)arg1 willConnectToSession:(id)arg2 options:(id)arg3;	// IMP=0x0010000000004250
- (void)dealloc;	// IMP=0x00100000000041f0

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"NSString",?,R,C

@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

