//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class MISSING_TYPE;

@interface _TtC12amsaccountsd27DeviceAccountPrivacyUpdater : NSObject
{
    MISSING_TYPE *stateTracker;	// 8 = 0x8
}

+ (id)shared;	// IMP=0x00200000000a11ef
- (void).cxx_destruct;	// IMP=0x00400000000a12c1
- (id)init;	// IMP=0x00100000000a1280

@end

