//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class AMSLRUCache, NSString;
@protocol OS_dispatch_queue;

@interface AMSDCookieService : NSObject
{
    AMSLRUCache *_altDSIDHashCache;	// 8 = 0x8
    AMSLRUCache *_dsidHashCache;	// 16 = 0x10
    AMSLRUCache *_cookiePropertyCache;	// 24 = 0x18
    AMSLRUCache *_cookieDatabaseCache;	// 32 = 0x20
    NSObject<OS_dispatch_queue> *_queue;	// 40 = 0x28
}

+ (_Bool)isConnectionEntitled:(id)arg1;	// IMP=0x0020000000014b66
+ (id)sharedService;	// IMP=0x00100000000120a3
- (void).cxx_destruct;	// IMP=0x0020000000014cbb
@property(readonly, nonatomic) NSObject<OS_dispatch_queue> *queue; // @synthesize queue=_queue;
@property(readonly, nonatomic) AMSLRUCache *cookieDatabaseCache; // @synthesize cookieDatabaseCache=_cookieDatabaseCache;
@property(readonly, nonatomic) AMSLRUCache *cookiePropertyCache; // @synthesize cookiePropertyCache=_cookiePropertyCache;
@property(readonly, nonatomic) AMSLRUCache *dsidHashCache; // @synthesize dsidHashCache=_dsidHashCache;
@property(readonly, nonatomic) AMSLRUCache *altDSIDHashCache; // @synthesize altDSIDHashCache=_altDSIDHashCache;
- (void)updateCookiesWithCookiePropertiesToAdd:(id)arg1 cookiePropertiesToRemove:(id)arg2 forAccount:(id)arg3 withCompletion:(CDUnknownBlockType)arg4;	// IMP=0x0010000000013fca
- (id)getCookiePropertiesForAccount:(id)arg1 cookieDatabaseOnly:(_Bool)arg2 error:(id *)arg3;	// IMP=0x00100000000135a3
- (void)getCookiePropertiesForAccount:(id)arg1 cookieDatabaseOnly:(_Bool)arg2 withCompletion:(CDUnknownBlockType)arg3;	// IMP=0x0010000000012e61
- (void)getCookiePropertiesForAccount:(id)arg1 withCompletion:(CDUnknownBlockType)arg2;	// IMP=0x0010000000012e4a
- (void)getCookieDatabasePathForAccount:(id)arg1 withCompletion:(CDUnknownBlockType)arg2;	// IMP=0x0010000000012c48
- (void)clearDanglingCookieDatabasesWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x0010000000012b43
- (id)clearDanglingCookieDatabases;	// IMP=0x00100000000126e3
- (void)clearAllCachedCookieProperties;	// IMP=0x00100000000120f8
- (id)init;	// IMP=0x0010000000011f85
- (id)_uniqueIdentifiersForAccount:(id)arg1 error:(id *)arg2;	// IMP=0x0010000000010236
- (id)_cookieDatabaseForAccount:(id)arg1 error:(id *)arg2;	// IMP=0x001000000000ff4c
- (id)_cachedCookieDatabaseForPath:(id)arg1;	// IMP=0x001000000000fd62
- (void)_cacheCookieDatabase:(id)arg1 withPath:(id)arg2;	// IMP=0x001000000000fb3b
- (void)_clearAllCachedCookieProperties;	// IMP=0x001000000000f9b8
- (id)_cachedCookiePropertiesForIdentifier:(id)arg1;	// IMP=0x001000000000f7ce
- (void)_cacheCookieProperties:(id)arg1 forIdentifier:(id)arg2;	// IMP=0x001000000000f531
- (id)_alliTunesAccountIdentifiers;	// IMP=0x001000000000effc

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"NSString",?,R,C

@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

