//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSString;

@interface AMSDPaymentValidationService : NSObject
{
}

+ (id)paymentHardwareType;	// IMP=0x0020000000039da0
+ (_Bool)isConnectionEntitled:(id)arg1;	// IMP=0x00100000000396f2
+ (id)sharedQueue;	// IMP=0x0010000000039671
+ (id)sharedService;	// IMP=0x001000000003961c
- (void)paymentHardwareStatusHeaderWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x002000000003977c

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"NSString",?,R,C

@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

