//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSString, PBDiagnosticsUIController;

@interface PBDiagnosticsController : NSObject
{
    int _screenshotCapturedNotificationToken;	// 8 = 0x8
    PBDiagnosticsUIController *_uiController;	// 16 = 0x10
}

- (void).cxx_destruct;	// IMP=0x002000000007c92e
@property(readonly, nonatomic) int screenshotCapturedNotificationToken; // @synthesize screenshotCapturedNotificationToken=_screenshotCapturedNotificationToken;
@property(readonly, nonatomic) PBDiagnosticsUIController *uiController; // @synthesize uiController=_uiController;
- (void)_handleBlackScreenRecoveryEvent:(id)arg1;	// IMP=0x001000000007c802
- (void)_handleScreenshotEvent:(id)arg1;	// IMP=0x001000000007c72a
- (void)_handleSysdiagnoseEvent:(id)arg1;	// IMP=0x001000000007c62f
- (void)_setupSystemKeychordGesturesUsingSystemGestureManager:(id)arg1;	// IMP=0x001000000007c583
- (void)_showScreenshotCapturedIndication;	// IMP=0x001000000007c56c
- (void)showStackShotIndication;	// IMP=0x001000000007c555
- (void)hideSysdiagnoseRunningIndication;	// IMP=0x001000000007c53e
- (_Bool)showSysdiagnoseRunningIndication;	// IMP=0x001000000007c507
- (void)invalidate;	// IMP=0x001000000007c4c0
- (void)dealloc;	// IMP=0x001000000007c3fe
- (id)initWithUIController:(id)arg1 systemGestureManager:(id)arg2 screenshotNotificationName:(const char *)arg3;	// IMP=0x001000000007bf9d
- (id)init;	// IMP=0x001000000007bf1e

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"NSString",?,R,C

@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

