//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <UIKitCore/UITapGestureRecognizer.h>

@interface PBGameControllerTapGestureRecognizer : UITapGestureRecognizer
{
    _Bool _isHomePressType;	// 8 = 0x8
}

@property(readonly, nonatomic) _Bool isHomePressType; // @synthesize isHomePressType=_isHomePressType;
- (void)pressesEnded:(id)arg1 withEvent:(id)arg2;	// IMP=0x001000000021274c
- (void)pressesChanged:(id)arg1 withEvent:(id)arg2;	// IMP=0x00100000002126ab
- (void)pressesBegan:(id)arg1 withEvent:(id)arg2;	// IMP=0x001000000021251e
- (void)setAllowedPressTypes:(id)arg1;	// IMP=0x001000000021249e

@end

