//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSString, PBDisplayManager, PBLanguageChangeObserver, PBSceneManager, PBUserProfileManager, PLInternationalizationService;

@interface PBInternationalizationManager : NSObject
{
    long long _userInterfaceLayoutDirection;	// 8 = 0x8
    unsigned long long _regionChangeTimestamp;	// 16 = 0x10
    PLInternationalizationService *_internationalizationService;	// 24 = 0x18
    PBSceneManager *_sceneManager;	// 32 = 0x20
    PBUserProfileManager *_userProfileManager;	// 40 = 0x28
    PBDisplayManager *_displayManager;	// 48 = 0x30
    PBLanguageChangeObserver *_languageChangeObserver;	// 56 = 0x38
}

- (void).cxx_destruct;	// IMP=0x00200000001ebfdb
@property(readonly, nonatomic) PBLanguageChangeObserver *languageChangeObserver; // @synthesize languageChangeObserver=_languageChangeObserver;
@property(readonly, nonatomic) PBDisplayManager *displayManager; // @synthesize displayManager=_displayManager;
@property(readonly, nonatomic) PBUserProfileManager *userProfileManager; // @synthesize userProfileManager=_userProfileManager;
@property(readonly, nonatomic) PBSceneManager *sceneManager; // @synthesize sceneManager=_sceneManager;
@property(readonly, nonatomic) PLInternationalizationService *internationalizationService; // @synthesize internationalizationService=_internationalizationService;
@property(readonly, nonatomic) unsigned long long regionChangeTimestamp; // @synthesize regionChangeTimestamp=_regionChangeTimestamp;
- (void)_languageDidChange;	// IMP=0x00000000001ebefa
- (void)observerDidObserveRegionWillChange:(id)arg1;	// IMP=0x00100000001ebe88
- (void)observer:(id)arg1 didObserveLanguageChange:(_Bool)arg2 localeChange:(_Bool)arg3 source:(long long)arg4;	// IMP=0x00100000001eb6b9
- (void)internationalizationService:(id)arg1 client:(id)arg2 setPreferredLanguages:(id)arg3 withVariants:(id)arg4 completion:(CDUnknownBlockType)arg5;	// IMP=0x00100000001eb0ae
- (void)internationalizationService:(id)arg1 client:(id)arg2 setDeviceRegion:(id)arg3 changePrimaryLanguage:(_Bool)arg4 completion:(CDUnknownBlockType)arg5;	// IMP=0x00100000001ea671
- (void)dealloc;	// IMP=0x00100000001ea616
- (id)initWithSceneManager:(id)arg1 userProfileManager:(id)arg2 displayManager:(id)arg3;	// IMP=0x00100000001ea0d3

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"NSString",?,R,C

@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

