//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class FBSceneSnapshot, NSString, UIImage, XBSnapshotDataProviderContext;

@interface PBSceneSnapshotDataProvider : NSObject
{
    XBSnapshotDataProviderContext *_context;	// 8 = 0x8
    FBSceneSnapshot *_snapshot;	// 16 = 0x10
    UIImage *_cachedImage;	// 24 = 0x18
    double _scaleFactor;	// 32 = 0x20
}

- (void).cxx_destruct;	// IMP=0x002000000014a6f1
@property(readonly, nonatomic) double scaleFactor; // @synthesize scaleFactor=_scaleFactor;
@property(readonly, nonatomic) UIImage *cachedImage; // @synthesize cachedImage=_cachedImage;
@property(readonly, nonatomic) FBSceneSnapshot *snapshot; // @synthesize snapshot=_snapshot;
@property(readonly, retain, nonatomic) XBSnapshotDataProviderContext *context; // @synthesize context=_context;
- (void)invalidateImage;	// IMP=0x001000000014a687
- (id)fetchImage;	// IMP=0x001000000014a2b2
- (id)initWithSceneSnapshot:(id)arg1 scaleFactor:(double)arg2;	// IMP=0x001000000014a135
- (id)init;	// IMP=0x001000000014a127

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"NSString",?,R,C

@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

