//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <UserProfiles/UPCandidateProfileStoreSnapshot.h>

@class PBSSuggestedUserProfileSnapshot;

@interface UPCandidateProfileStoreSnapshot (PineBoardAdditions)
@property(readonly, copy, nonatomic) PBSSuggestedUserProfileSnapshot *pb_suggestedUserProfilesSnapshot;
@end

