//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSMutableDictionary;
@protocol OS_dispatch_queue, OS_dispatch_source;

@interface RPMetrics : NSObject
{
    NSObject<OS_dispatch_queue> *_reportQueue;	// 8 = 0x8
    NSObject<OS_dispatch_source> *_reportTimer;	// 16 = 0x10
    _Bool _sendReport;	// 24 = 0x18
    NSMutableDictionary *_awdlBrowseMetrics;	// 32 = 0x20
    NSObject<OS_dispatch_queue> *_dispatchQueue;	// 40 = 0x28
    NSMutableDictionary *_needsAWDLAdvertisementMetrics;	// 48 = 0x30
}

+ (id)sharedMetricsNoCreate;	// IMP=0x004000000007d20d
+ (id)sharedMetrics;	// IMP=0x001000000007d178
- (void).cxx_destruct;	// IMP=0x002000000007e052
@property(retain, nonatomic) NSMutableDictionary *needsAWDLAdvertisementMetrics; // @synthesize needsAWDLAdvertisementMetrics=_needsAWDLAdvertisementMetrics;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *dispatchQueue; // @synthesize dispatchQueue=_dispatchQueue;
@property(retain, nonatomic) NSMutableDictionary *awdlBrowseMetrics; // @synthesize awdlBrowseMetrics=_awdlBrowseMetrics;
- (void)_reportMetrics;	// IMP=0x001000000007da30
- (void)_logReceivedMessageType:(int)arg1 identifier:(id)arg2 options:(id)arg3 appID:(id)arg4 timeBegin:(double)arg5 timeEnd:(double)arg6 bytesAdded:(unsigned long long)arg7 messagesAdded:(unsigned long long)arg8;	// IMP=0x001000000007da2a
- (void)logReceivedMessageType:(int)arg1 identifier:(id)arg2 options:(id)arg3 appID:(id)arg4 ctx:(CDStruct_20fd928a *)arg5;	// IMP=0x001000000007d853
- (void)logNeedsAWDLAdvertisementClient:(id)arg1 actionType:(unsigned char)arg2 bluetoothType:(unsigned char)arg3;	// IMP=0x001000000007d66e
- (void)logAWDLBrowseClient:(id)arg1;	// IMP=0x001000000007d4e9
- (void)invalidate;	// IMP=0x001000000007d487
- (void)_activate;	// IMP=0x001000000007d43a
- (void)activate;	// IMP=0x001000000007d3d9
- (id)descriptionWithLevel:(int)arg1;	// IMP=0x001000000007d3d1
- (id)init;	// IMP=0x001000000007d21e

@end

