//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class NSNumber;

@interface RPNearFieldValidationPayload
{
    _Bool _isKnownIdentity;	// 16 = 0x10
    NSNumber *_supportsApplicationLabel;	// 24 = 0x18
}

- (void).cxx_destruct;	// IMP=0x0020000000059432
@property(readonly, nonatomic) NSNumber *supportsApplicationLabel; // @synthesize supportsApplicationLabel=_supportsApplicationLabel;
@property(readonly, nonatomic) _Bool isKnownIdentity; // @synthesize isKnownIdentity=_isKnownIdentity;
- (id)descriptionWithLevel:(int)arg1;	// IMP=0x0010000000059313
- (id)description;	// IMP=0x00100000000592fc
- (id)dictionaryRepresentation;	// IMP=0x00100000000591af
- (id)initWithDictionary:(id)arg1;	// IMP=0x00100000000590ba
- (id)initWithKnownIdentity:(_Bool)arg1 supportsApplicationLabel:(_Bool)arg2;	// IMP=0x0010000000059019

@end

