//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSMutableArray, NSString;

@interface NDApplication : NSObject
{
    NSString *_bundleIdentifier;	// 8 = 0x8
    NSMutableArray *_observers;	// 16 = 0x10
}

+ (_Bool)springBoardApplicationExistsWithIdentifier:(id)arg1;	// IMP=0x00400000000013ac
+ (id)springboardApplicationWithBundleIdentifier:(id)arg1;	// IMP=0x00100000000012a2
+ (id)applicationWithIdentifier:(id)arg1;	// IMP=0x001000000000118e
+ (void)initialize;	// IMP=0x0010000000001135
- (void).cxx_destruct;	// IMP=0x0020000000001808
- (void)invokeSelectorForAllObservers:(SEL)arg1;	// IMP=0x00100000000015de
- (void)removeObserver:(id)arg1;	// IMP=0x001000000000153f
- (void)addObserver:(id)arg1;	// IMP=0x00100000000014c3
- (_Bool)isForeground;	// IMP=0x00100000000014bb
- (_Bool)hasForegroundBackgroundStates;	// IMP=0x00100000000014b3
- (id)initWithOperationID:(id)arg1;	// IMP=0x001000000000141e

@end

