//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class RMConnectionEndpoint;
@protocol RMConnectionDataDelegate;

@interface RMConnectionHandlerInternal : NSObject
{
    id <RMConnectionDataDelegate> _msgHandler;	// 8 = 0x8
    RMConnectionEndpoint *_endpoint;	// 16 = 0x10
}

- (void).cxx_destruct;	// IMP=0x002000000000495d
- (_Bool)isEqual:(id)arg1;	// IMP=0x00100000000048b2

@end

