//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface DMDFetchConfigurationSourceSyncTokenOperation
{
}

+ (_Bool)validateRequest:(id)arg1 error:(id *)arg2;	// IMP=0x004000000004efb5
+ (id)requiredEntitlements;	// IMP=0x001000000004ef5c
+ (id)whitelistedClassesForRequest;	// IMP=0x001000000004ef2a
- (void)runWithRequest:(id)arg1;	// IMP=0x004000000004ef7c
- (unsigned long long)queueGroup;	// IMP=0x001000000004ef71
- (_Bool)runOnMainThread;	// IMP=0x001000000004ef69

@end

