//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSString;

@interface DMDPowerAssertion : NSObject
{
    _Bool _isParked;	// 8 = 0x8
    NSString *_operation;	// 16 = 0x10
}

+ (id)assertionForOperation:(id)arg1;	// IMP=0x004000000006a607
- (void).cxx_destruct;	// IMP=0x002000000006acaa
@property(retain, nonatomic) NSString *operation; // @synthesize operation=_operation;
@property(nonatomic) _Bool isParked; // @synthesize isParked=_isParked;
- (void)_release;	// IMP=0x001000000006ab9c
- (void)_retain;	// IMP=0x001000000006aabb
- (void)unpark;	// IMP=0x001000000006a9c8
- (void)park;	// IMP=0x001000000006a8d2
- (void)stayAliveThroughHereAtLeast;	// IMP=0x001000000006a8cc
- (void)dealloc;	// IMP=0x001000000006a829
- (id)initForOperation:(id)arg1;	// IMP=0x001000000006a731

@end

