//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface DMDRemoveEventSubscriptionOperation
{
}

+ (id)requiredEntitlements;	// IMP=0x004000000006dc22
+ (id)whitelistedClassesForRequest;	// IMP=0x001000000006dbf0
+ (_Bool)validateRequest:(id)arg1 error:(id *)arg2;	// IMP=0x001000000006da72
- (void)runWithRequest:(id)arg1;	// IMP=0x004000000006dc3a
- (unsigned long long)queueGroup;	// IMP=0x001000000006dc2f

@end

