//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface DMDRemoveAppOperation
{
}

+ (void)removeAppWithBundleIdentifier:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x004000000006c287
+ (_Bool)removeAppMetadataForBundleIdentifier:(id)arg1 error:(id *)arg2;	// IMP=0x001000000006bd9f
+ (id)requiredEntitlements;	// IMP=0x001000000006b946
+ (id)whitelistedClassesForRequest;	// IMP=0x001000000006b914
- (void)runWithRequest:(id)arg1 bundleIdentifier:(id)arg2;	// IMP=0x004000000006b953

@end

