//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface DMDSetAppCellularSliceUUIDOperation
{
}

+ (id)requiredEntitlements;	// IMP=0x00400000000712d8
+ (id)whitelistedClassesForRequest;	// IMP=0x00100000000712a6
- (void)runWithRequest:(id)arg1 bundleIdentifier:(id)arg2;	// IMP=0x00400000000712e5

@end

