//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <CoreLocationProtobuf/CLPMotionActivity.h>

@interface CLPMotionActivity (RTExtensions)
+ (int)convertRTMotionActivtyConfidence:(unsigned long long)arg1;	// IMP=0x005000000012cf2f
+ (int)convertRTMotionActivtyType:(unsigned long long)arg1;	// IMP=0x005000000012cf12
- (id)initWithRTMotionActivity:(id)arg1;	// IMP=0x001000000012cf4a
@end

