//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSString;

__attribute__((visibility("hidden")))
@interface RTInvocationRecord : NSObject
{
    CDUnknownBlockType _block;	// 8 = 0x8
    CDUnknownBlockType _failureBlock;	// 16 = 0x10
    NSString *_invocationDescription;	// 24 = 0x18
}

- (void).cxx_destruct;	// IMP=0x00000000000381cc
@property(copy, nonatomic) NSString *invocationDescription; // @synthesize invocationDescription=_invocationDescription;
@property(copy, nonatomic) CDUnknownBlockType failureBlock; // @synthesize failureBlock=_failureBlock;
@property(copy, nonatomic) CDUnknownBlockType block; // @synthesize block=_block;
- (void)invokeFailure;	// IMP=0x000000000003816e
- (void)invoke;	// IMP=0x000000000003815b
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x000000000003810a
- (id)initWithBlock:(CDUnknownBlockType)arg1 failureBlock:(CDUnknownBlockType)arg2 description:(id)arg3;	// IMP=0x000000000003801e

@end

