//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class GKFriendListEntryCacheObject, NSDate;

@interface GKAchievementThatAFriendHasCacheObject
{
}

+ (id)entityName;	// IMP=0x00400000000fb65e
- (id)internalRepresentation;	// IMP=0x00200000000fb71f
- (void)updateWithServerRepresentation:(id)arg1;	// IMP=0x00100000000fb66b

// Remaining properties
@property(retain, nonatomic) GKFriendListEntryCacheObject *friend; // @dynamic friend;
@property(retain, nonatomic) NSDate *timestamp; // @dynamic timestamp;

@end

