//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <GameCenterFoundation/GKDispatchGroup.h>

@class GKClientProxy, NSManagedObjectContext;

@interface GKCacheTransactionGroup : GKDispatchGroup
{
    NSManagedObjectContext *_context;	// 64 = 0x40
    GKClientProxy *_client;	// 72 = 0x48
}

+ (id)transactionGroupWithName:(id)arg1 context:(id)arg2 client:(id)arg3;	// IMP=0x004000000011551e
+ (id)dispatchGroupWithName:(id)arg1;	// IMP=0x0010000000115405
- (void).cxx_destruct;	// IMP=0x0020000000116501
@property(retain, nonatomic) GKClientProxy *client; // @synthesize client=_client;
@property(retain, nonatomic) NSManagedObjectContext *context; // @synthesize context=_context;
- (void)notifyOnMainQueueWithBlock:(CDUnknownBlockType)arg1;	// IMP=0x0010000000116392
- (void)notifyOnQueue:(id)arg1 block:(CDUnknownBlockType)arg2;	// IMP=0x0010000000116259
- (void)stripGKPlayerInternalPIIs;	// IMP=0x0010000000115feb
- (void)performOnQueue:(id)arg1 block:(CDUnknownBlockType)arg2;	// IMP=0x0010000000115e80
- (void)performOnManagedObjectContext:(CDUnknownBlockType)arg1;	// IMP=0x0010000000115c10
- (void)dealloc;	// IMP=0x00100000001159fc
- (id)initWithName:(id)arg1 context:(id)arg2 client:(id)arg3;	// IMP=0x00100000001157bf
- (id)initWithName:(id)arg1;	// IMP=0x0010000000115698
- (id)transactionGroupWithName:(id)arg1;	// IMP=0x00100000001155e9

@end

