//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface GKDeprecatedBulletin
{
}

+ (_Bool)supportsSecureCoding;	// IMP=0x002000000014cbb8
- (void)encodeWithCoder:(id)arg1;	// IMP=0x004000000014cbef
- (id)initWithCoder:(id)arg1;	// IMP=0x001000000014cbc0

@end

