//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <GameCenterFoundation/GKFamiliarPlayerInternal.h>

@interface GKFamiliarPlayerInternal (Cache)
+ (int)familiarity;	// IMP=0x001000000013dde4
- (void)updateWithCacheObject:(id)arg1;	// IMP=0x002000000013dcdf
@end

