//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class NSString;

@interface GKGameStatServicePrivate
{
}

+ (id)currentFriendsPlayedList:(id)arg1;	// IMP=0x002000000007d068
+ (id)filterUnreportedAndHiddenAchievements:(id)arg1 includeUnreported:(_Bool)arg2 includeHidden:(_Bool)arg3;	// IMP=0x001000000007a589
+ (unsigned long long)requiredEntitlements;	// IMP=0x001000000007a57e
+ (Class)interfaceClass;	// IMP=0x001000000007a56d
- (oneway void)clearLeaderboardsCacheWithHandler:(CDUnknownBlockType)arg1;	// IMP=0x0020000000080e53
- (oneway void)clearAchievementsCacheWithHandler:(CDUnknownBlockType)arg1;	// IMP=0x00100000000809f3
- (oneway void)getReengagementAchievement:(CDUnknownBlockType)arg1;	// IMP=0x00100000000800dd
- (oneway void)getReengagementAchievements:(CDUnknownBlockType)arg1;	// IMP=0x0010000000080040
- (oneway void)loadReengagementAchievements:(id)arg1 handler:(CDUnknownBlockType)arg2;	// IMP=0x001000000007f2e6
- (id)processReengagementResults:(id)arg1 localPlayer:(id)arg2 expirationDate:(id)arg3 context:(id)arg4;	// IMP=0x001000000007ed54
- (id)existingReengagementAchievement:(id)arg1 context:(id)arg2;	// IMP=0x001000000007ea49
- (id)findAchievementInternal:(id)arg1 identifier:(id)arg2 context:(id)arg3 existingPercent:(double)arg4 existingDate:(id)arg5;	// IMP=0x001000000007e3b0
- (id)getCachedAcievementListForLocalPlayer:(id)arg1 context:(id)arg2;	// IMP=0x001000000007e25d
- (oneway void)getGamesFriendsPlayed:(long long)arg1 type:(id)arg2 fetchOptions:(unsigned long long)arg3 withinSecs:(long long)arg4 matchingBundleIDs:(id)arg5 handler:(CDUnknownBlockType)arg6;	// IMP=0x001000000007d647
- (oneway void)getGamesFriendsPlayed:(long long)arg1 type:(id)arg2 withinSecs:(long long)arg3 matchingBundleIDs:(id)arg4 handler:(CDUnknownBlockType)arg5;	// IMP=0x001000000007d623
- (oneway void)expireGamesFriendsPlayed;	// IMP=0x001000000007d392
- (void)loadGamesFriendsPlayed:(id)arg1 matchingBundleIDs:(id)arg2 handler:(CDUnknownBlockType)arg3;	// IMP=0x001000000007bdd8
- (id)ensureGameObject:(id)arg1 gameDescriptor:(id)arg2;	// IMP=0x001000000007bce6
- (id)ensureGameObjectsForDescriptors:(id)arg1 moc:(id)arg2;	// IMP=0x001000000007bb4d
- (id)currentLocalPlayer;	// IMP=0x001000000007ba8d
- (oneway void)getHypotheticalLeaderboardRanksForScores:(id)arg1 forGameDescriptor:(id)arg2 handler:(CDUnknownBlockType)arg3;	// IMP=0x001000000007b459
- (oneway void)getAchievementLeaderboardForRequest:(id)arg1 handler:(CDUnknownBlockType)arg2;	// IMP=0x001000000007b447
- (oneway void)getEntriesForLeaderboard:(id)arg1 fetchOptions:(unsigned long long)arg2 gameDescriptor:(id)arg3 localPlayer:(id)arg4 playerScope:(long long)arg5 timeScope:(long long)arg6 range:(struct _NSRange)arg7 players:(id)arg8 handler:(CDUnknownBlockType)arg9;	// IMP=0x001000000007aed8
- (oneway void)loadAchievementsForGameWithProfileFetchOptions:(id)arg1 players:(id)arg2 includeUnreported:(_Bool)arg3 includeHidden:(_Bool)arg4 profileFetchOptions:(unsigned long long)arg5 withCompletionHandler:(CDUnknownBlockType)arg6;	// IMP=0x001000000007a7b5

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"NSString",?,R,C

@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

