//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class GKGameCacheObject;

@interface GKLeaderboardSetListCacheObject
{
}

+ (Class)entryClass;	// IMP=0x00400000000fe2b6
+ (id)entityName;	// IMP=0x00100000000fe2a9
- (_Bool)isValid;	// IMP=0x00200000000fe3c6
- (void)updateWithServerRepresentation:(id)arg1 expirationDate:(id)arg2;	// IMP=0x00100000000fe2c7

// Remaining properties
@property(retain, nonatomic) GKGameCacheObject *game; // @dynamic game;

@end

