//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@interface CCDFeatures : NSObject
{
}

+ (id)depResponseDataFromData:(id)arg1;	// IMP=0x0020000000008056
+ (id)depResponseContentTypeFromContentType:(id)arg1;	// IMP=0x0010000000007ff8
+ (id)deviceRegisterURLStringWithURLString:(id)arg1;	// IMP=0x0010000000007f88
+ (id)depRemoveEnrollmentURLStringWithURLString:(id)arg1;	// IMP=0x0010000000007f18
+ (id)depProvisionalEnrollmentURLStringWithURLString:(id)arg1;	// IMP=0x0010000000007ea8
+ (id)depDeviceSerialNumberWithValue:(id)arg1;	// IMP=0x0010000000007e38
+ (id)depConfigurationEnrollmentURLStringWithURLString:(id)arg1;	// IMP=0x0010000000007dc2
+ (_Bool)sentinelExistsAtPath:(id)arg1;	// IMP=0x0010000000007d3a
+ (id)stringForDefaultsKey:(id)arg1;	// IMP=0x0010000000007ca6
+ (_Bool)isAppleInternal;	// IMP=0x0010000000007c95

@end

