//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface HydrogenDomain
{
}

+ (_Bool)supportsSecureCoding;	// IMP=0x0020000000005615
- (void)updateParameters;	// IMP=0x0040000000005568
- (id)initWithCoder:(id)arg1;	// IMP=0x001000000000551c
- (id)init;	// IMP=0x00100000000054d0
- (void)_internal_doInit;	// IMP=0x0010000000005460
- (id)domainChangeNotificationName;	// IMP=0x0010000000005453
- (unsigned long long)domain;	// IMP=0x0010000000005448

@end

