//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface LithiumDomain
{
}

+ (_Bool)supportsSecureCoding;	// IMP=0x0020000000011c89
- (void)updateParameters;	// IMP=0x0040000000011bcc
- (id)initWithCoder:(id)arg1;	// IMP=0x0010000000011b80
- (id)init;	// IMP=0x0010000000011b34
- (void)_internal_doInit;	// IMP=0x0010000000011ac4
- (id)domainChangeNotificationName;	// IMP=0x0010000000011ab7
- (unsigned long long)domain;	// IMP=0x0010000000011aac

@end

