//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface SodiumDomain
{
}

+ (_Bool)supportsSecureCoding;	// IMP=0x0020000000019f7b
- (void)updateParameters;	// IMP=0x0040000000019ece
- (id)initWithCoder:(id)arg1;	// IMP=0x0010000000019e82
- (id)init;	// IMP=0x0010000000019e36
- (void)_internal_doInit;	// IMP=0x0010000000019dd2
- (id)domainChangeNotificationName;	// IMP=0x0010000000019dc5
- (unsigned long long)domain;	// IMP=0x0010000000019dba

@end

