//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class AXAssetsXPCActivity, NSDictionary, NSString;

@interface AXSimpleAssetTaskTrigger : NSObject
{
    unsigned long long _type;	// 8 = 0x8
    NSString *_launchActivityId;	// 16 = 0x10
    AXAssetsXPCActivity *_launchActivity;	// 24 = 0x18
    NSString *_notificationName;	// 32 = 0x20
    NSDictionary *_arguments;	// 40 = 0x28
}

+ (id)withAnonymousInvokation:(id)arg1;	// IMP=0x002000000000dc26
+ (id)withFirstUnlockType;	// IMP=0x001000000000dbee
+ (id)withFirstBootType;	// IMP=0x001000000000dbb6
+ (id)withNotificationName:(id)arg1;	// IMP=0x001000000000db4a
+ (id)withLaunchActivityId:(id)arg1;	// IMP=0x001000000000dae1
- (void).cxx_destruct;	// IMP=0x002000000000dddd
@property(retain, nonatomic) NSDictionary *arguments; // @synthesize arguments=_arguments;
@property(retain, nonatomic) NSString *notificationName; // @synthesize notificationName=_notificationName;
@property(retain, nonatomic) AXAssetsXPCActivity *launchActivity; // @synthesize launchActivity=_launchActivity;
@property(retain, nonatomic) NSString *launchActivityId; // @synthesize launchActivityId=_launchActivityId;
@property(nonatomic) unsigned long long type; // @synthesize type=_type;
- (id)description;	// IMP=0x001000000000dd4b
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x001000000000dc92

@end

