//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSString, SOSAccount;

@interface SOSClient : NSObject
{
    SOSAccount *_account;	// 8 = 0x8
}

- (void).cxx_destruct;	// IMP=0x002000000023ed89
@property(retain) SOSAccount *account; // @synthesize account=_account;
- (void)setBypass:(_Bool)arg1 reply:(CDUnknownBlockType)arg2;	// IMP=0x001000000023ecf1
- (id)SOSMonitorModeSOSIsActiveDescription;	// IMP=0x001000000023eca1
- (_Bool)SOSMonitorModeSOSIsActive;	// IMP=0x001000000023ebad
- (void)SOSMonitorModeSOSIsActiveWithCallback:(CDUnknownBlockType)arg1;	// IMP=0x001000000023eaea
- (void)SOSMonitorModeEnableSOS;	// IMP=0x001000000023ea6c
- (void)SOSMonitorModeDisableSOS;	// IMP=0x001000000023e9ee
- (void)removeV0Peers:(CDUnknownBlockType)arg1;	// IMP=0x001000000023e985
- (void)iCloudIdentityStatus_internal:(CDUnknownBlockType)arg1;	// IMP=0x001000000023e91c
- (void)rpcTriggerRingUpdate:(CDUnknownBlockType)arg1;	// IMP=0x001000000023e85e
- (void)rpcTriggerBackup:(id)arg1 complete:(CDUnknownBlockType)arg2;	// IMP=0x001000000023e77e
- (void)keyStatusFor:(int)arg1 complete:(CDUnknownBlockType)arg2;	// IMP=0x001000000023e709
- (void)accountStatus:(CDUnknownBlockType)arg1;	// IMP=0x001000000023e6a0
- (void)iCloudIdentityStatus:(CDUnknownBlockType)arg1;	// IMP=0x001000000023e637
- (void)ghostBustInfo:(CDUnknownBlockType)arg1;	// IMP=0x001000000023e5ce
- (void)ghostBustPeriodic:(unsigned int)arg1 complete:(CDUnknownBlockType)arg2;	// IMP=0x001000000023e559
- (void)ghostBustTriggerTimed:(unsigned int)arg1 complete:(CDUnknownBlockType)arg2;	// IMP=0x001000000023e4e4
- (void)ghostBust:(unsigned int)arg1 complete:(CDUnknownBlockType)arg2;	// IMP=0x001000000023e46f
- (void)setWatchdogParmeters:(id)arg1 complete:(CDUnknownBlockType)arg2;	// IMP=0x001000000023e3e4
- (void)getWatchdogParameters:(CDUnknownBlockType)arg1;	// IMP=0x001000000023e37b
- (void)rpcTriggerSync:(id)arg1 complete:(CDUnknownBlockType)arg2;	// IMP=0x001000000023e2d5
- (void)importInitialSyncCredentials:(id)arg1 complete:(CDUnknownBlockType)arg2;	// IMP=0x001000000023e1f0
- (void)initialSyncCredentials:(unsigned int)arg1 altDSID:(id)arg2 flowID:(id)arg3 deviceSessionID:(id)arg4 canSendMetrics:(_Bool)arg5 complete:(CDUnknownBlockType)arg6;	// IMP=0x001000000023e0b0
- (void)joinCircleWithBlob:(id)arg1 altDSID:(id)arg2 flowID:(id)arg3 deviceSessionID:(id)arg4 canSendMetrics:(_Bool)arg5 version:(int)arg6 complete:(CDUnknownBlockType)arg7;	// IMP=0x001000000023dfb5
- (void)circleJoiningBlob:(id)arg1 flowID:(id)arg2 deviceSessionID:(id)arg3 canSendMetrics:(_Bool)arg4 applicant:(id)arg5 complete:(CDUnknownBlockType)arg6;	// IMP=0x001000000023dec6
- (void)circleHash:(CDUnknownBlockType)arg1;	// IMP=0x001000000023de5d
- (void)myPeerInfo:(id)arg1 flowID:(id)arg2 deviceSessionID:(id)arg3 canSendMetrics:(_Bool)arg4 complete:(CDUnknownBlockType)arg5;	// IMP=0x001000000023dd8e
- (void)stashAccountCredential:(id)arg1 altDSID:(id)arg2 flowID:(id)arg3 deviceSessionID:(id)arg4 canSendMetrics:(_Bool)arg5 complete:(CDUnknownBlockType)arg6;	// IMP=0x001000000023dca1
- (void)validatedStashedAccountCredential:(id)arg1 flowID:(id)arg2 deviceSessionID:(id)arg3 canSendMetrics:(_Bool)arg4 complete:(CDUnknownBlockType)arg5;	// IMP=0x001000000023dbd2
- (void)assertStashedAccountCredential:(CDUnknownBlockType)arg1;	// IMP=0x001000000023db69
- (void)stashedCredentialPublicKey:(CDUnknownBlockType)arg1;	// IMP=0x001000000023db00
- (void)rateLimitingPerformanceCounters:(CDUnknownBlockType)arg1;	// IMP=0x001000000023da97
- (void)kvsPerformanceCounters:(CDUnknownBlockType)arg1;	// IMP=0x001000000023da2e
- (void)userPublicKey:(CDUnknownBlockType)arg1;	// IMP=0x001000000023d9c5
- (_Bool)checkEntitlement:(id)arg1;	// IMP=0x001000000023d9bd
- (id)initSOSClientWithAccount:(id)arg1;	// IMP=0x001000000023d952

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"NSString",?,R,C

@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

