//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSString;
@protocol OS_dispatch_queue, SHAudioRecorderDelegate;

@interface SHAudioRecorder : NSObject
{
    struct AudioQueueBuffer *mBuffers[3];	// 8 = 0x8
    id <SHAudioRecorderDelegate> _delegate;	// 32 = 0x20
    long long _recordingSource;	// 40 = 0x28
    struct OpaqueAudioQueue *_audioQueue;	// 48 = 0x30
    NSObject<OS_dispatch_queue> *_audioRecorderDispatchQueue;	// 56 = 0x38
    struct AudioStreamBasicDescription _audioStreamBasicDescription;	// 64 = 0x40
}

+ (_Bool)hasAudioQueueFailedWithStatus:(int)arg1 annotateError:(id *)arg2;	// IMP=0x000000000002e2a9
+ (_Bool)isAudioQueueRunning:(struct OpaqueAudioQueue *)arg1;	// IMP=0x001000000002e01f
- (void).cxx_destruct;	// IMP=0x002000000002e5f5
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *audioRecorderDispatchQueue; // @synthesize audioRecorderDispatchQueue=_audioRecorderDispatchQueue;
@property(nonatomic) struct AudioStreamBasicDescription audioStreamBasicDescription; // @synthesize audioStreamBasicDescription=_audioStreamBasicDescription;
@property(nonatomic) struct OpaqueAudioQueue *audioQueue; // @synthesize audioQueue=_audioQueue;
@property(nonatomic) long long recordingSource; // @synthesize recordingSource=_recordingSource;
@property(nonatomic) __weak id <SHAudioRecorderDelegate> delegate; // @synthesize delegate=_delegate;
@property(readonly, copy) NSString *description;
- (void)startAudioQueueAfterRetrySecondsWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x001000000002e2ff
- (_Bool)stopAudioQueueAndClearBuffersWithError:(id *)arg1;	// IMP=0x001000000002e083
- (_Bool)stopRecordingWithError:(id *)arg1;	// IMP=0x001000000002e00d
- (void)startRecordingWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x001000000002d894
@property(readonly, nonatomic) _Bool isRunning;
- (id)initWithRecordingSource:(long long)arg1;	// IMP=0x001000000002d809
- (void)dealloc;	// IMP=0x001000000002d76d

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"NSString",?,R,C

@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

