//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSString;

@interface SHServiceProvider : NSObject
{
    NSString *_machServiceName;	// 8 = 0x8
}

+ (id)availableServices;	// IMP=0x002000000000484f
- (void).cxx_destruct;	// IMP=0x00200000000050ae
@property(readonly, copy, nonatomic) NSString *machServiceName; // @synthesize machServiceName=_machServiceName;
- (id)uiServiceHandlerForConnection:(id)arg1 withClientCredentials:(id)arg2;	// IMP=0x0010000000004f02
- (id)shazamKitServiceHandleForConnection:(id)arg1 withClientCredentials:(id)arg2;	// IMP=0x0010000000004d7d
- (id)eventsServiceHandleForConnection:(id)arg1 withClientCredentials:(id)arg2;	// IMP=0x0010000000004c3c
- (id)handleForConnection:(id)arg1 withClientCredentials:(id)arg2;	// IMP=0x00100000000049ec
- (id)buildListener;	// IMP=0x0010000000004983
- (id)initWithService:(Class)arg1;	// IMP=0x001000000000491a

@end

