//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSISO8601DateFormatter, NSString, SHLocationProvider, SHMatcherRequest, SHShazamKitServerCatalog;
@protocol SHMatcherDelegate, SHNetworkRecognitionRequester;

@interface SHShazamKitServerMatcher : NSObject
{
    id <SHMatcherDelegate> _delegate;	// 8 = 0x8
    NSISO8601DateFormatter *_iso8601Formatter;	// 16 = 0x10
    SHShazamKitServerCatalog *_catalog;	// 24 = 0x18
    id <SHNetworkRecognitionRequester> _networkRequester;	// 32 = 0x20
    SHMatcherRequest *_matcherRequest;	// 40 = 0x28
    SHLocationProvider *_locationProvider;	// 48 = 0x30
}

- (void).cxx_destruct;	// IMP=0x0020000000009bfa
@property(retain, nonatomic) SHLocationProvider *locationProvider; // @synthesize locationProvider=_locationProvider;
@property(retain, nonatomic) SHMatcherRequest *matcherRequest; // @synthesize matcherRequest=_matcherRequest;
@property(retain, nonatomic) id <SHNetworkRecognitionRequester> networkRequester; // @synthesize networkRequester=_networkRequester;
@property(retain, nonatomic) SHShazamKitServerCatalog *catalog; // @synthesize catalog=_catalog;
@property(nonatomic) __weak id <SHMatcherDelegate> delegate; // @synthesize delegate=_delegate;
- (void)stopRecognitionForRequestID:(id)arg1;	// IMP=0x00100000000098ae
- (void)stopRecognition;	// IMP=0x0010000000009840
- (id)buildURLForSignature:(id)arg1 endpoint:(id)arg2;	// IMP=0x001000000000978d
- (id)payloadForSignature:(id)arg1 withLocation:(id)arg2;	// IMP=0x001000000000939b
- (id)partnerURLRequestForSignature:(id)arg1 endpoint:(id)arg2;	// IMP=0x0010000000009233
- (void)matchSignature:(id)arg1 tokenizedURL:(id)arg2;	// IMP=0x00100000000089bc
- (void)startRecognitionForRequest:(id)arg1;	// IMP=0x0010000000008639
- (void)responseForServerData:(id)arg1 signature:(id)arg2;	// IMP=0x001000000000834b
@property(readonly, nonatomic) NSISO8601DateFormatter *iso8601Formatter; // @synthesize iso8601Formatter=_iso8601Formatter;
- (id)initWithCatalog:(id)arg1 recognitionRequester:(id)arg2;	// IMP=0x0010000000008261
- (id)initWithCatalog:(id)arg1;	// IMP=0x00100000000081ad
- (void)dealloc;	// IMP=0x001000000000816b

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"NSString",?,R,C

@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

