//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <Foundation/NSCalendar.h>

__attribute__((visibility("hidden")))
@interface __NSCFCalendar : NSCalendar
{
}

+ (_Bool)supportsSecureCoding;	// IMP=0x00100000007514ca
- (id)initWithCoder:(id)arg1;	// IMP=0x0000000000751506
- (void)encodeWithCoder:(id)arg1;	// IMP=0x00000000007514d2
- (Class)classForCoder;	// IMP=0x00000000007514b9

@end

