//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <Foundation/NSTimer.h>

__attribute__((visibility("hidden")))
@interface NSCFTimer : NSTimer
{
}

+ (id)allocWithZone:(struct _NSZone *)arg1;	// IMP=0x008000000087a66a
+ (_Bool)automaticallyNotifiesObserversForKey:(id)arg1;	// IMP=0x008000000087a662
- (id)init;	// IMP=0x000000000087ab68
- (id)initWithFireDate:(id)arg1 interval:(double)arg2 target:(id)arg3 selector:(SEL)arg4 userInfo:(id)arg5 repeats:(_Bool)arg6;	// IMP=0x000000000087a9f8
- (unsigned long long)_cfTypeID;	// IMP=0x000000000087a9ee
- (void)fire;	// IMP=0x000000000087a943
- (id)userInfo;	// IMP=0x000000000087a78d
- (void)setFireDate:(id)arg1;	// IMP=0x000000000087a766
- (id)fireDate;	// IMP=0x000000000087a73e
- (void)invalidate;	// IMP=0x000000000087a734
- (void)setTolerance:(double)arg1;	// IMP=0x000000000087a72a
- (double)tolerance;	// IMP=0x000000000087a720
- (double)timeInterval;	// IMP=0x000000000087a716
- (_Bool)isValid;	// IMP=0x000000000087a706
- (unsigned long long)retainCount;	// IMP=0x000000000087a658
- (_Bool)retainWeakReference;	// IMP=0x000000000087a647
- (_Bool)allowsWeakReference;	// IMP=0x000000000087a637
- (oneway void)release;	// IMP=0x000000000087a62d
- (id)retain;	// IMP=0x000000000087a623
- (unsigned long long)hash;	// IMP=0x000000000087a619
- (_Bool)isEqual:(id)arg1;	// IMP=0x000000000087a5f6

@end

