//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSNumber;

@interface DaemonBiometricStore : NSObject
{
}

+ (id)_dispatchQueueUpdateToken;	// IMP=0x0040000000185b13
+ (void)_resetAccount:(id)arg1 withConnection:(id)arg2;	// IMP=0x001000000018591a
+ (void)_handleMessage:(id)arg1 connection:(id)arg2 withReplyBlock:(CDUnknownBlockType)arg3;	// IMP=0x0010000000185306
+ (void)tokenUpdateStateWithMessage:(id)arg1 connection:(id)arg2;	// IMP=0x0010000000185163
+ (void)tokenUpdateShouldStartWithMessage:(id)arg1 connection:(id)arg2;	// IMP=0x0010000000184f7b
+ (void)tokenUpdateDidFinishWithMessage:(id)arg1 connection:(id)arg2;	// IMP=0x0010000000184dac
+ (void)setEnabledWithMessage:(id)arg1 connection:(id)arg2;	// IMP=0x0010000000184664
+ (void)setAllowedWithMessage:(id)arg1 connection:(id)arg2;	// IMP=0x00100000001845ad
+ (void)saveIdentityMapWithMessage:(id)arg1 connection:(id)arg2;	// IMP=0x00100000001843dc
+ (void)resetWithMessage:(id)arg1 connection:(id)arg2;	// IMP=0x00100000001841fe
+ (void)resetAccountWithMessage:(id)arg1 connection:(id)arg2;	// IMP=0x0010000000184058
+ (void)isIdentityMapValidWithMessage:(id)arg1 connection:(id)arg2;	// IMP=0x0010000000183ebc
+ (void)getStateWithMessage:(id)arg1 connection:(id)arg2;	// IMP=0x00100000001839b5
+ (void)getKeyCountWithMessage:(id)arg1 connection:(id)arg2;	// IMP=0x001000000018364f
+ (void)getIdentityMapCountWithMessage:(id)arg1 connection:(id)arg2;	// IMP=0x00100000001834ee
+ (void)getCurrentACLVersionWithMessage:(id)arg1 connection:(id)arg2;	// IMP=0x0010000000183460
+ (void)getConstraintsDictionaryWithMessage:(id)arg1 connection:(id)arg2;	// IMP=0x00100000001833bf
+ (void)getCachedBiometricHTTPHeadersWithMessage:(id)arg1 connection:(id)arg2;	// IMP=0x0010000000182c65
+ (void)getCachedBiometricAuthenticationContextWithMessage:(id)arg1 connection:(id)arg2;	// IMP=0x0010000000182764
+ (void)getAllCachedBiometricHTTPHeadersWithMessage:(id)arg1 connection:(id)arg2;	// IMP=0x0010000000181f00
+ (void)observeXPCServer:(id)arg1;	// IMP=0x0010000000181d12
+ (long long)tokenUpdateState;	// IMP=0x0010000000181647
+ (_Bool)tokenUpdateShouldStartWithLogKey:(id)arg1;	// IMP=0x0010000000180d92
+ (void)tokenUpdateDidFinishWithLogKey:(id)arg1;	// IMP=0x0010000000180b3a
- (void)_deleteKeychainTokensForAccountIdentifier:(id)arg1;	// IMP=0x00200000001856cc
- (id)_bootDate;	// IMP=0x0010000000185627
@property long long biometricState;
- (void)saveIdentityMap:(id)arg1 forAccountIdentifier:(id)arg2;	// IMP=0x0010000000180969
- (void)registerAccountIdentifier:(id)arg1;	// IMP=0x0010000000180963
- (void)obliterateBiometricsForAccountIdentifier:(id)arg1;	// IMP=0x0010000000180779
- (long long)tokenAvailabilityForAccountIdentifier:(id)arg1;	// IMP=0x001000000018076e
@property(readonly) NSNumber *lastRegisteredAccountIdentifier;
- (unsigned long long)keyCountForAccountIdentifier:(id)arg1;	// IMP=0x00100000001802e7
- (_Bool)isIdentityMapValidForAccountIdentifier:(id)arg1;	// IMP=0x00100000001802df
@property(readonly) _Bool isBiometricStateEnabled;
- (id)identityMap;	// IMP=0x00100000001802b2
- (void)clearLastRegisteredAccountIdentifier;	// IMP=0x00100000001800ec
@property(readonly) _Bool canPerformBiometricOptIn;

@end

