//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <iTunesStore/ISOperation.h>

@class NSData, NSDictionary, NSNumber, NSString, SSURLConnectionResponse, SSURLRequestProperties, SSVGratisRequestBody;

@interface GratisClaimOperation : ISOperation
{
    NSNumber *_accountID;	// 96 = 0x60
    NSString *_authenticationReasonDescription;	// 104 = 0x68
    NSData *_clientAuditTokenData;	// 112 = 0x70
    SSURLRequestProperties *_defaultRequestProperties;	// 120 = 0x78
    NSDictionary *_rawOutput;	// 128 = 0x80
    SSVGratisRequestBody *_requestBody;	// 136 = 0x88
    _Bool _suppressesErrorDialogs;	// 144 = 0x90
    SSURLConnectionResponse *_urlResponse;	// 152 = 0x98
}

- (id)_newRetryRequestPropertiesWithURL:(id)arg1;	// IMP=0x002000000013c663
- (id)_newDefaultRequestProperties;	// IMP=0x001000000013c535
- (id)_bodyData;	// IMP=0x001000000013c4c5
- (id)_authenticationContext;	// IMP=0x001000000013c3dc
- (id)_accountID;	// IMP=0x001000000013c32b
- (void)operation:(id)arg1 didAuthenticateWithDSID:(id)arg2;	// IMP=0x001000000013c25b
- (void)run;	// IMP=0x001000000013bcb6
@property(readonly) SSURLConnectionResponse *URLResponse;
@property _Bool suppressesErrorDialogs;
@property(retain, nonatomic) NSData *clientAuditTokenData;
@property(copy) NSString *authenticationReasonDescription;
@property(readonly) NSDictionary *rawOutput;
- (void)dealloc;	// IMP=0x001000000013b991
- (id)initWithRequestBody:(id)arg1;	// IMP=0x001000000013b8f7
- (id)initWithPurchase:(id)arg1;	// IMP=0x001000000013b786

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"NSString",?,R,C

@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly, nonatomic) NSNumber *metricsLoadURLSamplingPercentage;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"NSNumber",?,R,N

@property(readonly, nonatomic) NSNumber *metricsLoadURLSamplingPercentageCachedResponses;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"NSNumber",?,R,N

@property(readonly, nonatomic) NSNumber *metricsLoadURLSessionDuration;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"NSNumber",?,R,N

@property(readonly) Class superclass;

@end

