//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface InstallMediaDownloadOperation
{
}

- (void)_updateRentalsPlist;	// IMP=0x00400000001c3db2
- (id)_newIPodLibraryItem;	// IMP=0x00100000001c3aae
- (_Bool)_isDaemonOwned;	// IMP=0x00100000001c3993
- (_Bool)_installExternalDownload:(id *)arg1;	// IMP=0x00100000001c350c
- (id)_installDaemonOwnedDownload:(id *)arg1;	// IMP=0x00100000001c30a2
- (_Bool)_areSourceAndDestinationEqual;	// IMP=0x00100000001c2f81
- (void)run;	// IMP=0x00100000001c29cb

@end

