//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class ISOperationQueue, SSMetricsEventController;
@protocol OS_dispatch_queue, OS_dispatch_source;

@interface MetricsController : NSObject
{
    long long _backoffRetryCount;	// 8 = 0x8
    NSObject<OS_dispatch_source> *_backoffRetryTimer;	// 16 = 0x10
    NSObject<OS_dispatch_queue> *_dispatchQueue;	// 24 = 0x18
    SSMetricsEventController *_eventController;	// 32 = 0x20
    ISOperationQueue *_operationQueue;	// 40 = 0x28
}

+ (id)sharedInstance;	// IMP=0x004000000016e3d3
- (void).cxx_destruct;	// IMP=0x00200000001703ec
- (void)_sendUnentitledResponseToMessage:(id)arg1 connection:(id)arg2;	// IMP=0x001000000017018f
- (void)_scheduleBackoffRetry;	// IMP=0x001000000016fd3f
- (void)_reportEventsIfNeeded;	// IMP=0x001000000016f9d5
- (void)_reportEvents;	// IMP=0x001000000016f6cd
- (id)_operationQueue;	// IMP=0x001000000016f611
- (_Bool)_hasEntitlements:(id)arg1;	// IMP=0x001000000016f5b5
- (void)_cancelBackoffRetryTimer;	// IMP=0x001000000016f57f
- (void)_cancelBackoffRetry;	// IMP=0x001000000016f55a
- (void)setInternalSettingsWithMessage:(id)arg1 connection:(id)arg2;	// IMP=0x001000000016f3eb
- (void)reportEventsWithMessage:(id)arg1 connection:(id)arg2;	// IMP=0x001000000016efad
- (void)recordAnalyticsWithMetricsDialogEventWithMessage:(id)arg1 connection:(id)arg2;	// IMP=0x001000000016ec14
- (void)insertEventWithMessage:(id)arg1 connection:(id)arg2;	// IMP=0x001000000016e888
- (void)getInternalSettingsWithMessage:(id)arg1 connection:(id)arg2;	// IMP=0x001000000016e787
- (void)configureDuet;	// IMP=0x001000000016e781
- (void)recordAnalyticsWithMetricsDialogEvent:(id)arg1 forTopic:(id)arg2;	// IMP=0x001000000016e4ea
- (void)observeXPCServer:(id)arg1;	// IMP=0x001000000016e428
- (void)dealloc;	// IMP=0x001000000016e33a
- (id)init;	// IMP=0x001000000016e255

@end

