//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <iTunesStore/ISOperation.h>

@class NSArray, NSNumber, NSString, SSDownloadPolicy, SSMemoryEntity;

@interface PrepareDownloadOperation : ISOperation
{
    SSMemoryEntity *_download;	// 96 = 0x60
    _Bool _ignoresDownloadHandler;	// 104 = 0x68
    NSArray *_mediaAssets;	// 112 = 0x70
    CDUnknownBlockType _outputBlock;	// 120 = 0x78
    SSDownloadPolicy *_policy;	// 128 = 0x80
}

+ (long long)_URLSessionTaskPriorityForDownloadPriority:(long long)arg1;	// IMP=0x002000000016b6d3
+ (long long)_URLSessionTaskPriorityForDownload:(id)arg1;	// IMP=0x001000000016b58b
+ (id)_mediaAssetsForDownloadIdentifier:(long long)arg1 session:(id)arg2;	// IMP=0x00100000001655b3
+ (_Bool)_isDTServiceHubIssuedRequest:(id)arg1;	// IMP=0x0010000000165518
+ (void)enumerateOperationsWithDownloadQuery:(id)arg1 session:(id)arg2 usingBlock:(CDUnknownBlockType)arg3;	// IMP=0x0010000000161e4f
- (void).cxx_destruct;	// IMP=0x002000000016b83e
- (_Bool)_usesStreamingZipDataConsumerForAsset:(id)arg1;	// IMP=0x001000000016b6f5
- (double)_transferProgressFractionWithAsset:(id)arg1;	// IMP=0x001000000016b31b
- (_Bool)_shouldFailForDiskSpaceWithAsset:(id)arg1 dataConsumer:(id)arg2;	// IMP=0x001000000016a532
- (_Bool)_shouldFailForFinishedDownload;	// IMP=0x001000000016a4e2
- (_Bool)_shouldCancelAutomaticDownload;	// IMP=0x001000000016a248
- (_Bool)_shouldCancelAsDuplicate;	// IMP=0x001000000016a16b
- (_Bool)_sendsStoreHeadersForAsset:(id)arg1;	// IMP=0x001000000016a0a5
- (_Bool)_requiresPoweredPluggedIn;	// IMP=0x0010000000169f36
- (void)_recordCoreAnalyticsEventForClient:(id)arg1 downloadKind:(id)arg2 url:(id)arg3;	// IMP=0x0010000000169c83
- (id)_newURLRequestWithAsset:(id)arg1;	// IMP=0x0010000000169640
- (id)_newDataConsumerWithAsset:(id)arg1 destinationPath:(id)arg2;	// IMP=0x0010000000169298
- (id)_newAVContentInfoDictionary;	// IMP=0x0010000000168ebb
- (id)_newAVAssetDownloadSessionOptionsWithAsset:(id)arg1 URLRequest:(id)arg2;	// IMP=0x0010000000168358
- (long long)_loadSizeForAsset:(id)arg1 error:(id *)arg2;	// IMP=0x0010000000167aa2
- (long long)_loadSizeIfNecessaryForAsset:(id)arg1;	// IMP=0x00100000001679f9
- (_Bool)_itemIsInSoftwareLibrary;	// IMP=0x00100000001678f2
- (_Bool)_itemIsInMediaLibrary;	// IMP=0x0010000000167629
- (id)_clientIdentifier;	// IMP=0x00100000001673ed
- (id)_bestMediaAsset;	// IMP=0x0010000000166aec
- (long long)_assetSizeFromURLResponse:(id)arg1;	// IMP=0x001000000016692a
- (_Bool)_assetNeedsDecryption:(id)arg1;	// IMP=0x0010000000166886
- (_Bool)_isPodcast;	// IMP=0x0010000000166836
- (_Bool)_isPodcastRestore;	// IMP=0x00100000001667c5
- (_Bool)_allowsCellularAccessForAsset:(id)arg1;	// IMP=0x0010000000165bfc
- (void)operation:(id)arg1 didReceiveResponse:(id)arg2;	// IMP=0x0010000000165503
- (long long)operation:(id)arg1 dispositionForAuthenticationChallenge:(id)arg2;	// IMP=0x00100000001654f8
- (void)run;	// IMP=0x0010000000162536
@property(copy) CDUnknownBlockType outputBlock;
@property _Bool ignoresDownloadHandler;
@property(readonly, nonatomic) long long downloadIdentifier;
- (id)_initWithDownload:(id)arg1 mediaAssets:(id)arg2 policy:(id)arg3;	// IMP=0x0010000000161d75

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"NSString",?,R,C

@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly, nonatomic) NSNumber *metricsLoadURLSamplingPercentage;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"NSNumber",?,R,N

@property(readonly, nonatomic) NSNumber *metricsLoadURLSamplingPercentageCachedResponses;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"NSNumber",?,R,N

@property(readonly, nonatomic) NSNumber *metricsLoadURLSessionDuration;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"NSNumber",?,R,N

@property(readonly) Class superclass;

@end

