//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class ISOperationQueue, LoadDownloadQueueOperation, NSMutableOrderedSet, NSMutableSet, NSNumber, NSSet;
@protocol OS_dispatch_queue;

@interface StoreDownloadQueue : NSObject
{
    NSMutableOrderedSet *_activeRestoreIDs;	// 8 = 0x8
    _Bool _automaticDownloadsAreDisabled;	// 16 = 0x10
    _Bool _checkAutomaticDownloadQueueOnEnable;	// 17 = 0x11
    NSObject<OS_dispatch_queue> *_dispatchQueue;	// 24 = 0x18
    NSNumber *_lastCheckedAccountID;	// 32 = 0x20
    LoadDownloadQueueOperation *_loadAutomaticDownloadQueueOperation;	// 40 = 0x28
    ISOperationQueue *_operationQueue;	// 48 = 0x30
    ISOperationQueue *_restoreOperationQueue;	// 56 = 0x38
    NSMutableSet *_storeQueueRequests;	// 64 = 0x40
    NSMutableOrderedSet *_trackedPurchaseDownloadIDs;	// 72 = 0x48
}

+ (void)triggerDownloadsWithMessage:(id)arg1 connection:(id)arg2;	// IMP=0x00400000000ad43e
+ (void)synchronizeAutomaticDownloadKindsWithMessage:(id)arg1 connection:(id)arg2;	// IMP=0x00100000000ad3bb
+ (void)setAutomaticDownloadKindsWithMessage:(id)arg1 connection:(id)arg2;	// IMP=0x00100000000acded
+ (void)reloadFromServerWithMessage:(id)arg1 connection:(id)arg2;	// IMP=0x00100000000ac9a2
+ (void)observeXPCServer:(id)arg1;	// IMP=0x00100000000ac8c7
+ (void)getAutomaticDownloadKindsWithMessage:(id)arg1 connection:(id)arg2;	// IMP=0x00100000000ac74c
+ (void)cancelRedownloadsWithMessage:(id)arg1 connection:(id)arg2;	// IMP=0x00100000000ac65f
+ (id)sharedDownloadQueue;	// IMP=0x00100000000a9838
- (void).cxx_destruct;	// IMP=0x00200000000b2f25
- (id)_validQueueIdentifiersForPlatform;	// IMP=0x00100000000b2e63
- (id)_validQueueIdentifiersForDaemon;	// IMP=0x00100000000b2c9d
- (void)_synchronizeAutomaticDownloadKinds:(CDUnknownBlockType)arg1;	// IMP=0x00100000000b29e3
- (void)_setLastCheckedAccountID:(id)arg1;	// IMP=0x00100000000b2934
- (id)_restorableDownloadsQueryInDatabase:(id)arg1;	// IMP=0x00100000000b26ff
- (void)_retrySoftFailedRestoreDownloads;	// IMP=0x00100000000b2461
- (void)_retryCanceledRestoreDownloads;	// IMP=0x00100000000b21b2
- (id)_newSetAutomaticDownloadKindsOperationWithDownloadKinds:(id)arg1 account:(id)arg2;	// IMP=0x00100000000b20ff
- (id)_newQueueRequestsWithReason:(id)arg1 accountID:(id)arg2 session:(id)arg3;	// IMP=0x00100000000b1ad3
- (id)_newOperationByCommitingAutomaticDownloadKinds:(id)arg1 account:(id)arg2;	// IMP=0x00100000000b1a08
- (id)_newLoadQueueOperationForQueueRequest:(id)arg1;	// IMP=0x00100000000b0c8f
- (id)_newCheckQueueOperationForQueueRequest:(id)arg1;	// IMP=0x00100000000afd78
- (_Bool)_ignoreVideos;	// IMP=0x00100000000afc94
- (void)_checkAutomaticDownloadQueue:(id)arg1;	// IMP=0x00100000000aed55
- (void)_handleMessage:(id)arg1 connection:(id)arg2 usingBlock:(CDUnknownBlockType)arg3;	// IMP=0x00100000000aebce
- (id)_downloadQueryWithQueueRequest:(id)arg1 database:(id)arg2;	// IMP=0x00100000000ae992
- (id)_automaticDownloadsQueryWithDatabase:(id)arg1 accountID:(id)arg2;	// IMP=0x00100000000ae805
- (void)_addOperationsForRequests:(id)arg1 reason:(id)arg2;	// IMP=0x00000000000adf64
- (void)_networkTypeChangedNotification:(id)arg1;	// IMP=0x00100000000ade5d
- (void)_accountStoreChangedNotification:(id)arg1;	// IMP=0x00100000000ad959
- (void)_accountAuthenticatedNotification:(id)arg1;	// IMP=0x00100000000ad690
- (void)synchronizeAutomaticDownloadKinds;	// IMP=0x00100000000ac64b
- (void)setAutomaticDownloadKinds:(id)arg1 account:(id)arg2;	// IMP=0x00100000000ac5dd
@property(copy, nonatomic) NSSet *automaticDownloadKinds;
- (void)restoreDownloadsWithIdentifiers:(id)arg1 reason:(id)arg2;	// IMP=0x00100000000abd86
- (void)restoreAllRestorableDownloadsWithReason:(id)arg1;	// IMP=0x00100000000abb66
@property(readonly, nonatomic) NSSet *enabledDownloadKinds;
- (void)enableAutomaticDownloadsWithReason:(id)arg1;	// IMP=0x00100000000ab6fd
- (void)disableAutomaticDownloadsWithReason:(id)arg1;	// IMP=0x00100000000ab4a4
@property(readonly) NSSet *downloadKindsBeingChecked;
- (void)commitAutomaticDownloadKinds:(id)arg1 markAsDirty:(_Bool)arg2;	// IMP=0x00100000000aabc7
- (void)checkQueuesWithRequest:(id)arg1;	// IMP=0x00100000000aaab5
- (_Bool)checkQueuesWithReason:(id)arg1 accountID:(id)arg2;	// IMP=0x00100000000aa851
- (void)checkAutomaticDownloadQueue;	// IMP=0x00100000000a9bf4
- (_Bool)cancelAllRedownloads;	// IMP=0x00100000000a9908
- (void)dealloc;	// IMP=0x00100000000a96c5
- (id)init;	// IMP=0x00100000000a9175

@end

