//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface SagaLibrary
{
}

+ (id)oversizeLogCategory;	// IMP=0x004000000011e852
+ (id)logCategory;	// IMP=0x001000000011e832
- (_Bool)_isEnabledWithURLBag:(id)arg1;	// IMP=0x004000000011e825
- (id)_bagKey;	// IMP=0x001000000011e818
- (id)_userIdentity;	// IMP=0x001000000011e7ad
- (id)initWithConfiguration:(id)arg1;	// IMP=0x001000000011e707

@end

