//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class NSDictionary, NSString;

@interface SagaCloudAddItemOperation
{
    long long _adamID;	// 16 = 0x10
    long long _referralAlbumAdamID;	// 24 = 0x18
    NSString *_referralPlaylistGlobalID;	// 32 = 0x20
    NSDictionary *_adamIDToSagaIDMap;	// 40 = 0x28
}

+ (_Bool)supportsSecureCoding;	// IMP=0x0040000000111519
- (void).cxx_destruct;	// IMP=0x0020000000110ac9
@property(retain, nonatomic) NSDictionary *adamIDToSagaIDMap; // @synthesize adamIDToSagaIDMap=_adamIDToSagaIDMap;
- (void)removePendingAddedItemsForPermanentlyFailedOperation;	// IMP=0x00100000001109a6
- (void)processAddedItems:(id)arg1;	// IMP=0x001000000011082f
- (void)logCloudAddRequestDescription;	// IMP=0x0010000000110790
- (id)cloudAddRequestWithDatabaseID:(unsigned int)arg1;	// IMP=0x0010000000110721
- (void)encodeWithCoder:(id)arg1;	// IMP=0x00100000001106a4
- (id)initWithCoder:(id)arg1;	// IMP=0x001000000011062a
- (id)initWithConfiguration:(id)arg1 adamID:(long long)arg2 referralPlaylistGlobalID:(id)arg3 clientIdentity:(id)arg4;	// IMP=0x00100000001105b1
- (id)initWithConfiguration:(id)arg1 adamID:(long long)arg2 referralAlbumAdamID:(long long)arg3 clientIdentity:(id)arg4;	// IMP=0x0010000000110581
- (id)initWithConfiguration:(id)arg1 adamID:(long long)arg2 clientIdentity:(id)arg3;	// IMP=0x001000000011053a

@end

