//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface UpdateArtistArtworkTokensOperation
{
}

- (id)_imageURLFromArtworkInfo:(id)arg1;	// IMP=0x0040000000070ca2
- (void)_addAllStoreArtistIDsToSet:(id)arg1;	// IMP=0x0010000000070be5
- (void)_addSpecificStoreArtistIDsToSet:(id)arg1;	// IMP=0x001000000007078f
- (void)main;	// IMP=0x0010000000070196

@end

